### ISSUE TITLE
Deleting endpoints for a nodePort service still allows access to the endpoint via service

### ISSUE THREAD

**Issue by trozet** [ovn-org/ovn-kubernetes#1109]
While testing #1096 I noticed this bug. Since it is not part of my changes for #1096 I believe it warrants  its own issue. The issue is that when a nodePort service has an endpoint, the load balancer is created in OVN the load balancer is created from the node IP -> pod. I believe this may be incorrect because I think the node IP should route to the cluster IP, and then to the pod IP (from what I see in the k8s docs).

During the deleteEndpoints function, there is no check for nodePort. So even though the clusterIP -> Pod load balance is removed, the one for the node IP -> Pod IP still exists.

For example, a nodePort svc like:

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  ports:
    - protocol: TCP
      port: 58585
      targetPort: 80
  type: NodePort

With endpoint:
apiVersion: v1
kind: Endpoints
metadata:
  name: my-service
subsets:
  - addresses:
      - ip: 10.244.0.5
    ports:
      - port: 80

Will result in the following load balancer:
_uuid               : 96b285d2-ad65-41b4-a905-73a6f9985d8d
external_ids        : {TCP_lb_gateway_router=GR_ovn-control-plane}
health_check        : []
ip_port_mappings    : {}
name                : ""
protocol            : tcp
vips                : {"169.254.33.2:30149"="10.244.0.5:80"}

Notice the node IP going directly to the pod. This is not cleaned up during deleteEndpoints and thus continues to function even when the service has no endpoints.

**Comment by trozet** [comment]
@dcbw @girishmg please assign to me. Also would appreciate your opinion on whether or not we should change nodePort behavior to go node IP->cluster IP->Pod IP, or if we should leave it as is. From the k8s page:
NodePort: Exposes the Service on each Node’s IP at a static port (the NodePort). **A ClusterIP Service, to which the NodePort Service routes**, is automatically created. You’ll be able to contact the NodePort Service, from outside the cluster, by requesting <NodeIP>:<NodePort>

**Comment by tssurya** [comment]
Closing this as it was fixed via https://github.com/ovn-org/ovn-kubernetes/pull/1074
