### ISSUE TITLE
validate cluster/service CIDRs against reserved IPs

### ISSUE THREAD

**Issue by danwinship** [ovn-org/ovn-kubernetes#1132]
ovn-kubernetes internally uses `100.64.0.0/16` (for IPv4) and `fd98::/64` (for IPv6) for the join network. It should require that the cluster/service CIDRs don't overlap these, since chaos would result if they did.

**Comment by girishmg** [comment]
@danwinship one of our new hires is looking at this. So not to duplicate are you working on a PR for this? If so, I will ask him not to work on it. Thanks.

**Comment by danwinship** [comment]
(clarified on slack; I'm not working on this, I just saw the problem and didn't want it to get forgotten about)
