### ISSUE TITLE
Remove support for old (pre-port group) OVN

### ISSUE THREAD

**Issue by danwinship** [ovn-org/ovn-kubernetes#1135]
We keep starting to have this conversation and then forgetting the details...

We should drop support for versions of OVN that don't support port groups, and then remove `pkg/ovn/policy_old.go`.

IIRC, the best answer anyone could come up with for why we still support old OVN is that there weren't new enough OVN packages on Windows. Is this still true? If so, do we care?

@dcbw @girishmg

**Comment by danwinship** [comment]
(Thinking about this in particular because of dual-stack and noticing that we'd end up having to double the total "volume" of address sets in order to match both IPv4 and IPv6 packets... except that it seems like instead we could just create a port group for each podSelector rather than an address set, and just not worry about IP addresses at all.)

**Comment by dcbw** [comment]
@danwinship @girishmg that's the only reason I recall; that the latest OVS/OVN that Cloudbase provides is 2.10.x: https://cloudbase.it/openvswitch/#download But 2.10 is 18+ months old already, so I guess unless we have significant numbers of users on Windows then for tech debt reasons we should probably remove it.

**Comment by girishmg** [comment]
@dcbw I agree
