### ISSUE TITLE
shared gateway mode does not support IPv6 / dual-stack

### ISSUE THREAD

**Issue by danwinship** [ovn-org/ovn-kubernetes#1141]
- [ ] `pkg/node/gateway_shared_intf.go:initSharedGateway()` assumes there is an IPv4 address on gateway
- [ ] `pkg/node/helper_linux.go:getDefaultGatewayInterfaceDetails()` only looks at IPv4 addresses/routing
- [x] ~`pkg/ovn/master.go:addStaticRouteToHost()` appends `"/32"` to an IP address~
- [ ] `pkg/util/nicstobridge.go:NicToBridge()` and `BridgeToNic()` only move IPv4 addresses/routes between NIC and bridge
- [ ] `pkg/ovn/master.go:StartClusterMaster()` needs to handle multiple subnets for shared gateway mode
- ... ?

**Comment by Billy99** [comment]
The following PRs were merged to address this issue:
#1462 - Update shared gateway to support IPv6/Dualstack
#1623 - IPv6 Shared-Gateway fixes
#1627 - Use flood for shared gw

**Comment by danwinship** [comment]
OK, this is mostly working at this point. Anything further can be individual bugs/PRs.
