### ISSUE TITLE
find a way to merge local and shared gateway modes

### ISSUE THREAD

**Issue by danwinship** [ovn-org/ovn-kubernetes#1193]
Having two fairly different modes for configuring nodes complicates the code, makes testing more difficult, and results in fixes sometimes being made for one version of the code but not the other (eg, #1141, #1126).

We should make a mode that solves everyone's problems and migrate everyone to that.

I believe the main reason OpenShift isn't using shared gateway mode is because it can result in the node's primary network interface getting broken if something goes wrong, rendering the node completely unreachable. But @dcbw can explain more.

I know one of the problems with local gateway mode is that it double-NATs traffic but I'm sure @girishmg can explain other problems with it. (It's also currently less-configurable than shared gateway mode.)

At one point @dcbw was working on a solution using `tc` to move traffic back and forth between the primary network interface and the OVN bridge without needing to actually add the interface to the bridge or remove its IP address. I'm not sure how far he got or what problems he encountered.

**Comment by dcbw** [comment]
> I believe the main reason OpenShift isn't using shared gateway mode is because it can result in the node's primary network interface getting broken if something goes wrong, rendering the node completely unreachable. But @dcbw can explain more.

Yes, that's the reason. In the past we've considered it too risky to touch the node's main network interface partly because we operate in so many scenarios (AWS, GCE, Azure, OpenStack, bare-metal, etc). If one thing goes wrong with moving the main NIC into the OVS bridge the node falls off the cluster.

Second, if the NIC is part of the OVS bridge and anything happens to OVS (stop container to upgrade it, crash, OVS gets wedged, flows get misconfigured) your node falls off the cluster.

Yes, none of these things should happen and we can have rollbacks and error handling. But it adds a ton of failure points and all of them result in the node falling off the cluster.

> I know one of the problems with local gateway mode is that it double-NATs traffic but I'm sure @girishmg can explain other problems with it. (It's also currently less-configurable than shared gateway mode.)

That is the main drawback.

> At one point @dcbw was working on a solution using `tc` to move traffic back and forth between the primary network interface and the OVN bridge without needing to actually add the interface to the bridge or remove its IP address. I'm not sure how far he got or what problems he encountered.

The main issues there were that it was somewhat fragile (eg stuff doesn't work and there's no good way to find out why), and (b) Girish was uncomfortable with recalling the conmarking of all packets because that might conflict with administrator local configuration. IIRC.

But I *also* had a solution to remove the double-NAT from the localnet gateway mode #755  that didn't work quite right, so I reworked that in #768 but never got around to review fixes. Maybe we could pick that back up as an interim?

**Comment by girishmg** [comment]
> > I believe the main reason OpenShift isn't using shared gateway mode is because it can result in the node's primary network interface getting broken if something goes wrong, rendering the node completely unreachable. But @dcbw can explain more.
> 
> Yes, that's the reason. In the past we've considered it too risky to touch the node's main network interface partly because we operate in so many scenarios (AWS, GCE, Azure, OpenStack, bare-metal, etc). If one thing goes wrong with moving the main NIC into the OVS bridge the node falls off the cluster.
> 
> Second, if the NIC is part of the OVS bridge and anything happens to OVS (stop container to upgrade it, crash, OVS gets wedged, flows get misconfigured) your node falls off the cluster.
> 
> Yes, none of these things should happen and we can have rollbacks and error handling. But it adds a ton of failure points and all of them result in the node falling off the cluster.

@dcbw most of the above are not issues if you are 'not' running ovs-vswitchd and ovsdb-server inside the containers and running only OVN and OVN-K8s components as pods.

When a host is provisioned it comes up with a supported version of OVS installed. We use host-based network configuration software to setup the OVS bridge using the underlying NIC as the uplink port. Thereafter, the OVS bridge is not touched from the configuration point of view, i.e. no replumbing of the interface with IP and routes.

The only thing that gets added to the OVS bridge by ovnkube-node are 
  -- OpenFlow rules for NodePort services and 
  -- initial OpenFlow rules for connection tracking the traffic leaving the OVN logical topology

The big advantage of this is that there are no `iptable` rules on the host and the entire datapath is done using OpenFlow rules and this can be completely offloaded to Smart NICs that support OVS offload.

> > I know one of the problems with local gateway mode is that it double-NATs traffic but I'm sure @girishmg can explain other problems with it. (It's also currently less-configurable than shared gateway mode.)
> 
> That is the main drawback.

In addition to double-NATing (there is no easy fix as can be seen in #755 and #768) drawback, the other main issue is that it provides partial-offload. The flows related to `br-int` gets offloaded, but will be pushed back to the host stack to match the IP table rules on the host.

**Comment by danwinship** [comment]
> When a host is provisioned it comes up with a supported version of OVS installed. We use host-based network configuration software to setup the OVS bridge using the underlying NIC as the uplink port. Thereafter, the OVS bridge is not touched from the configuration point of view, i.e. no replumbing of the interface with IP and routes.

This is a little tricker for us since OCP supports other network plugins, so the host can't just unconditionally configure things that way. Although I guess what we'd do is have the Cluster Network operator create appropriate MachineConfig objects to install configs / systemd units / whatever to the node, and then any nodes that were installed after that point would have the relevant files installed on first boot, so it wouldn't be awful...

> and this can be completely offloaded to Smart NICs that support OVS offload

which is a feature request we've heard mumbling about

**Comment by girishmg** [comment]
@danwinship PR #665 has already integrated support for OVS offload support to SmartNIC such as Mellanox. So, today with OVN-K8s + supported linux kernel + Mellanox hardware you can achieve OVS offloads (there are few flows that don't get offloaded due to missing support, but fixes are being pushed to Linux Kernel)

**Comment by trozet** [comment]
IMHO we should always use shared gateway, unless some specific platform cannot use it for some reason. Double NAT results in:

1. lower performance + extra L3 hop
2. us having to manage iptables rules on the host in our code
3. incompatibility with certain networking protocols

There are plenty of network management tools out there for openvswitch to guarantee configuration of moving NICs around does not corrupt a system (puppet, ansible, etc). It should not be hard to do this. Other platforms use an agent on the node itself to ensure configuration is always correct. We just need to make the jump, and still support local gateway until we can verify shared is stable on platforms we care about.

Reminds me that we need to add shared gateway jobs to KIND CI. @girishmg are you still working on that or do you want me to try to add them?

**Comment by zshi-redhat** [comment]
> IMHO we should always use shared gateway, unless some specific platform cannot use it for some reason. Double NAT results in:
> 
>     1. lower performance + extra L3 hop
> 
>     2. us having to manage iptables rules on the host in our code
> 
>     3. incompatibility with certain networking protocols
> 
+1 on using shared gateway mode.
Moving to shared gateway mode will allow us to enable ovs hw offload on openshift unless there is workaround to not use iptable rules in host network namespace for north/south traffic.

**Comment by danwinship** [comment]
Just as an update; OpenShift is planning to switch to shared gateway mode, and assuming we don't run into problems, we can eventually get rid of local gateway mode.

**Comment by tssurya** [comment]
This was fixed by https://github.com/ovn-org/ovn-kubernetes/pull/2663
Both modes are super close today. Closing this issue as its done.
