### ISSUE TITLE
Events are sometimes missed when watch terminates at same time as event

### ISSUE THREAD

**Issue by dcbw** [ovn-org/ovn-kubernetes#1202]
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/127/pull-ci-openshift-ovn-kubernetes-release-4.3-e2e-gcp-ovn/9

Around 20:08:xx an alertmanager-main-2 pod is created and ovnkube master sets up the logical port and IP address and annotates the pod. This is all fine.

Then at 20:14:16 the alertmanager-main-2 pod is deleted and re-created:

```
Mar 31 20:14:16.978942 ci-op-n7j7m-w-b-cjhn7.c.openshift-gce-devel-ci.internal hyperkube[1302]: I0331 20:14:16.978880    1302 kubelet.go:1924] SyncLoop (DELETE, "api"): "alertmanager-main-2_openshift-monitoring(aa3a7a1b-2e1a-450d-ac92-333fcb6788a1)"
Mar 31 20:14:16.986197 ci-op-n7j7m-w-b-cjhn7.c.openshift-gce-devel-ci.internal hyperkube[1302]: I0331 20:14:16.986145    1302 status_manager.go:581] Pod "alertmanager-main-2_openshift-monitoring(aa3a7a1b-2e1a-450d-ac92-333fcb6788a1)" fully terminated and removed from etcd
Mar 31 20:14:16.989904 ci-op-n7j7m-w-b-cjhn7.c.openshift-gce-devel-ci.internal hyperkube[1302]: I0331 20:14:16.989863    1302 status_manager.go:541] Pod "alertmanager-main-2" (aa3a7a1b-2e1a-450d-ac92-333fcb6788a1) does not exist on the server
Mar 31 20:14:16.999195 ci-op-n7j7m-w-b-cjhn7.c.openshift-gce-devel-ci.internal hyperkube[1302]: I0331 20:14:16.999151    1302 kubelet.go:1918] SyncLoop (REMOVE, "api"): "alertmanager-main-2_openshift-monitoring(aa3a7a1b-2e1a-450d-ac92-333fcb6788a1)"
Mar 31 20:14:16.999322 ci-op-n7j7m-w-b-cjhn7.c.openshift-gce-devel-ci.internal hyperkube[1302]: I0331 20:14:16.999219    1302 kubelet.go:2123] Failed to delete pod "alertmanager-main-2_openshift-monitoring(aa3a7a1b-2e1a-450d-ac92-333fcb6788a1)", err: pod not found
Mar 31 20:14:17.067238 ci-op-n7j7m-w-d-5v56r.c.openshift-gce-devel-ci.internal hyperkube[1308]: I0331 20:14:17.067198    1308 kubelet.go:1908] SyncLoop (ADD, "api"): "alertmanager-main-2_openshift-monitoring(14107337-49e3-4cfa-9269-356f1a6046f0)"
Mar 31 20:14:17.075940 ci-op-n7j7m-w-d-5v56r.c.openshift-gce-devel-ci.internal hyperkube[1308]: I0331 20:14:17.075886    1308 kubelet_pods.go:1328] Generating status for "alertmanager-main-2_openshift-monitoring(14107337-49e3-4cfa-9269-356f1a6046f0)"
```
So now the apiserver sees a different pod and it has no annotations yet because ovnkube master hasn't set up this new pod with the same name but different UID.

Around 20:14:17 something happens with the ovnkube master watches:

```
E0331 20:14:16.467171       1 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:openshift-ovn-kubernetes:ovn-kubernetes-controller" cannot list resource "namespaces" in API group "" at the cluster scope
E0331 20:14:16.473185       1 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:openshift-ovn-kubernetes:ovn-kubernetes-controller" cannot list resource "endpoints" in API group "" at the cluster scope
E0331 20:14:16.476774       1 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.NetworkPolicy: networkpolicies.networking.k8s.io is forbidden: User "system:serviceaccount:openshift-ovn-kubernetes:ovn-kubernetes-controller" cannot list resource "networkpolicies" in API group "networking.k8s.io" at the cluster scope
E0331 20:14:16.476939       1 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.Node: nodes is forbidden: User "system:serviceaccount:openshift-ovn-kubernetes:ovn-kubernetes-controller" cannot list resource "nodes" in API group "" at the cluster scope
E0331 20:14:16.488554       1 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:openshift-ovn-kubernetes:ovn-kubernetes-controller" cannot list resource "pods" in API group "" at the cluster scope
E0331 20:14:16.491583       1 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.Service: services is forbidden: User "system:serviceaccount:openshift-ovn-kubernetes:ovn-kubernetes-controller" cannot list resource "services" in API group "" at the cluster scope
```

Unfortunately that is exactly the same time as the new alertmanager-main-2 pod has been deleted and re-added to the apiserver.  The node tries to call CNI ADD:

```
time="2020-03-31T20:14:17Z" level=info msg="Waiting for ADD result for pod openshift-monitoring/alertmanager-main-2"
time="2020-03-31T20:14:17Z" level=info msg="[openshift-monitoring/alertmanager-main-2] dispatching pod network request &{ADD openshift-monitoring alertmanager-main-2 fa2b3c79582b47106333783c0f007ea6c75eac59e253444625011572bd4bbe8a /proc/7090/ns/net eth0 0xc000162b60}"
...
time="2020-03-31T20:14:39Z" level=info msg="[openshift-monitoring/alertmanager-main-2] CNI request &{ADD openshift-monitoring alertmanager-main-2 fa2b3c79582b47106333783c0f007ea6c75eac59e253444625011572bd4bbe8a /proc/7090/ns/net eth0 0xc000162b60}, result \"\", err failed to get pod annotation: timed out waiting for the condition"
time="2020-03-31T20:14:39Z" level=info msg="Waiting for DEL result for pod openshift-monitoring/alertmanager-main-2"
```

Maybe we need to check annotations in `WatchPods()`, perhaps like so?

```
		UpdateFunc: func(old, newer interface{}) {
			pod := newer.(*kapi.Pod)
			if !podWantsNetwork(pod) {
				return
			}

			if podScheduled(pod) {
				podInfo, err := util.UnmarshalPodAnnotation(pod)
				_, retry := retryPods.Load(pod.UID)
				if  podInfo == nil || retry {
					if err := oc.addLogicalPort(pod); err != nil {
						klog.Errorf(err.Error())
					} else {
						retryPods.Delete(pod.UID)
					}
				}
			}
		},
```

**Comment by dcbw** [comment]
Another thought, maybe we need https://github.com/kubernetes/kubernetes/pull/83911 in our client-go?

**Comment by dcbw** [comment]
@girishmg @danwinship @trozet

**Comment by girishmg** [comment]
> E0331 20:14:16.467171       1 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:openshift-ovn-kubernetes:ovn-kubernetes-controller" cannot list resource "namespaces" in API group "" at the cluster scope
> E0331 20:14:16.473185       1 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:openshift-ovn-kubernetes:ovn-kubernetes-controller" cannot list resource "endpoints" in API group "" at the cluster scope
> E0331 20:14:16.476774       1 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.NetworkPolicy: networkpolicies.networking.k8s.io is forbidden: User "system:serviceaccount:openshift-ovn-kubernetes:ovn-kubernetes-controller" cannot list resource "networkpolicies" in API group "networking.k8s.io" at the cluster scope
> E0331 20:14:16.476939       1 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.Node: nodes is forbidden: User "system:serviceaccount:openshift-ovn-kubernetes:ovn-kubernetes-controller" cannot list resource "nodes" in API group "" at the cluster scope
> E0331 20:14:16.488554       1 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:openshift-ovn-kubernetes:ovn-kubernetes-controller" cannot list resource "pods" in API group "" at the cluster scope
> E0331 20:14:16.491583       1 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.Service: services is forbidden: User "system:serviceaccount:openshift-ovn-kubernetes:ovn-kubernetes-controller" cannot list resource "services" in API group "" at the cluster scope

I have seen these errors whenever cluster role binding goes missing. Perhaps someone deleted and added it back.

> Maybe we need to check annotations in `WatchPods()`, perhaps like so?

Yes, this should help assuming there is an update to the pod.

**Comment by danwinship** [comment]
> Another thought, maybe we need [kubernetes/kubernetes#83911](https://github.com/kubernetes/kubernetes/pull/83911) in our client-go?

Yes. You're not supposed to have to do anything special when the watch terminates. This is totally that bug. We'll need to backport that too.

@girishmg I believe the role-binding-related errors here are irrelevant and are just because ovn-kubernetes gets started early in the cluster install process before the cluster is fully set-up.
