### ISSUE TITLE
Create github action trigger to re-run CI on PRs

### ISSUE THREAD

**Issue by trozet** [ovn-org/ovn-kubernetes#1216]
I've tried:

name: Go
on:
push:
pull_request:
pull_request_review_comment:
types:
- created

And then in under the jobs doing:
verify:
name: Verify
runs-on: ubuntu-latest
if: github.event_name == 'pull_request' || github.event_name == 'push' || github.event.pull_request_review_comment.comment.body == '/retest'

but it doesn't seem to trigger.

**Comment by dave-tucker** [comment]
It's definintely `issue_comment` you want.
From the docs:
https://developer.github.com/v3/activity/events/types/#pullrequestreviewcommentevent
> Triggered when a comment on a pull request's unified diff is created, edited, or deleted (in the Files Changed tab).

https://developer.github.com/v3/activity/events/types/#issuecommentevent
> Triggered when an issue comment is created, edited, or deleted.

Weird GitHub API quirk is that PR's are actually issues too.

> Note: GitHub's REST API v3 considers every pull request an issue, but not every issue is a pull request. For this reason, "Issues" endpoints may return both issues and pull requests in the response. You can identify pull requests by the pull_request key.

**Comment by trozet** [comment]
@dave-tucker I had tried issue comment first, and then switched to PR comment. For PR comment I tried going to files changed, reviewing and adding an inline comment, then deleting it. Nothing would seem to trigger it on my fork of ovn-kubernetes.
