### ISSUE TITLE
leverage support for both master and node mode in single ovnkube process on k8s master nodes

### ISSUE THREAD

**Issue by girishmg** [ovn-org/ovn-kubernetes#1317]
A single instance of ovnkube process already supports both master and node mode. The commentary in PR #1313 got me to think whether we should leverage this on the k8s master nodes. 

This would let us 
- not to run two instances of ovnkube on the master nodes
- we can force the ovnkube-node daemonset to not to run on masters using nodeAntiAffinity or some such

@ovn-org/ovn-kubernetes-committers thoughts?

**Comment by danwinship** [comment]
I feel like it would make more sense to just split ovnkube into two separate binaries. It doesn't make any sense to have the master and node code in the same process if the two "sides" only ever communicate with each other by writing to the OVN and Kubernetes databases...
