### ISSUE TITLE
kind: e2e external gateway connectivity test without using macvlan interface

### ISSUE THREAD

**Issue by girishmg** [ovn-org/ovn-kubernetes#1364]
Any reason why we are creating a macvlan interface on one of the worker nodes container and performing the connectivity test? Currently, we create a `macvlan` interface on ovn-worker node and then create a Pod in ovn-worker2 and ping the macvlan interface from that Pod.

```
+------------------+  +-------------+    +-------------+             
|ovn-control-plane |  |ovn-worker   |    |ovn-worker2  |   docker0   
|                  |  |             |    |             |  172.17.0.1 
|                  |  |             |    |             |    |        
|     172.17.0.2   |  | 172.17.0.3  |    | 172.17.0.4  |    |        
+-------+----------+  +-----+-------+    +-----+-------+    |        
        |                   |                  |            |        
+-------+-------------------+------------------+------------+-----+  
|                          Linux Bridge                           |  
+-----------------------------------------------------------------+  
```

Why can't we just ping 172.17.0.1 address on `docker0` interface that is present on the running host?

The reason I ask is that while running the tests in `shared` gateway mode, the underlying physical interface `eth0` is an uplink of an OVS bridge, So, trying to create a `macvlan` on eth0 will fail

```
error running /home/runner/go/src/k8s.io/kubernetes/_output/bin/kubectl --server=https://10.1.0.4:11337 --kubeconfig=/home/runner/admin.conf exec ovnkube-node-wpfll --namespace=ovn-kubernetes --container=ovnkube-node -- ip link add macvlan0 link eth0 type macvlan mode bridge:
Command stdout:

stderr:
RTNETLINK answers: Device or resource busy
command terminated with exit code 2

error:
exit status 2
```

@nerdalert @dcbw PTAL

**Comment by girishmg** [comment]
Please see this error at https://github.com/ovn-org/ovn-kubernetes/pull/1363/checks?check_run_id=707422542 for reference..

**Comment by girishmg** [comment]
@nerdalert will it be an issue if we move to using the `docker0` interface for this particular test?

**Comment by nerdalert** [comment]
Hi @girishmg the first plan was to simulate ex_gw using macvlan. The final iteration is here https://github.com/ovn-org/ovn-kubernetes/pull/1272. The Macvlan gets removed in that PR. It is ready to merge, as soon as I can get the CI to run. For some reason it won't kick on that PR anymore. Thanks!

**Comment by girishmg** [comment]
closing this issue since we don't use macvlan interface.. look at #1272
