### ISSUE TITLE
kind deployment hangs after ~450 containers are started and stopped

### ISSUE THREAD

**Issue by as-com** [ovn-org/ovn-kubernetes#1380]
This test often results in the cluster hanging/freezing: https://github.com/as-com/ovn-kubernetes/blob/19e1ee941235c1c6f1963fa84637fa62cad5ebb2/test/e2e/e2e_test.go#L595-L684

Here is an example of one such run in GitHub Actions: https://github.com/as-com/ovn-kubernetes/runs/721262002?check_suite_focus=true#step:9:8997

Notice how the next test in the suite hangs for a few hours before being cancelled.

Previous test runs have printed error messages mentioning etcserver timeouts. Similar behavior is observed on my lab machine. Logs: [kind.tar.gz](https://github.com/ovn-org/ovn-kubernetes/files/4725572/kind.tar.gz)

**Comment by aojea** [comment]
I'm not familiar with the ovn ipam, so apologize in advance, but that seems that you have 
```
pec:NodeSpec{PodCIDR:10.244.2.0/24,
```

a /24 contains 253 free IPs, using 2 nodes ~500 pods in a cluster.
Maybe what happens is that you are running out of IPs and the new pods are waiting that a IP is released so they can acquire it?

**Comment by as-com** [comment]
nb: the party is over here: https://github.com/ovn-org/ovn-kubernetes/pull/1358

**Comment by as-com** [comment]
closing due to likely cause being IP/MAC address space exhaustion
