### ISSUE TITLE
fix util packages for finding n'th IP in a subnet

### ISSUE THREAD

**Issue by trozet** [ovn-org/ovn-kubernetes#1386]
current util functions call each other and end up recursively doing NextIP() n number of times. This is inefficient and a waste of function calls. Refactor these functions to just do byte arithmetic or some other method to directly get the n'th IP addr:

// GetNodeGatewayIfAddr returns the node logical switch gateway address
// (the ".1" address)
func GetNodeGatewayIfAddr(subnet *net.IPNet) *net.IPNet {
	return &net.IPNet{IP: NextIP(subnet.IP), Mask: subnet.Mask}
}

// GetNodeManagementIfAddr returns the node logical switch management port address
// (the ".2" address)
func GetNodeManagementIfAddr(subnet *net.IPNet) *net.IPNet {
	gwIfAddr := GetNodeGatewayIfAddr(subnet)
	return &net.IPNet{IP: NextIP(gwIfAddr.IP), Mask: subnet.Mask}
}

// GetNodeHybridOverlayIfAddr returns the node logical switch hybrid overlay
// port address (the ".3" address)
func GetNodeHybridOverlayIfAddr(subnet *net.IPNet) *net.IPNet {
	mgmtIfAddr := GetNodeManagementIfAddr(subnet)
	return &net.IPNet{IP: NextIP(mgmtIfAddr.IP), Mask: subnet.Mask}
}

**Comment by danwinship** [comment]
yeah, see discussion in #1367; there's no reason to be using bignum math here
