### ISSUE TITLE
Flakes in hybrid overlay pod annotation sync code

### ISSUE THREAD

**Issue by dcbw** [ovn-org/ovn-kubernetes#1413]
https://github.com/ovn-org/ovn-kubernetes/pull/1410/checks?check_run_id=760821334

@dave-tucker

**Comment by girishmg** [comment]
@dcbw @dave-tucker it seems to be more than a flake for me atleast :(. My `make check` consistently fails 50% of the times. I used this to just run the tests in `ovn` package

```
[root@k8s-master go-controller]# for i in {1..4}; do go clean --testcache; make clean; PKGS=github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn hack/test-go.sh; sleep 1; done
```

**Comment by dave-tucker** [comment]
@girishmg I was looking at the tests in the `control-plane` suite which were to do with hybrid-overlay.
I think you're referring to a unit test `[it] resets the hybrid annotations on update` which I think @trozet added. That's also been failing a few times for me, but I'm not sure it's related to this issue.

**Comment by dave-tucker** [comment]
I ran the `ovn` tests 30 times against the tip of master and only saw one flake:

`[It] does not allocate a hostsubnet for a node that already has one` :shrug:

**Comment by trozet** [comment]
• Failure [0.112 seconds]
OVN Pod Operations
/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/ovn/pods_test.go:162
  with hybrid overlay gw mode
  /home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/ovn/pods_test.go:667
    resets the hybrid annotations on update [It]
    /home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/ovn/pods_test.go:668

    Expected
        <string>: {"default":{"ip_addresses":["10.128.1.5/24"],"mac_address":"11:22:33:44:55:66","gateway_ips":["10.128.1.3"],"routes":[{"dest":"10.128.0.0/14","nextHop":"10.128.1.1"},{"dest":"172.16.1.0/24","nextHop":"10.128.1.1"},{"dest":"10.132.0.0/14","nextHop":"10.128.1.3"}],"ip_address":"10.128.1.5/24","gateway_ip":"10.128.1.3"}}
    to contain substring
        <string>: "gateway_ip":"10.128.1.1"

    /home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/ovn/pods_test.go:736

**Comment by trozet** [comment]
This is either a race condition in the test between when the namespace is updated and the new pod is created (namespace has not finished updating by the time the pod is created), or there is a real race in our HO code. I'll add some more checks to the namespace update in the test case to rule out the former. However, I cannot seem to reproduce this locally, even running what you mentioned @girishmg so I might need your help to check the results.
