### ISSUE TITLE
hybrid overlay dual-stack support

### ISSUE THREAD

**Issue by danwinship** [ovn-org/ovn-kubernetes#1495]
We need dual-stack support for the hybrid overlay code.

  - [ ] master calls subnetallocator.AllocateNetworkRange() assuming IPv4 (#1493)
  - [ ] config allows for dual-stack HO subnets but annotation does not (WIP)
  - [ ] master.go handleOverlayPort() has "// FIXME DUAL-STACK"
  - [ ] node.go getNodeSubnetAndIP() has "// FIXME DUAL-STACK" (which will change its return value and propagate outward)
  - [ ] node_linux.go is explicitly IPv4-only
  - [ ] node_windows.go configures an IPv4 "fake" network and may have other IPv4-only dependencies?
  - [ ] overlay_windows.go is single-stack (and possibly IPv4-only)
  - [ ] pkg/ovn/pods.go : Method addRoutesGatewayIP needs to handle dual stack aspects for hybridOverlayExternalGW.

It's possible we don't care about IPv6/dual-stack support in the Linux/Windows hybrid case?

**Comment by gvbalaji** [comment]
I will start looking at this item @danwinship 
master.go handleOverlayPort() has "// FIXME DUAL-STACK"

**Comment by gvbalaji** [comment]
An additional TODos in dual stack I found is this. @danwinship 

pkg/ovn/pods.go : Method addRoutesGatewayIP needs to handle dual stack aspects for hybridOverlayExternalGW.

**Comment by gvbalaji** [comment]
I'll start looking into
 node.go getNodeSubnetAndIP() has "// FIXME DUAL-STACK" (which will change its return value and propagate outward)

**Comment by gvbalaji** [comment]
Understand that windows HO Vxlan support is v4 only. They are planning to support v6 in future.   We need to understand the dual stack aspects of F5 integration which @dcbw would gather in Thursday's Verizon call
1. Weather F5 supports v6/dual stack.
2. If the external gateway annotations for HO need to support multiple addresses.

Much of the work above depends on answers to these.
