### ISSUE TITLE
e2e test fails on IPv6 Only - should resolve connection reset issue

### ISSUE THREAD

**Issue by Billy99** [ovn-org/ovn-kubernetes#1516]
The Kubernetes E2E test `should resolve connection reset issue #74839 [Slow]` defined in `k8s.io/kubernetes/test/e2e/network/kube_proxy.go` fails 100% in IPv6 only deployment.

Investigating the test, it launches an image defined by `k8s.io/kubernetes/test/image/regression-issue-74839\`. In this image, there is a function defined in `k8s.io/kubernetes/test/image/regression-issue-74839/main.go` that fails:

```
func getIP() net.IP {
	conn, err := net.Dial("udp", "8.8.8.8:53")
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close()

	localAddr := conn.LocalAddr().(*net.UDPAddr)

	return localAddr.IP
}
```
In an IPv6 only deploy, dialling 8.8.8.8 will fail. This issue is tracking getting this fixed in upstream E2E.

**Comment by Billy99** [comment]
Upstream issue:
https://github.com/kubernetes/kubernetes/issues/93281

**Comment by tssurya** [comment]
We don't deploy kubeproxy, closing this issue as its stale.
