### ISSUE TITLE
e2e test fails on IPv6 Only - should allow egress access to server in CIDR block

### ISSUE THREAD

**Issue by Billy99** [ovn-org/ovn-kubernetes#1517]
The Kubernetes E2E test `should allow egress access to server in CIDR block [Feature:NetworkPolicy]` defined in `k8s.io/kubernetes/test/e2e/network/network_policy.go` fails 100% in IPv6 only deployment.

Still investigating why this fails.

**Comment by tssurya** [comment]
This test is passing now, we are not skipping conformance tests. Closing this issue
