### ISSUE TITLE
Github CI doesn´t offer IPv6 connectivity

### ISSUE THREAD

**Issue by Billy99** [ovn-org/ovn-kubernetes#1522]
Since Github CI doesn´t offer IPv6 connectivity, IPv6 specific tests are blocked. If/When Github CI provides IPv6 connectivity, these tests (one for now) need to be unblocked.

**Comment by tssurya** [comment]
We enabled IPV6 lanes in control plane via https://github.com/ovn-org/ovn-kubernetes/pull/4106
All issues with this label: https://github.com/ovn-org/ovn-kubernetes/labels/ci-ipv6 are currently addressing this issue
Closing this.
