### ISSUE TITLE
Refactor ovnkube-node

### ISSUE THREAD

**Issue by alexanderConstantinescu** [ovn-org/ovn-kubernetes#1549]
Today ovnkube-node runs in two mode (local vs shared), these modes are prevalent in the code and taken into account (in the sense that the code is logically organised to deal with those cases appropriately).  We however also run on two different OS-es (windows / linux) which is, today, not at all as well thought as the first case, which leads to us having awkward looking code like this:

`pkg/node/gateway_shared_intf_windows.go `
```
func initSharedGatewayIPTables() error {
	return nil
}

func cleanupSharedGatewayIPTChains() {
}

func addSharedGatewayIptRules(service *kapi.Service, nodeIP *net.IPNet) {
}

func delSharedGatewayIptRules(service *kapi.Service, nodeIP *net.IPNet) {
}

func syncSharedGatewayIptRules(services []interface{}, nodeIP *net.IPNet) {
}
```

This also is the underlying reason we have race conditions being triggered on the node side for testing. We are using singletons here: https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/util/iptables.go#L35 which are due to wanting to test iptables state. If we would properly encapsulate all modes (local vs shared vs linux vs windows) we could just embed the iptables helper into a `OvnLinuxNode` object and properly test and execute code without singletons....we would also avoid having goofy looking code like `initSharedGatewayIPTables` in a windows specific file.

**Comment by danwinship** [comment]
Windows support is going away soon (#1534) and probably local gateway support will go away in 6 months or so assuming everything works out with shared gateway mode in OpenShift (#1193).

So, yes, things are terrible now, but it will probably be fixed without needing a refactoring. (Though we'll need a lot of cleanup to remove no-longer-necessary abstraction layers.)
