### ISSUE TITLE
E0729 13:45:01.810595       1 master.go:203] Failed to get northd_probe_interval value stderr(ovn-nbctl: no key "northd_probe_interval" in NB_Global record "." column options

### ISSUE THREAD

**Issue by trozet** [ovn-org/ovn-kubernetes#1553]
In ovn-kube we set the northd probe interval via bash:

```
set_northd_probe_interval() {
  # OVN_NORTHD_PROBE_INTERVAL - probe interval of northd for NB and SB DB
  # connections in ms (default 5000)
  northd_probe_interval=${OVN_NORTHD_PROBE_INTERVAL:-5000}

  echo "setting northd probe interval to ${northd_probe_interval} ms"

  # this call will fail on non-leader node since we are using unix socket and no --no-leader-only option.
  output=$(ovn-nbctl --if-exists get NB_GLOBAL . options:northd_probe_interval)
  if [[ $? == 0 ]]; then
    output=$(echo ${output} | tr -d '\"')
    echo "the current value of northd probe interval is ${output} ms"
    if [[ "${output}" != "${northd_probe_interval}" ]]; then
      ovn-nbctl set NB_GLOBAL . options:northd_probe_interval=${northd_probe_interval}
      if [[ $? != 0 ]]; then
        echo "Failed to set northd probe interval to ${northd_probe_interval}. Exiting....."
        exit 13
      fi
      echo "successfully set northd probe interval to ${northd_probe_interval} ms"
    fi
  fi
  return 0
}

```

The problem is in openshift we dont use this bash, so we constantly see the error in the $subject spammed in our logs. I'm thinking we shouldnt set some DB option in bash, and then check it in go lang if we can avoid it. @girishmg is there a reason we cannot set the value also in go code with a config option to ovn-kubernetes?

**Comment by trozet** [comment]
@dcbw FYI

**Comment by danwinship** [comment]
We should talk in the community meeting about doing setup in bash/daemonsets vs doing setup in golang.

**Comment by girishmg** [comment]
@trozet @danwinship certain things need to be setup during the raft cluster build time, like election timer.

However, we could set northd_probe_interval from the golang. We already set openflow_probe_interval and remote_probe_interval from golang. We can definitely talk about this during the community meeting.

**Comment by abhat** [comment]
🤷‍♂️ what is the best way to assign an issue to yourself?

**Comment by abhat** [comment]
Can someone close this now that it is fixed?
