### ISSUE TITLE
Smart NIC Support for OVN-Kubernetes

### ISSUE THREAD

**Issue by moshe010** [ovn-org/ovn-kubernetes#1558]
Add support for Smart-NIC which is a NIC with an embedded CPU e.g Mellanox BlueField 2 DPU [1]  
Link for design proposal [2]. if required we would be happy to explain use-case/design in the bi-weekly meeting. 

[1] - https://www.mellanox.com/products/bluefield2-overview
[2] - https://docs.google.com/document/d/1ZPzEHyyTJ86J81srdntbJVBTCvtQQ94QycaLgzOHjiQ/edit?pli=1#

**Comment by adrianchiris** [comment]
Updated link to the doc.
https://docs.google.com/document/d/11IoMKiohK7hIyIE36FJmwJv46DEBx52a4fqvrpCBBcg/edit?usp=sharing
