### ISSUE TITLE
Jobs timing out due to test failures

### ISSUE THREAD

**Issue by aojea** [ovn-org/ovn-kubernetes#1584]
I could observe that there is a pattern of PR job failures, where some jobs pass all tests and one job times our because all tests hangs.
You can identify them using the following query
https://github.com/ovn-org/ovn-kubernetes/actions?query=is%3Afailure++workflow%3Aovn-ci

Look for the jobs that take more than 1 hours, the longer the better.

And then, check that it has at least 3 jobs passed and the jobs that failed, in the step `Run Tests` have an anomalous duration (it should take 20 mins max)

An example is this
https://github.com/ovn-org/ovn-kubernetes/actions/runs/194857569

The PR does not touch any code, neither in the gates nor ovn-kubernetes , is a change in the periodic job.
3 e2e jobs are completely green
This e2e job took 2 hours to finish https://github.com/ovn-org/ovn-kubernetes/runs/945242896?check_suite_focus=true

**Comment by trozet** [comment]
From reading the logs it looks like the issue is pod creation in add logical port is getting stuck. Meaning that I see pods getting created early in the logs, and then I never see the defer log for the amount of time taken to create the port. I believe there may be some kind of dead lock happening here. Future pods that are created in kapi are seen in the informer watch, but do not receive corresponding add logical port info logs. Also indicating to me that all the handlers are hung and are not processing the new pods.

**Comment by trozet** [comment]
The original log I looked at was:
https://github.com/ovn-org/ovn-kubernetes/runs/946421252?check_suite_focus=true

The log in this issue looks to be a little different.

**Comment by trozet** [comment]
First bug found while investigating has to do with metrics not being properly setup:
https://github.com/ovn-org/ovn-kubernetes/pull/1585

I don't think this has anything to do with test failures, but it is getting in the way of debugging with the constant log spam.

**Comment by abhat** [comment]
Not sure if it's related. But I found a bug in ovn-nbctl during `lr_nat_add` where it doesn't honor `--may-exist`. This was causing init gateway to fail and therefore nodes to be not ready. I think that will cause `waitForNodeLogicalSwitch` to get blocked. I submitted a patch upstream to ovn to fix it. After fixing the nbctl issue, I see that we can resolve pods correctly.

**Comment by trozet** [comment]
> Not sure if it's related. But I found a bug in ovn-nbctl during `lr_nat_add` where it doesn't honor `--may-exist`. This was causing init gateway to fail and therefore nodes to be not ready. I think that will cause `waitForNodeLogicalSwitch` to get blocked. I submitted a patch upstream to ovn to fix it. After fixing the nbctl issue, I see that we can resolve pods correctly.

I took a look through the logs. I don't think this is what we are seeing for this particular issue.

**Comment by aojea** [comment]
another occurrence https://github.com/ovn-org/ovn-kubernetes/runs/967329034?check_suite_focus=true
```
/home/runner/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/network_policy.go:1522
2020-08-10T15:43:12.8077224Z [90m------------------------------[0m
2020-08-10T15:47:33.6787326Z {"msg":"FAILED [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should enforce policy based on Ports [Feature:NetworkPolicy]","total":-1,"completed":3,"skipped":511,"failed":1,"failures":["[sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client should enforce policy based on Ports [Feature:NetworkPolicy]"]}
```

after this all test fails timing out, it seems is blocking the DNS requests

```
2020-08-10T15:43:06.2171324Z Pod logs:
2020-08-10T15:43:06.2171670Z nc: bad address 'svc-server.network-policy-5888'
2020-08-10T15:43:06.2172020Z nc: bad address 'svc-server.network-policy-5888'
```

**Comment by aojea** [comment]
While debugging this I realized we are processing events that are set for deletion

```
ovn-kubernetes/ovnkube-master.log-I0810 16:14:28.678005      48 namespace.go:234] Updating namespace: network-policy-4327
ovn-kubernetes/ovnkube-master.log:I0810 16:14:28.686720      48 namespace.go:320] Deleting namespace: network-policy-4327
ovn-kubernetes/ovnkube-master.log-I0810 16:16:18.053918      48 namespace.go:234] Updating namespace: dns-8578
ovn-kubernetes/ovnkube-master.log:I0810 16:16:18.063031      48 namespace.go:320] Deleting namespace: dns-8578
ovn-kubernetes/ovnkube-master.log-I0810 16:19:10.927456      48 namespace.go:234] Updating namespace: dns-4668
ovn-kubernetes/ovnkube-master.log:I0810 16:19:10.938137      48 namespace.go:320] Deleting namespace: dns-4668
ovn-kubernetes/ovnkube-master.log-I0810 16:19:10.977691      48 namespace.go:234] Updating namespace: services-8408
ovn-kubernetes/ovnkube-master.log:I0810 16:19:10.984453      48 namespace.go:320] Deleting namespace: services-8408
ovn-kubernetes/ovnkube-master.log-I0810 16:19:28.024564      48 namespace.go:234] Updating namespace: network-policy-4486
ovn-kubernetes/ovnkube-master.log:I0810 16:19:28.031899      48 namespace.go:320] Deleting namespace: network-policy-4486
ovn-kubernetes/ovnkube-master.log-I0810 16:24:15.471623      48 namespace.go:234] Updating namespace: dns-1970
ovn-kubernetes/ovnkube-master.log:I0810 16:24:15.479731      48 namespace.go:320] Deleting namespace: dns-1970
ovn-kubernetes/ovnkube-master.log-I0810 16:24:28.823559      48 namespace.go:234] Updating namespace: network-policy-6806
ovn-kubernetes/ovnkube-master.log:I0810 16:24:28.839489      48 namespace.go:320] Deleting namespace: network-policy-6806
ovn-kubernetes/ovnkube-master.log-I0810 16:24:38.760781      48 namespace.go:234] Updating namespace: nettest-6553
ovn-kubernetes/ovnkube-master.log:I0810 16:24:38.768998      48 namespace.go:320] Deleting namespace: nettest-6553
ovn-kubernetes/ovnkube-master.log-I0810 16:26:22.776583      48 namespace.go:234] Updating namespace: dns-9831
```

this may cause inconsistencies, fix here https://github.com/ovn-org/ovn-kubernetes/pull/1604
