### ISSUE TITLE
Master node gets isolated when the ovnkube-node pod is deleted with HA and shared gateway

### ISSUE THREAD

**Issue by aojea** [ovn-org/ovn-kubernetes#1599]
I was consistently hitting this problem during the refactor of the e2e control-plane tests that delete the ovnkube-node to check that it does not drop the traffic.

Current tests force an immediate deletion of the test
https://github.com/ovn-org/ovn-kubernetes/blob/bb6081af58fd9d90996af9427c924eefa7a2240f/test/e2e/e2e_test.go#L269
However, I didn't realize about it and was using the Delete Pod api call with the default options, causing that all the jobs using HA and shared gateway failed.

The logs always showed that one of the node has lost the connectivity against the others.

There is an occurrence here 
https://github.com/ovn-org/ovn-kubernetes/runs/958568934?check_suite_focus=true

**Comment by aojea** [comment]
A quick fix is to create those pods with the GracePeriod to 0, but I can not understand why it only happens in HA mode.
Is that the communication between the master and ovn is lost and is not able to recover?

**Comment by girishmg** [comment]
@aojea there are several things in play here.

1. OVS daemons are shipped as a container in ovnkube-node
2. The ovnkube-node moves the host networking stack to OVS bridge model like below

In shared-gateway mode, we start with the node like this:
```
+--------------------------+
|Node1                     |
|                          |
|                          |
|     +--------+           |
+-----+  eth0  +-----------+
      +--------+    
```
and the code in ovnkube-node changes the host networking stack to 

```
+---------------------------+
|Node1                      |
|                           |
|                           |
|    br-eth0                |
|       |                   |
|       |                   |
|      ++---------+         |
|      | br-eth0  |         |
|      +----+-----+         |
|           |               |
|       +---+----+          |
+-------+  eth0  +----------+
        +--------+       
```

When you delete the ovnkube-node, you also delete the OVS daemons and the OVS bridge setup on the host is hosed. So, you lose connection to the host.

So, when we delete the node as part of shutdown we can convert the host stack back to figure 1 above.

**Comment by girishmg** [comment]
@aojea Another problem is when you delete a K8s node using `kubectl delete node`, the kubelet doesn't provide graceful shutdown semantics for the daemonset pods. So, the containers running inside the daemonset will not get SIGTERM for it to handle certain things. So, this is very tricky to get it work.

In production and serious deployments, the OVS is choice of software for host networking. So, deployers will not run OVS in containers. Hence, it is not a problem in use cases like that.

**Comment by aojea** [comment]
> In production and serious deployments, the OVS is choice of software for host networking. So, deployers will not run OVS in containers. 

just for confirmation,  running ovs in the host does not have any of the problems? or do we still to revert back the host stack?

**Comment by girishmg** [comment]
@aojea Yes, running OVS in the host does not have any problems. The OVS bridge on the host is setup ahead of time. The `ovnkube-node` Pod doesn't run ovs-daemons container.

**Comment by danwinship** [comment]
So yeah, the way the daemonsets are set up currently, we should not be testing that you can delete the ovnkube pods when using shared gateway mode.

We should probably move the ovs pods out of the ovnkube-node DaemonSet into a separate DaemonSet, and note that (a) you only need to run that DS if you don't have OVS on the host, and (b) if you run OVS in containers in shared gateway mode, then it's not safe to kill those containers

**Comment by aojea** [comment]
> In production and serious deployments, the OVS is choice of software for host networking. So, deployers will not run OVS in containers. Hence, it is not a problem in use cases like that.

I think that the test scenarios should be as close as possible to production, so I modified the CI to run OVS in the nodes instead of pods.

https://github.com/ovn-org/ovn-kubernetes/pull/1561/commits/26e10f9b42bc035e5436bc0fa6679655aef147de
