### ISSUE TITLE
invalid command ovs-metrics

### ISSUE THREAD

**Issue by mkfsn** [ovn-org/ovn-kubernetes#1609]
Hi, I followed the setup in the [README](https://github.com/ovn-org/ovn-kubernetes/blob/1f5e4c9/README.md) but the `ovnkube-node` pod keeps crashing.

It seems to me that the docker image is outdated (although it's `latest`) because I saw the following error in the `ovs-metrics-exporter` container:

```
================== ovnkube.sh --- version: 3 ================
 ==================== command: ovs-metrics
 =================== hostname: k8s-router-2
 =================== daemonset version 3
 =================== Image built from ovn-kubernetes ref: refs/heads/master  commit: 69f1ec54e62cf8c13ab06910593f704e44784b2a
invalid command ovs-metrics
valid v3 commands: ovs-server nb-ovsdb sb-ovsdb run-ovn-northd ovn-master  ovn-controller ovn-node display_env display ovn_debug cleanup-ovs-server  cleanup-ovn-node nb-ovsdb-raft sb-ovsdb-raft db-raft-metrics
```

but I also see the `ovs-metrics` in the master branch:

https://github.com/ovn-org/ovn-kubernetes/blob/master/dist/images/ovnkube.sh#L1024

Did I do something incorrectly?

**Comment by danwinship** [comment]
You should build your own ovnkube image... I'm not sure how often we update the "official" image, but it definitely doesn't track git master closely

**Comment by amorenoz** [comment]
I hit the same issue, maybe the REAMD.md could be updated to reflect that?

**Comment by xinghaipiaozhou** [comment]
> 
> 
> You should build your own ovnkube image... I'm not sure how often we update the "official" image, but it definitely doesn't track git master closely

how to  build my own ovnkube image?
