### ISSUE TITLE
network policy flakes

### ISSUE THREAD

**Issue by trozet** [ovn-org/ovn-kubernetes#1624]
See in this run there are a handful of flakes:
https://github.com/ovn-org/ovn-kubernetes/pull/1593/checks?check_run_id=999835669

[Fail] [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client [It] should enforce multiple egress policies with egress allow-all policy taking precedence [Feature:NetworkPolicy] 
/home/runner/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/network_policy.go:1522

[Fail] [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client [It] should stop enforcing policies after they are deleted [Feature:NetworkPolicy] 
/home/runner/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/network_policy.go:1522

Different network policy tests seem to randomly fail sometimes in our CI (upstream and downstream) we need to figure this out.

**Comment by trozet** [comment]
more here: https://github.com/ovn-org/ovn-kubernetes/pull/1620/checks?check_run_id=999949171

**Comment by vpickard** [comment]
cc @vpickard

**Comment by trozet** [comment]
We found the root cause of the failure for "should stop enforcing policies after they are deleted" test is due to allow-related acl changes. Reverting in this PR:
https://github.com/ovn-org/ovn-kubernetes/pull/1641
