### ISSUE TITLE
Missing CRD definitions

### ISSUE THREAD

**Issue by roytman** [ovn-org/ovn-kubernetes#1650]
Hi guys, 
I deployed ovn-kubernetes on my cluster according to the instructions from the [README.md](https://github.com/ovn-org/ovn-kubernetes/blob/master/README.md#run-daemonset-and-deployment) file.

All pods successfully started, but the CNI configuration files (10-ovn-kubernetes.conf) were not created. 
The `ovnkube-node` files contained a lot of messages like: 
> I0830 10:03:14.053295   19327 reflector.go:211] Listing and watching *v1.EgressIP from github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/egressip/v1/apis/informers/externalversions/factory.go:117
E0830 10:03:14.054768   19327 reflector.go:178] github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/egressip/v1/apis/informers/externalversions/factory.go:117: Failed to list *v1.EgressIP: the server could not find the requested resource (get egressi
ps.k8s.ovn.org)

The issue was resolved by deployment CRD definitions from `k8s.ovn.org_egressips.yaml` 

Should we add the CRD deployment instructions to the README.md file?

**Comment by danwinship** [comment]
> Should we add the CRD deployment instructions to the README.md file?

Probably, but I think we had decided that ovn-kubernetes is expected to work fine (ie, error-free) if you don't install the CRDs as long as you don't enable the features? @alexanderConstantinescu ?

**Comment by alexanderConstantinescu** [comment]
Sorry for that, I just double checked and it seems we do create the informer even if ovn-kubernetes has disabled egress IP. I will submit a PR with a fix for that.

**Comment by danwinship** [comment]
README fixed by #1651 and the warnings will be fixed by #1656
