### ISSUE TITLE
[failing test]NetworkPolicy between server and client should ensure an IP overlapping both IPBlock.CIDR and IPBlock.Except is allowed

### ISSUE THREAD

**Issue by aojea** [ovn-org/ovn-kubernetes#1663]
> [Fail] [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client [It] should ensure an IP overlapping both IPBlock.CIDR and IPBlock.Except is allowed [Feature:NetworkPolicy]
> 
> That test was specifically added to make ovn-kubernetes fail because our implementation of IPBlock.Except is incorrect (#845).

**Comment by danwinship** [comment]
Do we really need this separately from #845?

**Comment by aojea** [comment]
nope
