### ISSUE TITLE
[failing test] Conntrack should be able to preserve UDP traffic when server pod cycles for a NodePort service 

### ISSUE THREAD

**Issue by aojea** [ovn-org/ovn-kubernetes#1664]
[Fail] [sig-network] Conntrack [It] should be able to preserve UDP traffic when server pod cycles for a NodePort service 
/home/runner/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/conntrack.go:195

_Originally posted by @aojea in https://github.com/ovn-org/ovn-kubernetes/pull/1658#issuecomment-687222115_

**Comment by trozet** [comment]
resolved by https://github.com/ovn-org/ovn-kubernetes/pull/1889
