### ISSUE TITLE
fix unit test flakes

### ISSUE THREAD

**Issue by aojea** [ovn-org/ovn-kubernetes#1707]
We have several known flakes in the CI.

There are several reasons why a test can be flake, a good resource to learn more about golang testing and flakes can be found here 
- https://gist.github.com/liggitt
- https://youtu.be/Ewp8LNY_qTg

There are several tools we can use, one is to enable the race detector to warn us if we can have race conditions

https://github.com/ovn-org/ovn-kubernetes/pull/1640

The other is try to reproduce and deflake the test, as an example, a way of finding flakes in the hybrid controller will be:

1. compile the test as an static binary
```
cd ovn-kubernetes/go-controller
go test ./hybrid-overlay/pkg/controller/ -c -o test1
```

2. Download the golang tools, that include the `stress` utility

```
go get -u golang.org/x/tools/...
```

3. run the binary with it
```
stress sudo ./test1 -ginkgo.v
...
I0916 18:13:56.307158  217758 informer.go:139] Starting 1 pod
…
24 runs so far, 1 failures
37 runs so far, 1 failures
46 runs so far, 1 failures

/tmp/go-stress-20200916T181349-105282285
Running Suite: Hybrid Overlay Controller Suit
```

4. the binary has ginkgo embededd, if you want to focus on a certain test just do:
```
stress sudo ./test1 -ginkgo.v -ginkgo.focus="cleans up a Linux node when the OVN hostsubnet annotation is removed"
...
I0916 18:17:30.581856  222027 shared_informer.go:253] caches populated
I0916 18:17:30.581861  222027 informer.go:139] Starting 1 n
…
286 runs so far, 24 failures
```

**Comment by alexanderConstantinescu** [comment]
How about also re-instating the race detector for e2e test, like https://github.com/ovn-org/ovn-kubernetes/pull/1575 did? As a later step of course, I would imagine already having a stable build with unit tests running with the race detector on is step 1.
