### ISSUE TITLE
import ginkgo and gomega using PackageName

### ISSUE THREAD

**Issue by aojea** [ovn-org/ovn-kubernetes#1801]
Currently we are importing ginkgo and gomega using the ".",  i.e.

https://github.com/ovn-org/ovn-kubernetes/blob/4d3e5674e6977cc9ece447c77458d38c45747101/go-controller/pkg/config/config_test.go#L16-L17

that implies that all the package exported identifiers declared into 

> The PackageName is used in qualified identifiers to access exported identifiers of the package within the importing source file. It is declared in the file block. If the PackageName is omitted, it defaults to the identifier specified in the package clause of the imported package. If an explicit period (.) appears instead of a name, all the package's exported identifiers declared in that package's package block will be declared in the importing source file's file block and must be accessed without a qualifier.

Due to this is not possible to update ginkgo and gomega dependencies, because there are conflicts with the exported identifiers.

We must import ginkgo and gomega function using the package name, that means to replace in all *_test.go files to append the package name, and change the import to remove the "."

```

	ginkgo.Describe("OvnDBAuth operations", func() {
		var certFile, keyFile, caFile string

		ginkgo.BeforeEach(func() {
			var err error
			certFile, err = crea
```

xref: https://golang.org/ref/spec#Import_declarations

These are the files that need to be changed, no need to change all of them at same time, and multiple persons can work on them in parallel:

- [ ] hybrid-overlay/pkg/controller/controller_suite_test.go
- [ ] hybrid-overlay/pkg/controller/master_test.go
- [ ] hybrid-overlay/pkg/controller/node_linux_test.go
- [ ] pkg/node/node_suite_test.go
- [ ] pkg/node/gateway_init_linux_test.go
- [ ] pkg/node/gateway_localnet_linux_test.go
- [ ] pkg/node/node_test.go
- [ ] pkg/node/management-port_linux_test.go
- [ ] pkg/node/port_claim_test.go
- [ ] pkg/util/util_suite_test.go
- [ ] pkg/ovn/policy_test.go
- [ ] pkg/ovn/gateway_test.go
- [ ] pkg/ovn/endpoints_test.go
- [ ] pkg/ovn/service_test.go
- [ ] pkg/ovn/ovn_suite_test.go
- [ ] pkg/ovn/egressfirewall_test.go
- [ ] pkg/ovn/egressgw_test.go
- [ ] pkg/ovn/address_set_test.go
- [ ] pkg/ovn/logical_switch_manager_test.go
- [ ] pkg/ovn/pods_test.go
- [ ] pkg/ovn/master_test.go
- [ ] pkg/ovn/namespace_test.go
- [ ] pkg/ovn/egressip_test.go
- [ ] pkg/factory/factory_test.go
- [ ] pkg/cni/ovs_test.go
- [ ] pkg/cni/cni_suite_test.go
- [ ] pkg/informer/informer_test.go
- [ ] pkg/config/config_test.go

**Comment by aojea** [comment]
updated the info, @sheetalsingala @OmerBenHayun if you want to work on this please sync to not duplicate the effort.
One options is to submit one PR per folder, `pkg/ovn`, `pkg/cni`, ...

**Comment by sheetalsingala** [comment]
I will be working on `pkg/cni`, `pkg/config`, `pkg/informer`, `pkg/factory`, `hybrid-overlay` and `pkg/node`

**Comment by OmerBenHayun** [comment]
I did the rest: `pkg/ovn` and `pkg/util`.

**Comment by dcbw** [comment]
@aojea is it that Ginkgo and Gomega have clashing exports, or that OVN clashes with one or both of those?

**Comment by aojea** [comment]
> OVN clashes with one or both of those

this ^^, and due to that we can 't bump the ginkgo/gomega deps

**Comment by dcbw** [comment]
@aojea so... why don't we just change OVN? what bits clash? I'd rather fix OVN than do the naming prefix for the ginkgo/gomega stuff everywhere :(

**Comment by aojea** [comment]
having dot imports is risky, you never known if some of the imports will clash sooner or later
https://github.com/golang/go/issues/29326#issuecomment-516425395

TIL, it seems to be the pattern in ginkgo and gomega users based on the thread I linked.
I'm clearly in favour of removing the dot import and make it explicit to avoid risks, over readability, but is an opinion like any other ...
