### ISSUE TITLE
ovnkube master stuck when egress ip crd is not deployed

### ISSUE THREAD

**Issue by moshe010** [ovn-org/ovn-kubernetes#1848]
We the master code if you don't deploy the egress k8s.ovn.org_egressfirewalls.yaml and k8s.ovn.org_egressips.yaml
the master show the following error:
E1117 19:15:44.920327      52 reflector.go:178] pkg/crd/egressip/v1/apis/informers/externalversions/factory.go:117: Failed to list *v1.EgressIP: the server could not find the requested resource (get egressips.k8s.ovn.org)
E1117 19:15:44.920327      52 reflector.go:178] pkg/crd/egressip/v1/apis/informers/externalversions/factory.go:117: Failed to list *v1.EgressIP: the server could not find the requested resource (get egressips.k8s.ovn.org)
E1117 19:15:44.920327      52 reflector.go:178] pkg/crd/egressip/v1/apis/informers/externalversions/factory.go:117: Failed to list *v1.EgressIP: the server could not find the requested resource (get egressips.k8s.ovn.org)

and the ovnkube node is stuck waiting for the management port to be ready 
I1117 19:16:47.308278   27540 ovs.go:170] exec(693): stderr: ""
I1117 19:16:47.775704   27540 ovs.go:166] exec(694): /usr/bin/ovs-vsctl --timeout=15 --if-exists get interface ovn-k8s-mp0 ofport
I1117 19:16:47.792968   27540 ovs.go:169] exec(694): stdout: "3\n"
I1117 19:16:47.793012   27540 ovs.go:170] exec(694): stderr: ""
I1117 19:16:47.793037   27540 ovs.go:166] exec(695): /usr/bin/ovs-ofctl --no-stats --no-names dump-flows br-int table=65,out_port=3
I1117 19:16:47.807109   27540 ovs.go:169] exec(695): stdout: ""
I1117 19:16:47.807146   27540 ovs.go:170] exec(695): stderr: ""

**Comment by trozet** [comment]
@JacobTanenbaum will take this

**Comment by JacobTanenbaum** [comment]
the egressFirewall is fine whether or not the egressFirewall CRD is present, there was an issue with the `--enable-egress-ip` flag not working as intended. In order to deploy without egressIP you need to remove the CRD and deploy without ``--enable-egress-ip`
