### ISSUE TITLE
EgressDNS will need to resolve DNS names on the nodes 

### ISSUE THREAD

**Issue by JacobTanenbaum** [ovn-org/ovn-kubernetes#1880]
while writing e2e tests for https://github.com/ovn-org/ovn-kubernetes/pull/1597 in the CI the nodes always seemed to resolve the DNS names to different IP addresses then the master did, while locally on a kind cluster the DNS names resolve the same it is clear that for the proper functionality to occur nodes will need to resolve them as well

**Comment by aojea** [comment]
> while writing e2e tests for #1597 in the CI the nodes always seemed to resolve the DNS names to different IP addresses then the master did, while locally on a kind cluster the DNS names resolve the same it is clear that for the proper functionality to occur nodes will need to resolve them as well

can you elaborate on this?, is difficult to me to understand this sentence
>  CI the nodes always seemed to resolve the DNS names to different IP addresses then the master did

what are the CI nodes and the masters here?

**Comment by JacobTanenbaum** [comment]
currently the egressFirewall DNS name enhancement is written in such a way that the ovnkube-master pod  resolves the DNS name to ip addresses and builds the address_set off those IP addresses the assumption being that pods on worker nodes will resolve IPs to one in that set. That assumption held true locally in kind clusters but once the PR was uploaded and the automated testing ran the pod deployed by the e2e test resolved the DNS name differently then ovnkube-master so the rule was not followed

It looks like we will need a way for the ovnkube-node pods to also resolve the DNS name and report the results to master so that we can build the correct address_set for the cluster

**Comment by aojea** [comment]
the CI needs to patch CoreDNS to work in an offline environment (for IPv6)

https://github.com/ovn-org/ovn-kubernetes/blob/c9555e70e4d813b1abb9daba344ee8b55c3b2584/contrib/kind.sh#L287-L312
