### ISSUE TITLE
Failure to get ovnsb db size

### ISSUE THREAD

**Issue by vpickard** [ovn-org/ovn-kubernetes#1967]
I'm seeing this error log in my KIND setup, started with ../contrib/kind.sh (no options):

`I0120 15:47:05.939150      74 ovs.go:166] exec(466): /usr/bin/ovn-appctl -t /var/run/ovn/ovnsb_db.ctl --timeout=5 memory/show
I0120 15:47:05.943468      74 ovs.go:169] exec(466): stdout: "cells:12190 monitors:4 sessions:5\n"
I0120 15:47:05.943517      74 ovs.go:170] exec(466): stderr: ""
E0120 15:47:05.943551      74 ovn_db.go:258] Failed to get the DB size for database OVN_Southbound: stat /etc/ovn/ovnsb_db.db: no such file or directory`

I had a chat with @abhat. Aniket is saying the metrics checker does check for standalone but it does so only for metrics registration, it should do so also for the updaters.

**Comment by tssurya** [comment]
Stale issue, closing.
