### ISSUE TITLE
OVN-Kubernetes releases

### ISSUE THREAD

**Issue by aojea** [ovn-org/ovn-kubernetes#1994]
Following up on the discussion in #1956, I think that we should do OVN-kubernetes releases, preferably associated to the kubernetes release version, just tagging 

> branching can be expensive to maintain at this stage and for this type of project, I will happy just with tagging and and doing a "kind" of release explaining the ovn/ovs/kubernetes versions that weren't tested at that time, so we can have a temporal reference

> ovn-kube 20.12 tag , was released with ovn 20.12, ovs 2.2, kubernetes 1.20

> I was wondering if we should pin the ovs/ovn versions and bumping them manually , so we can identify possible regressions/incompatibilites between ovn-kube and ovn

I think it is a fine idea and in the same line of thoughts we should at some point think wrt. stable branch that will be pinned to an older version of ovs/ovn, perhaps naming it after ovn, like ovn-kubernetes-20.12 etc. I think @dcbw brought this up to one of community meetings  but we've never concluded on it.

_Originally posted by @dyusupov in https://github.com/ovn-org/ovn-kubernetes/issues/1956#issuecomment-768626287_

**Comment by aojea** [comment]
ping @dcbw @girishmg @trozet @dyusupov

**Comment by dyusupov** [comment]
unfortunately there is no other way of gaining stability other than yes, branching... but the cost can be somewhat amortized with the right tooling e.g. CICD and policies. I would say that since ovn-kubernetes is effectively an umbrella for ovn, ovs and kubernetes, we need to support a version matrix of dependences for any given stable release

**Comment by aojea** [comment]
I don´t think that branching will work for something that consumes Kubernetes, it is too fast pace ...  in 2 years you´ll have 6 stable branches and you´ll get lost in backports, cis, deprecations .... we don´t have branching in KIND and we support a lot of Kubernetes versions, the key is to have your latest release stable and not break anything between releases.... users must use last stable

Adding a tag doesn´t change anything from what we have now, is just adding a bookmark at certain point in time without any contract, but we show clear what we had at that point

**Comment by dyusupov** [comment]
I think KIND is not a good example as it is not something that people run for months and years or define upgrade paths. On a contrary, we used branching very successfully with Rook project.. infrastructure is something that would need that sort of level of stability on a long run and networking is even bigger part of it than storage. But I do agree that tagging is next step towards it

**Comment by aojea** [comment]
> I think KIND is not a good example as it is not something that people run for months and years or define upgrade paths. On a contrary, we used branching very successfully with Rook project.. . But I do agree that tagging is next step towards it

yeah, please forgive me, I think I´ve should added more context to my words, I didn´t want to enter in a release model discussion, your points are totally right.
I´ve tried to mean that at this stage and with the current rate of changes, features, ... I don´t feel we need branching right now and it is going to slow down due to its overhead

**Comment by alexandrevicenzi** [comment]
Are there any plans to create tags or releases? The last one is from 2018.

Tags and/or releases would help package maintainers to actually track any changes in the project and update their distribution accordingly.

I ask because we maintain a package called ovnkube in openSUSE, and it's currently outdated due the lack of releases.
