### ISSUE TITLE
Pin ovs/ovn version on Dockerfile.fedora

### ISSUE THREAD

**Issue by aojea** [ovn-org/ovn-kubernetes#1995]
Dockerfile.Fedora just downloads whatever is published in the corresponding Fedora repo at that point in time. This causes that we never know when we had a version bump in ovs or ovn, and if this affected or not ovn-kuberntes, and this has consequences, mainly in the CI.

Right now we can have the impression that the CI is more or less flaky, but a git-bisect is useless if the flakiness was introduced by ovs/ovn, if we explicitly add a commit bumping the versions we can solve this problem.

I really think that we should do this 

> I was wondering if we should pin the ovs/ovn versions and bumping them manually , so we can identify possible regressions/incompatibilites between ovn-kube and ovn

_Originally posted by @aojea in https://github.com/ovn-org/ovn-kubernetes/issues/1956#issuecomment-768613024_

**Comment by dyusupov** [comment]
re #1994. To clarify, you suggesting to build ovn/ovs (docker multi-stage builds here) and deliver it as a part of Dockerfile.fedora (and maybe all others that we want to support), correct?

**Comment by aojea** [comment]
I wasn´t entering into the implementation details, I just want that we have a commit of when the ovs/ovn has changed, so we can trace problems and to know which ovs/ovn versions we were using for testing from commitA to commit B

Said this, I think that we should start small , just a `dnf install ovn-20.12.0-5.fc34` should be enough ... docker multi-stage builds require a great effort to maintain, it is better to offload that work to the ovn team and consume their packages

**Comment by aojea** [comment]
Today all PRs are failing, even the ones without any code change related
https://github.com/ovn-org/ovn-kubernetes/runs/1951632949?check_suite_focus=true

however, last PR merged went through completely green
https://github.com/ovn-org/ovn-kubernetes/actions/runs/582978864

Assuming CI failures are not related to OVN-Kube I was looking for the external dependencies and I could observer that the ovn version is different, the failing ones have OVN version:
```
   Verifying        : openvswitch-2.14.0-2.fc33.x86_64                     19/71 
  Verifying        : ovn-20.12.0-17.fc33.x86_64                           20/71 
  Verifying        : ovn-central-20.12.0-17.fc33.x86_64                   21/71 
  Verifying        : ovn-host-20.12.0-17.fc33.x86_64      
```
the last PR merged:

```
   ovn                         x86_64    20.12.0-5.fc33          updates    1.0 M
 ovn-central                 x86_64    20.12.0-5.fc33          updates    423 k
 ovn-host                    x86_64    20.12.0-5.fc33          updates    667 k
```

I can't confirm this is the cause yet, but looks suspicious

**Comment by aojea** [comment]
Fixed by https://github.com/ovn-org/ovn-kubernetes/pull/2078
