### ISSUE TITLE
external host ping pod not working, pod ping external host is work

### ISSUE THREAD

**Issue by chestarss** [ovn-org/ovn-kubernetes#2019]
1、pod ip  ping external ip ok
2、external ip ping pod id not work

tcpdump  in node which pod belong to.

**Comment by chestarss** [comment]
![image](https://user-images.githubusercontent.com/11288347/107334545-d057a700-6af1-11eb-907a-d7ab3fcf3393.png)

**Comment by chestarss** [comment]
![image](https://user-images.githubusercontent.com/11288347/107335074-773c4300-6af2-11eb-880f-6cfdd356080a.png)

**Comment by tssurya** [comment]
> 1、pod ip ping external ip ok 2、external ip ping pod id not work
> 
> tcpdump in node which pod belong to.

but external clients cannot access pods directly unless they are exposed using services. Closing this issue as its stale. Please reopen if you don't agree
