### ISSUE TITLE
Service Reject ACL does not work after adding/removing endpoints

### ISSUE THREAD

**Issue by trozet** [ovn-org/ovn-kubernetes#2045]
Initial service create will add a reject ACL and not add the VIP to the load balancer. Allowing service reject to work correctly. However, adding endpoints, and then removing endpoints will leave the VIP in the load balancer. This causes OVN to send the empty-lb-event instead of letting the packet hit the reject ACL in the pipeline.

The solution to this is to detect if the endpoints have been idled or not when deciding whether to leave the VIP on the load balancer or not.

This will be resolved when we move to reject on load balancers instead of via ACLs.

**Comment by tssurya** [comment]
We are using reject via load balancers and not ACLs for services. Closing issue as its fixed.
