### ISSUE TITLE
New E2E test: delete/re-add node, verify existing containers have connectivity

### ISSUE THREAD

**Issue by trozet** [ovn-org/ovn-kubernetes#2282]
With the fix for #2281 for bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1973286 we need a test case added to control plane tests to ensure this doesn't break again. The basic gist is this:

1. node has pods on it
2. node is deleted
3. node is added back in very quick succession
4. the grace period hasn't passed for pods to have been evicted from the node, so the containers stay put
5. ensure that the pods have network connectivity again

**Comment by trozet** [comment]
@kedark3 FYI in case you are interested

**Comment by kedark3** [comment]
@trozet I will definitely take a stab at it. Thanks!!

**Comment by kedark3** [comment]
Hi @trozet I tried to run this through a simple kind cluster, just by deleting and recreating worker node, and as soon as I do that, the coredns pods loses connectivity, and it only regains connectivity when I delete the pod and recreate it. While other pods keep running, see below:

![image](https://user-images.githubusercontent.com/8180469/132065307-2109d217-6d9a-4842-b3c8-af88fcc9bf94.png)


And here's how the coredns pods complain: 
![image](https://user-images.githubusercontent.com/8180469/132065341-064c308e-ecc2-4529-b840-dee07f77bc23.png)

Am I doing that right? Are we expecting this to be broken for now?  I see you merged https://github.com/ovn-org/ovn-kubernetes/pull/2281 , how did you test it?

Please advise.
