### ISSUE TITLE
Create Design Documentation for OVN-Kubernetes Multicast Feature 

### ISSUE THREAD

**Issue by astoycos** [ovn-org/ovn-kubernetes#2288]
There is no document explaining how multicast works in OVN-Kubernetes.  It would be really good to have a document similar to the [one made for Network Policy](https://github.com/ovn-org/ovn-kubernetes/blob/master/docs/network-policy.md) Explaining what OVN resources are created when Multicast Is enabled. 

This is a good first issue for newcomers as a kind cluster can be brought up analyze how multicast should work, giving the user some experience poking around the OVN objects used under OVN-K

**Comment by astoycos** [comment]
@maiqueb this Is a good first issue :)

**Comment by maiqueb** [comment]
Sure, I'll take it.

/assign

**Comment by maiqueb** [comment]
Seems I cannot assign this to myself. I think I'll have to join the ovn-org somehow for it to be possible.

Is that something you can help me with @astoycos ?
