### ISSUE TITLE
ipv4/ipv6 dual stack support production ready?

### ISSUE THREAD

**Issue by rprakashg** [ovn-org/ovn-kubernetes#2461]
Given ipv4/ipv6 dual stack support is in beta in kubernetes, is anyone using this in production kubernetes clusters today?
Anyone tested this within VMWare or even clusters running on AWS/GCP/Azure ?

**Comment by wangshuai199398** [comment]
I want to know too，do you know now ipv4/ipv6 dual stack is support？
