### ISSUE TITLE
Unit testing: Add more coverage for ovn-dbchecker

### ISSUE THREAD

**Issue by trozet** [ovn-org/ovn-kubernetes#2576]
As I was working on #2554 I noticed we have unit tests for the election timer check, but no other checks. It would be nice if someone can add testing for each of the other checks: ensureClusterRaftMembership, ensureLocalRaftServerID, as well as testing if the db would get reset. Can leverage the changes I'm making in to have the checks return an error.

**Comment by andreaskaris** [comment]
@trozet  @jluhrsen I'll take this one
