### ISSUE TITLE
Run ovnk e2e tests on upgrade jobs

### ISSUE THREAD

**Issue by trozet** [ovn-org/ovn-kubernetes#2641]
We missed a bug where unidling was broken on upgrade:
https://github.com/ovn-org/ovn-kubernetes/pull/2638

I'm not sure if we would have caught this by simply running the e2e tests after upgrade or if it would have required configuring unidling before the upgrade, upgrading, then testing to see if it still worked. Either way we need some types of tests like this where we configure some functionality before an upgrade, then upgrade and check that it still works appropriately.

**Comment by andreaskaris** [comment]
@trozet I am pretty sure that I misunderstand your request, because this here looks a bit too trivial? https://github.com/ovn-org/ovn-kubernetes/pull/2644/commits/b96b5f8fa427b9d01b70f93c1d221f4680d9d70e
