### ISSUE TITLE
CI: control-plane tests are timing out

### ISSUE THREAD

**Issue by tssurya** [ovn-org/ovn-kubernetes#2678]
Examples:

https://github.com/ovn-org/ovn-kubernetes/runs/4278125594?check_suite_focus=true#step:10:6350
https://github.com/ovn-org/ovn-kubernetes/runs/4233431908?check_suite_focus=true#step:10:3904
https://github.com/ovn-org/ovn-kubernetes/runs/4235721029?check_suite_focus=true#step:10:1848

Someone needs to look into why this is happening, my initial thoughts were that the time wasn't enough, but as @alexanderConstantinescu  pointed out in https://github.com/ovn-org/ovn-kubernetes/pull/2660 that need not be the case and maybe some e2e's are being done in an inefficient way.

**Comment by jluhrsen** [comment]
This is something I'd like to take a shot at, but I would't be able to start taking a look at it for a week or so as we roll in to my next work sprint. if that's ok, let me know and I'll create the jira stuff to help me track it. Otherwise someone else can work on this if they have cycles now.

**Comment by tssurya** [comment]
@jluhrsen : that's totally fine, thanks for volunteering. It's not super urgent. It can wait till next week. 
/assign @jluhrsen

**Comment by jluhrsen** [comment]
@tssurya, I wanted to see if there is something I can figure out here, but I just went through every failed 'ovn-ci' for the past 7 days and did not see any that timed out. Wondering if this might not be happening any more?

**Comment by tssurya** [comment]
maybe its not, after the recent k8 rebases we always bump up the time for all runs since the number of tests added also increase. Closing this since it doesn't seem to be an issue anymore.
