### ISSUE TITLE
”kubeconfig.yaml" not found

### ISSUE THREAD

**Issue by SoftTissues** [ovn-org/ovn-kubernetes#2685]
Hello guys，

I'm a tiro in ovn-kubernetes.When I try to start the start ovnkube utility on the master. The log show me that I am missing the "kubeconfig.yaml" file.I saw this issue once appeared here, but the connection under that issue is unavailable.
What should I do to get this "kubeconfig.yaml".

### log:
```
I1130 22:44:07.097542   18165 ovs.go:95] Maximum command line arguments set to: 191102
F1130 22:44:07.120098   18165 ovnkube.go:132] kubernetes kubeconfig file "kubeconfig.yaml" not found
```

**Comment by dougsland** [comment]
@SoftTissues this report is still valid? How have you setup your env ? 
/cc @flavio-fernandes
