### ISSUE TITLE
EgressIP Test "should not do anyting for user defined status updates" is broken

### ISSUE THREAD

**Issue by tssurya** [ovn-org/ovn-kubernetes#3028]
spoke to @kyrtapz  and @flavio-fernandes already, this is regarding: https://github.com/ovn-org/ovn-kubernetes/pull/3008#issuecomment-1149537762
We think this never worked properly OR we regressed :)

**Comment by trozet** [comment]
@alexanderConstantinescu FYI

**Comment by tssurya** [comment]
fixed via https://github.com/ovn-org/ovn-kubernetes/pull/3035
