### ISSUE TITLE
kind : Not able to create a setup when NET_CIDR_IPV4 is set to IP/16/19

### ISSUE THREAD

**Issue by numansiddique** [ovn-org/ovn-kubernetes#3072]
kind.sh fails if 

#export NET_CIDR_IPV4="10.244.0.0/16/19"
#./kind.sh

+ kind create cluster --name ovn --kubeconfig /root/ovn.conf --image kindest/node:v1.24.0 --config=/home/nusiddiq/go/src/github.com/ovn-org/ovn-kubernetes/contrib/kind-ovn.yaml --retain
enabling experimental podman provider
ERROR: failed to create cluster: invalid pod subnet failed to parse cidr value:"10.244.0.0/16/19" with error: invalid CIDR address: 10.244.0.0/16/19

**Comment by dougsland** [comment]
@numansiddique it seems invalid CIDR. If you try `10.244.0.0/16` or `10.244.0.0/19` should do the trick.
/cc  @jcaamano 

I would close this one.

**Comment by jcaamano** [comment]
@numansiddique what notation is that and how should we be supporting it?
