### ISSUE TITLE
Endpoint slices commit causing failures in OpenShift

### ISSUE THREAD

**Issue by trozet** [ovn-org/ovn-kubernetes#3116]
Tried pulling in a few commits downstream, and most of the jobs consistently fail:
https://github.com/openshift/ovn-kubernetes/pull/1237

The two main commits there were @npinaeva sync map implementation and @Pardhakeswar endpoint slices change. I then opened 2 more PRs, one without sync map:
https://github.com/openshift/ovn-kubernetes/pull/1245

^ fails most jobs

one without endpoint slices:
https://github.com/openshift/ovn-kubernetes/pull/1244
^passes most jobs on first try

This leads me to believe there is some regression with:
https://github.com/openshift/ovn-kubernetes/pull/1244/commits/1a225eaed53ab35e33efcb3f73a6092553398449

A common failure is:
```
Post "https://thanos-querier-openshift-monitoring.apps.ci-op-w5rmtciv-834bf.origin-ci-int-aws.dev.rhcloud.com/api/v1/query_range": net/http: TLS handshake timeout
```

Maybe this is trying to connect to some k8s service to get metrics. Either way we need a fast fix or need to revert this change. @girishmg FYI

@ricky-rav could you please investigate this?

**Comment by ricky-rav** [comment]
I see that you've included my follow-up PR on endpoint slices, thanks @trozet!

We now have:
- https://github.com/openshift/ovn-kubernetes/pull/1246 (reverting both endpointslice PRs)
- https://github.com/openshift/ovn-kubernetes/pull/1237 (including both endpointslice PRs)

Comparing failures in those two PRs, I see that both PRs now fail two required jobs, with one overlap:
- 1246 fails `ci/prow/e2e-aws-ovn-upgrade-local-gateway` (3 failed tests, 29 flakes) and `ci/prow/4.12-upgrade-from-stable-4.11-e2e-aws-ovn-upgrade`  (12 failed tests, 23 flakes) 
- 1237 fails `ci/prow/e2e-aws-ovn-upgrade-local-gateway` (4 failed tests, 29 flakes)  and ` ci/prow/e2e-aws-ovn-upgrade` (4 failed tests, 36 flakes) 

In `ci/prow/e2e-aws-ovn-upgrade-local-gateway`, two failed tests are the same in both PRs.

I'm running again required jobs to see if failures are persistent.

**Comment by ricky-rav** [comment]
All required jobs succeeded this time on 1237.

**Comment by ricky-rav** [comment]
Same for 1246. @trozet I think we're ready to merge the endpointslice commits.

**Comment by trozet** [comment]
yeah looks like your fix resovled the problem. Thanks!

**Comment by trozet** [comment]
OpenShift is seeing a regression with outage timers for OpenShift routes (leverages services) over 1m20 seconds during upgrade. Reverting the endpoint slices has fixed the issue:
https://github.com/openshift/ovn-kubernetes/pull/1248

https://issues.redhat.com/browse/TRT-468

Problem:
```
{  fail [github.com/openshift/origin/test/extended/util/disruption/backend_sampler_tester.go:184]: Aug 16 15:43:31.348: ns/openshift-authentication route/oauth-openshift disruption/ingress-to-oauth-server connection/new was unreachable during disruption: (no exact match for historicaldata.DataKey{Name:"ingress-to-oauth-server-new-connections", JobType:platformidentification.JobType{Release:"4.12", FromRelease:"4.11", Platform:"aws", Architecture:"amd64", Network:"ovn", Topology:"ha"}}, fell back to historicaldata.DataKey{Name:"ingress-to-oauth-server-new-connections", JobType:platformidentification.JobType{Release:"4.11", FromRelease:"4.10", Platform:"aws", Architecture:"amd64", Network:"ovn", Topology:"ha"}}) for at least 1m35s of 1h15m30s (maxAllowed=1m20s):

Aug 16 14:28:01.190 - 1808s I ns/openshift-authentication route/oauth-openshift disruption/ingress-to-oauth-server connection/new ns/openshift-authentication route/oauth-openshift disruption/ingress-to-oauth-server connection/new started responding to GET requests over new connections
Aug 16 14:58:09.190 - 1s    E ns/openshift-authentication route/oauth-openshift disruption/ingress-to-oauth-server connection/new reason/DisruptionBegan ns/openshift-authentication route/oauth-openshift disruption/ingress-to-oauth-server connection/new stopped responding to GET requests over new connections: Get "https://oauth-openshift.apps.ci-op-hl48ngi3-d5c74.aws-2.ci.openshift.org/healthz": net/http: TLS handshake timeout
```

Due to this regression we may need to revert in upstream until we figure out the fix.
