### ISSUE TITLE
Endpoints are not updated if new GW has been added

### ISSUE THREAD

**Issue by tong101** [ovn-org/ovn-kubernetes#316]
When adding endpoints, ovnkube collects current available GWs to create load balancer VIP. However, if new GW has been added after endpoints has been created. The VIP will not be updated. We should watch the adding/deleting GW event and update VIP accordingly.

**Comment by rajatchopra** [comment]
Is this for NodePort?

**Comment by tong101** [comment]
Yes

**Comment by winsopc** [comment]
The issue still exist with latest code base. I will submit a fix for reviewing this week.
