### ISSUE TITLE
EgressIPPod can't be deleted after namespace was deleted: infinte retry

### ISSUE THREAD

**Issue by npinaeva** [ovn-org/ovn-kubernetes#3223]
If a namespace delete event was received before egressIPPod delete event, pod won't ever be deleted.

```
I1012 15:36:08.506796      61 obj_retry.go:1443] Delete event received for *v1.Namespace netpol-2754-x
I1012 15:36:08.545473      61 obj_retry.go:1443] Delete event received for *factory.egressIPPod netpol-2754-x/c
E1012 15:36:08.545484      61 obj_retry.go:1456] Failed to delete *factory.egressIPPod netpol-2754-x/c, error: namespace "netpol-2754-x" not found
```

then you will see infinite retries
```
I1012 15:36:29.947335      61 obj_retry.go:1093] Going to retry *factory.egressIPPod resource setup for 1 number of resources: [netpol-2754-x/c]
```

Probably this function https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/ovn/egressip.go#L454 should be able to delete egress ip pod even if namespace is already deleted.

**Comment by tssurya** [comment]
are we really seeing infinite retries? We should stop after 15 attempts.
```
const maxFailedAttempts = 15 // same value used for the services level-driven controller

```

**Comment by tssurya** [comment]
Original bug which is there for all the controllers using shared resources should be fixed for this case.. I have a feeling the namespace deletion would probably tear down the setup for the pod since I'd expect a pod update event, need to verify.. in which case its a matter to deciding if retry needs to be done or not.

**Comment by npinaeva** [comment]
yeah by infinite I mean doesn't have a chance to succeed.
delete events for namespace and pod are not synchronized in any way, and in case pod event arrives later, resources for egress ip won't be cleaned up.
What is the original bug for all controllers, I don't see how this problem is common for al of them?

**Comment by tssurya** [comment]
example endpointslices and services, there is no guarantee of order - we do a cache in gateway code to counter this, namespace and pod has also been an existing problem example in network policy controller as well where we had a hack.

**Comment by npinaeva** [comment]
right, so we may need one more hack for egress ips, since it has similar problem, like store required namespace info internally to be able to cleanup
