### ISSUE TITLE
udp unreachable for service backed by host endpoint on the same node

### ISSUE THREAD

**Issue by zshi-redhat** [ovn-org/ovn-kubernetes#3340]
Run netcat udp tests for the following traffic:

regular pod (netcat client)  ->  clusterIP service -> single host endpoint on the same node (netcat server)

tcpdump on the regular pod OVS interface and found that:
The first udp packet is sent successfully to the host endpoint and received by the netcat server
The second udp packet is sent to the host endpoint, but not received by the netcat server, icmp udp unreachable message is received on the pod interface.

Example of tcpdump :
```
# tcpdump -i d51fb4adea94639 -nneepv 

08:41:51.537256 0a:58:0a:f4:01:07 > 0a:58:0a:f4:01:01, ethertype IPv4 (0x0800), length 46: (tos 0x0, ttl 64, id 1585, offset 0, flags [DF], proto UDP (17), length 32)
    10.244.1.7.35801 > 10.96.220.212.5201: UDP, length 4

08:41:55.457962 0a:58:0a:f4:01:07 > 0a:58:0a:f4:01:01, ethertype IPv4 (0x0800), length 46: (tos 0x0, ttl 64, id 1586, offset 0, flags [DF], proto UDP (17), length 32)
    10.244.1.7.35801 > 10.96.220.212.5201: UDP, length 4

08:41:55.460867 de:02:f7:db:80:d7 > 0a:58:0a:f4:01:07, ethertype IPv4 (0x0800), length 74: (tos 0xc0, ttl 64, id 11477, offset 0, flags [none], proto ICMP (1), length 60)
    10.96.220.212 > 10.244.1.7: ICMP 10.96.220.212 udp port 5201 unreachable, length 40
	(tos 0x0, ttl 63, id 1586, offset 0, flags [DF], proto UDP (17), length 32)
    10.244.1.7.35801 > 10.96.220.212.5201: UDP, length 4
```

`d51fb4adea94639` is the regular pod veth interface.
`10.244.1.7` is IP of regular pod.
`10.96.220.212` is cluster ip service

ovn-kubernetes master commit:
18fbc0187eeeaa5723e25e5e4ce6a692c10c806b

ovn/ovs versions:
ovn-22.12.0-0.fc36.x86_64
ovn-central-22.12.0-0.fc36.x86_64
ovn-host-22.12.0-0.fc36.x86_64
ovn-vtep-22.12.0-0.fc36.x86_64
openvswitch-2.17.0-3.fc36.x86_64

**Comment by wizhaoredhat** [comment]
This problem occurs for:
Regular Pod -> NodePort Service traffic (Host Backend pod - Same Node)
Regular Pod -> Cluster IP Service traffic (Host Backend pod - Same Node)
Iperf3 can be used to reproduce this as well.
