### ISSUE TITLE
IPv6 setup pod error.

### ISSUE THREAD

**Issue by wangshuai199398** [ovn-org/ovn-kubernetes#3357]
Hello everyone.
I use ipv6 to deploy ovn-kubernetes，coredns and service pod setup error.
command：
kubectl describe pod coredns-6d8c4cb4d-wqdvh -n kube-system
error:
ormal   SandboxChanged          15m (x2937 over 70m)  kubelet  Pod sandbox changed, it will be killed and re-created.
  Warning  FailedCreatePodSandBox  2s (x3739 over 69m)   kubelet  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "53503b62ae0a0bedb6f31d1727818a990e8deb64ea46fc326961f04dd612fe53" network for pod "coredns-6d8c4cb4d-wqdvh": networkPlugin cni failed to set up pod "coredns-6d8c4cb4d-wqdvh_kube-system" network: CNI request failed with status 400: '[kube-system/coredns-6d8c4cb4d-wqdvh 53503b62ae0a0bedb6f31d1727818a990e8deb64ea46fc326961f04dd612fe53] [kube-system/coredns-6d8c4cb4d-wqdvh 53503b62ae0a0bedb6f31d1727818a990e8deb64ea46fc326961f04dd612fe53] failed to configure pod interface: failed to add IP addr 2000:1024:0:1::4/64 to eth0: permission denied
who know why?

**Comment by zhangjing57** [comment]
I have the same problem.Does anyone else have an opinion?
