### ISSUE TITLE
OVN DB endpoints are deleted when kube-controller container recreated

### ISSUE THREAD

**Issue by DmytroLinkin** [ovn-org/ovn-kubernetes#3385]
**Setup**:
Host: VM with Centos8.5
Kubernetes: client 1.23.1, server 1.23.16
ovn-kubernetes: downstream branch half year behind the master branch

**Use case**:
During deployment of ovnk8s downloading & extracting images on control plane node consumes ~100% of CPUs if host is weak (VM for ex.). This cause kube-controller (and kube-scheduler) liveness probe to fail - it can't connect to `https://127.0.0.1:10257/healthz` and triggers recreation of the container. When kube-controller is up and ready, it removes DB endpoints (why?) if ovnkube-db pod managed to create them by this time.

kube-controller deletes not only DB endpoints, but other created manually as well. Besides of the use case above same result can be reproduced if create custom service with endpoints and then do one of: manually stop kube-controller container, or insert iptable rule to reject (not drop) connection to `https://127.0.0.1:10257/healthz`, or simultaneously download big images. Probably the same issue may happen after host reboot if kubernetes will see newer images and start download them.

**Ideas**:
Because DB service created as headless kubernetes doesn't create endpoints dynamically, hence they must be created manually (done by ovnkube.sh during DB containers start up). I assume that kube-controller remove stale endpoints, which for ex. may had been left after removed pod, but manual endpoint creation doesn't provide enough information about it so it is also considered as stale and removed. 

What was the reason behind defining DB service as headless?
I see that `Endpoints` is kind of a legacy and there is `EndpointSlices` resource doing basically the same but also allow to specify service name this slices are associated to, like:

```
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: my-service-a
  namespace: my-namespace
  labels:
    kubernetes.io/service-name: my-service
```

I tried to reproduce issue using slices instead of endpoints for custom service and slices hadn't been removed, so it seems to work.

**Comment by girishmg** [comment]
I am really surprised that kube-controller is trying to delete endpoints of a K8s Headless Service. The endpoint IPs for an headless service is not managed by kube-controller, so one would expect that it shouldn't muck around with it.

**Comment by DmytroLinkin** [comment]
https://github.com/kubernetes/kubernetes/issues/115801
