### ISSUE TITLE
docker run can change to ctr run?

### ISSUE THREAD

**Issue by wangshuai199398** [ovn-org/ovn-kubernetes#3483]
now run-ovn-dpu.sh and run-ovnkube-node-dpu.sh setup container user ”docker run“，can change to ctr run?

**Comment by tssurya** [comment]
@wangshuai199398 : what are your reasons behind the request?
I don't see why not as long as it doesn't break the existing use cases and tests
probably someone from the dpu experts can chime in here to see if there is a strict reason for using docker.

**Comment by DmytroLinkin** [comment]
I also would like to hear more about use case.

AFAIK, BlueField is the only DPU where ovnk8s is deployed and it have docker installed. Also from `ctr --help`
```
...
DESCRIPTION:

ctr is an unsupported debug and administrative client for interacting
with the containerd daemon. Because it is unsupported, the commands,
options, and operations are not guaranteed to be backward compatible or
stable from release to release of the containerd project.
...
```
So I'm not sure why this tool presented on the BlueField.
