### ISSUE TITLE
ovnkube-node failed to start: "Waiting for ovs_ready to come up"

### ISSUE THREAD

**Issue by cyclinder** [ovn-org/ovn-kubernetes#3493]
Hi, teams! I try to install `ovn-kubernets` on my local by following [the install doc](https://github.com/ovn-org/ovn-kubernetes), But `ovnkube-node` failed to start, Always complaining:

```
[root@node1 x86_64]# kubectl get  po -n ovn-kubernetes -o wide
NAME                              READY   STATUS    RESTARTS          AGE   IP             NODE    NOMINATED NODE   READINESS GATES
ovnkube-db-7474bbdbc5-8nd66       2/2     Running   0                 21h   10.6.168.131   node1   <none>           <none>
ovnkube-master-546b54cb97-7dxnj   2/2     Running   154 (3m13s ago)   20h   10.6.168.131   node1   <none>           <none>
ovnkube-node-dxcmx                1/3     Running   462 (4m10s ago)   20h   10.6.168.132   node2   <none>           <none>
ovnkube-node-q8l87                1/3     Running   6 (4m53s ago)     18m   10.6.168.131   node1   <none>           <none>
[root@node1 x86_64]# kubectl logs -f -n ovn-kubernetes ovnkube-node-q8l87
Defaulted container "ovnkube-node" out of: ovnkube-node, ovn-controller, ovs-metrics-exporter
================== ovnkube.sh --- version: 3 ================
 ==================== command: ovn-node
 =================== hostname: node1
 =================== daemonset version 3
 =================== Image built from ovn-kubernetes ref: 43da7b1  commit: 43da7b1a7c62ba78fffa14965a4bee552d24dc11
=============== ovn-node - (wait for ovs)
info: Waiting for ovs_ready to come up, waiting 1s ...
info: Waiting for ovs_ready to come up, waiting 5s ...
info: Waiting for ovs_ready to come up, waiting 5s ...
info: Waiting for ovs_ready to come up, waiting 5s ...
```

What's happening here？ Can anyone help me? Thanks

Kernel Version:

```
[root@node1 x86_64]# uname -a
Linux node1 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

modInfo:

```
[root@node1 x86_64]# modinfo openvswitch
filename:       /lib/modules/3.10.0-957.27.2.el7.x86_64/kernel/net/openvswitch/openvswitch.ko.xz
alias:          net-pf-16-proto-16-family-ovs_packet
alias:          net-pf-16-proto-16-family-ovs_flow
alias:          net-pf-16-proto-16-family-ovs_vport
alias:          net-pf-16-proto-16-family-ovs_datapath
license:        GPL
description:    Open vSwitch switching datapath
retpoline:      Y
rhelversion:    7.6
srcversion:     5F31AD399652124B5C06AB4
depends:        nf_conntrack,nf_nat,libcrc32c,nf_nat_ipv6,nf_nat_ipv4,nf_defrag_ipv6
intree:         Y
vermagic:       3.10.0-957.27.2.el7.x86_64 SMP mod_unload modversions
signer:         CentOS Linux kernel signing key
sig_key:        52:0A:4E:2D:9D:55:3E:F8:42:01:C1:88:B8:7F:E5:1B:9D:E1:1A:5E
sig_hashalgo:   sha256
[root@node1 yaml]# rpm -qa | grep openvswitch-2.5.8-1.x86_64
openvswitch-2.5.8-1.x86_64
```

**Comment by DmytroLinkin** [comment]
About wait message:
Under the hood ovnkube-node checks for `ovsdb-server.pid` and `ovs-vswitchd.pid` files at `/var/run/openvswitch`. You may check what is there.

About versions:
OVS version looks to old. Unfortunately OVNK8s doesn't specify exact minimal version of OVS, however it is said `kernel >= 4.6`, so OVS version somewhat around it. More effective will be installing latest OVS as README suggests. If it doesn't install/work for some reason, try to install ~2.17.

**Comment by cyclinder** [comment]
Thanks for the help! @DmytroLinkin 



> About wait message: Under the hood ovnkube-node checks for `ovsdb-server.pid` and `ovs-vswitchd.pid` files at `/var/run/openvswitch`. You may check what is there.
> 
Yes, I checked it and don't found `ovsdb-server.pid` and `ovs-vswitchd.pid` in `/var/run/openvswitch`. 

At first, I compiled the package manually but it failed, so I installed the current version , I'm wondering if there is a compatibility issue between the ovs and kernel versions?

**Comment by DmytroLinkin** [comment]
Compilation fails due to the missing symbols in headers, right? I would recommend to switch kernel.

**Comment by cyclinder** [comment]
Is there a compatibility matrix here for the ovs version and the kernel version or something? 

When I installed `ovn-node.yaml`, it works :)

**Comment by DmytroLinkin** [comment]
> Is there a compatibility matrix here for the ovs version and the kernel version or something?

Have no idea.
 
> When I installed `ovn-node.yaml`, it works :)

Not following, `ovnkube-node.yaml`? The same, You had deployed initially?
