### ISSUE TITLE
Default deployment uses old container image from hub.docker.com

### ISSUE THREAD

**Issue by s1061123** [ovn-org/ovn-kubernetes#3541]
Hi,

As far as I looked 'dist/templates' manifest template, default uses image, docker.io/ovnkube/ovn-daemonset:latest, however, this image was updated at 2019 and never updated. As far as I looked repo, now latest images in [ghcr.io/ovn-org/ovn-kubernetes](https://github.com/orgs/ovn-org/packages?repo_name=ovn-kubernetes).

Is there any reason why ghcr.io's image is used as default image?

**Comment by xagent003** [comment]
I agree. It would be good to host stable release images. I'm unable to build container image, not sure why: https://github.com/ovn-org/ovn-kubernetes/issues/3573
