### ISSUE TITLE
daemonset.sh: sanity check for argument k8s-apiserver

### ISSUE THREAD

**Issue by vakabus** [ovn-org/ovn-kubernetes#3581]
I would suggest adding a sanity check for the `--k8s-apiserver=` option for `daemonset.sh`, so that it fails if the given URL does not start with URL scheme (I guess the only options are `http://` or `https://`).

---

Why am I suggesting this? I've just spent couple of days trying to debug an extremely weird issue, where one singular container (`sb-ovsdb`) was failing due to connection issues with this log output:

```
=============== sb-ovsdb ========== RUNNING
======= checking [192.168.1.221]:6641 OVSDB instance ===============
=============== setting ovnkube-db endpoints to 192.168.1.221
Error from server (BadRequest): the server rejected our request for an unknown reason
Failed to create endpoint with host(s) 192.168.1.221 for ovnkube-db service
```

I understood it as if some connection to `ovsdb-server` was failing, not connection to k8s api server. In the end, the problem was, that I set the the `daemonset.sh` argument to `--k8s-apiserver=192.168.1.221:6443` and not `--k8s-apiserver=https://192.168.1.221:6443`. I think the sanity check could prevent others from making the same mistake.

**Comment by kvaps** [comment]
Faced the same issue, thanks for opening
