### ISSUE TITLE
[Interconnect] [CI] Enable MultiHoming tests in control-plane lanes

### ISSUE THREAD

**Issue by tssurya** [ovn-org/ovn-kubernetes#3635]
As part of this https://github.com/ovn-org/ovn-kubernetes/pull/3366 we are skipping the multihoming tests.
https://github.com/ovn-org/ovn-kubernetes/pull/3620 should enable localnet and the second PR which will fix L2 will need to enable L2.

/assign @jcaamano 
/assign @maiqueb 

Close this issue as the associated PR merges

**Comment by maiqueb** [comment]
I think we can close this issue after #3765 merges, right @jcaamano ?

**Comment by tssurya** [comment]
done, closing issue
