### ISSUE TITLE
ovn-master pod cannot start  【log show error is initialize libovsdb NB client failed】

### ISSUE THREAD

**Issue by xfzhili** [ovn-org/ovn-kubernetes#3637]
ovnkube.go:369] error when trying to initialize libovsdb NB client: failed to connect to tcp:131.168.26.152:6641: database OVN_Northbound validation error (5): database Model contains model for table Mirror which is not present in schema. database Model contains model for table Static_MAC_Binding which is not present in schema. database Model contains model for table Chassis_Template_Var which is not present in schema. Mapper Error. Object type nbdb.NAT contains field GatewayPort (*string) ovs tag gateway_port: Column does not exist in schema. Mapper Error. Object type nbdb.LogicalSwitchPort contains field MirrorRules ([]string) ovs tag mirror_rules: Column does not exist in schema

base image is ubuntu:22.04
ovn version is showed as follows
![image](https://github.com/ovn-org/ovn-kubernetes/assets/51232972/2157b814-c4b1-428d-8ecd-0af5527adfad)

The running ovs version on the environment is 2.8.2

Is this error related to my not using ovs-node daemonset?

This problem has troubled me for a few days, how to deal with it, thanks.

**Comment by k82cn** [comment]
Please check whether there's a version mismatch.

**Comment by kvaps** [comment]
I have the same issue, no versions mismatch, I built my own image

**Comment by kvaps** [comment]
Problem gone after reverting 7e7e141d445da056e50ffee280838e6a98971bd8
