### ISSUE TITLE
When a Windows node is removed from a cluster the created resources should be cleaned up 

### ISSUE THREAD

**Issue by JacobTanenbaum** [ovn-org/ovn-kubernetes#3758]
Currently removing a windows node from a cluster leaves resources behind. There should be cleanup done on the node so that as many created resources as possible are removed from the machine.

**Comment by DmytroLinkin** [comment]
Hi. Could You please clarify, what do You mean "removing a windows node"? If You mean undeploying ovnk8s, then, unfortunately, it doesn't do a cleanup at all. Mb it will be added in foreseeable future.
