### ISSUE TITLE
cannot build daemonset container

### ISSUE THREAD

**Issue by seastco** [ovn-org/ovn-kubernetes#3767]
following the [build instructions](https://github.com/ovn-org/ovn-kubernetes#building-the-daemonset-container):

```
mkdir -p $HOME/work/src/github.com/ovn-org
cd $HOME/work/src/github.com/ovn-org
git clone https://github.com/ovn-org/ovn-kubernetes
cd $HOME/work/src/github.com/ovn-org/ovn-kubernetes/dist/images

# Build ovn docker image
pushd ../../go-controller
make
...
grep: github.com/ovn-org/ovn-kubernetes/go-controller/go.sum: No such file or directory
...
make: *** [all] Error 1
```

**Comment by seastco** [comment]
I must be missing something obvious here? how is anyone building this?

**Comment by DmytroLinkin** [comment]
Hi. Grep error pops up disregarding build was successful or not. Look carefully, You should have another error that is actual error.
