### ISSUE TITLE
Northd metrics can't get updated

### ISSUE THREAD

**Issue by npinaeva** [ovn-org/ovn-kubernetes#3774]
Need to change labels here https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/metrics/ovn_northd.go#L95 to work with ovn-ic names

**Comment by tssurya** [comment]
oh lol! totally possible we missed that one... I didn't know we hard coded things like that...

**Comment by tssurya** [comment]
I guess the label has to be changed to `app=ovnkube-controller` u/s but d/s i have to check i think its still app=ovnkube-master cc @ricky-rav

**Comment by tssurya** [comment]
@martinkennelly : Should this line that nadia pointed out be changed to ovnkube-controller foe d/s somehow?
