### ISSUE TITLE
Does ovn-kubernetes cross-node pod intercommunication support the vxlan protocol? Is there a channel configured?

### ISSUE THREAD

**Issue by xfzhili** [ovn-org/ovn-kubernetes#3782]

**Comment by DmytroLinkin** [comment]
Do You mean VXLAN instead of GENEVE? AFAIU - no. It can be used along with so called [hybrid overlay](https://github.com/ovn-org/ovn-kubernetes/blob/master/docs/hybrid-overlay.md).
