### ISSUE TITLE
ovnkube-trace doesn't work for dual-stack clusters

### ISSUE THREAD

**Issue by dceara** [ovn-org/ovn-kubernetes#3783]
At least one reason for it not working is (on a dual-stack kind cluster):
```
# ./ovnkube-trace -src-namespace default -src pod1 -dst-namespace default -dst pod2 -udp -dst-port 12345
F0717 12:01:33.944577  353723 ovnkube-trace.go:1223] Failed to get information from pod pod1: invalid output 0a:58:0a:f4:02:01 10.244.2.1/24 fd00:10:244:3::1/64
```

due to:
```
func getSwitchPortMacAddress(coreclient *corev1client.CoreV1Client, restconfig *rest.Config, podInfo *PodInfo, ovnNamespace, portPrefix string) (string, error) {
	tspCmd := "ovn-sbctl --no-leader-only " + podInfo.SbCommand + " --bare --no-heading --column=mac list Port_Binding " + portPrefix + podInfo.NodeName
	ipOutput, ipError, err := execInPod(coreclient, restconfig, ovnNamespace, podInfo.OvnKubePodName, "ovnkube-node", tspCmd, "")
	if err != nil {
		return "", fmt.Errorf("execInPod() failed. err: %s, stderr: %s, stdout: %s, podInfo: %v", err, ipError, ipOutput, podInfo)
	}
	// The ipOutput is with the following format: 0a:58:a8:fe:00:03 168.254.0.3/16, parse the mac address from it.
	macIP := strings.Split(strings.Replace(ipOutput, "\n", "", -1), " ")
	if len(macIP) != 2 {
		return "", fmt.Errorf("invalid output %s", ipOutput)
	}
	return macIP[0], nil
}
```

The `macIP` variable has length 3 (MAC + v4 + v6) in this case.

**Comment by dceara** [comment]
CC: @kyrtapz @pperiyasamy

**Comment by pperiyasamy** [comment]
Thanks @dceara for finding this out!
 Fixing it with this commit https://github.com/ovn-org/ovn-kubernetes/pull/3717/commits/b1620585b900842ae80d162749723d90b2336c2d.

**Comment by dceara** [comment]
As discussed offline 

> Thanks @dceara for finding this out! Fixing it with this commit [b162058](https://github.com/ovn-org/ovn-kubernetes/commit/b1620585b900842ae80d162749723d90b2336c2d).

Np but, as discussed offline, this commit partially fixes the issue.  I think the user should be allowed to specify which address family to be used for tracing.  Currently we always use IPv4 for dual-stack.  That might hide v6 problems.  I'd keep the issue open until we have a complete fix.

**Comment by pperiyasamy** [comment]
> > Thanks @dceara for finding this out! Fixing it with this commit [b162058](https://github.com/ovn-org/ovn-kubernetes/commit/b1620585b900842ae80d162749723d90b2336c2d).
> 
> Np but, as discussed offline, this commit partially fixes the issue. I think the user should be allowed to specify which address family to be used for tracing.

sure @dceara, now updated commit https://github.com/ovn-org/ovn-kubernetes/pull/3717/commits/3cabbd496ecfb80dfc1eab4e890dd5d5e76655b7 with taking which address family to use and uses pod ip accordingly.  
/cc @tssurya

**Comment by pperiyasamy** [comment]
@dceara can we close the issue now ? The relevant commit 6dc5c868c3ba9d623a324170d5fcc65fcde7b5fc is merged already.

**Comment by dceara** [comment]
> @dceara can we close the issue now ? The relevant commit [6dc5c86](https://github.com/ovn-org/ovn-kubernetes/commit/6dc5c868c3ba9d623a324170d5fcc65fcde7b5fc) is merged already.

Sounds good to me, thanks!

Fixed by https://github.com/ovn-org/ovn-kubernetes/pull/3717.
