### ISSUE TITLE
When I use ovs offload, is OS kernel 4.18 ok,？why do I need 5.7.0 and above？

### ISSUE THREAD

**Issue by xfzhili** [ovn-org/ovn-kubernetes#3809]

**Comment by xfzhili** [comment]
![image](https://github.com/ovn-org/ovn-kubernetes/assets/51232972/605d36de-1e61-4a15-a931-de8a24ba5b52)

**Comment by DmytroLinkin** [comment]
Hi,
Screenshot You are pointing to is HW offload for OVS. For regular OVS baseline is >4.6.
If HW offload is what You need, then You should refer to the driver documentation for Your HW in regard to supported offloading of Connection Tracking, Geneve tunnels, etc.. The easiest way to do that is to check kernel version and related docs.

**Comment by xfzhili** [comment]
#

> Hi, Screenshot You are pointing to is HW offload for OVS. For regular OVS baseline is >4.6. If HW offload is what You need, then You should refer to the driver documentation for Your HW in regard to supported offloading of Connection Tracking, Geneve tunnels, etc.. The easiest way to do that is to check kernel version and related docs.

**Comment by xfzhili** [comment]
> 您好， 屏幕截图您指向的是 OVS 的硬件卸载。对于常规 OVS 基线为 >4.6。 如果您需要硬件卸载，那么您应该参阅您的硬件的驱动程序文档，了解有关支持的连接跟踪、Geneve 隧道等卸载的信息。最简单的方法是检查内核版本和相关文档。

**Comment by DmytroLinkin** [comment]
> > Hi, Screenshot You are pointing to is HW offload for OVS. For regular OVS baseline is >4.6. If HW offload is what You need, then You should refer to the driver documentation for Your HW in regard to supported offloading of Connection Tracking, Geneve tunnels, etc.. The easiest way to do that is to check kernel version and related docs.
> 
> Thank you so much. This means that if 4.18 supports hardware offload, there is no need for 5.7.0？

In order to get HW offload You need, eventually, NIC with offload support + driver that support required features. If You sure that 4.18 kernel have everything - go ahead.

**Comment by xfzhili** [comment]
> > > Hi, Screenshot You are pointing to is HW offload for OVS. For regular OVS baseline is >4.6. If HW offload is what You need, then You should refer to the driver documentation for Your HW in regard to supported offloading of Connection Tracking, Geneve tunnels, etc.. The easiest way to do that is to check kernel version and related docs.
> > 
> > 
> > Thank you so much. This means that if 4.18 supports hardware offload, there is no need for 5.7.0？
> 
> In order to get HW offload You need, eventually, NIC with offload support + driver that support required features. If You sure that 4.18 kernel have everything - go ahead.
thank you very much
