### ISSUE TITLE
When I use the hw offload function, it doesn't seem to work well. Offloaded flow table not as expected

### ISSUE THREAD

**Issue by xfzhili** [ovn-org/ovn-kubernetes#3835]
when I ping pod2 in pod1, there is  two flow table offload
![image](https://github.com/ovn-org/ovn-kubernetes/assets/51232972/6b5dabc9-b201-40c3-a0f7-86eaba38884c)
[root@node-1 ~]# ovs-appctl dpctl/dump-flows -m type=offloaded
ufid:e32d66cd-c953-45a6-a7aa-ce4b4d8ded22, skb_priority(0/0),skb_mark(0/0),ct_state(0x22/0x3e),ct_zone(0/0),ct_mark(0/0x1),ct11),packet_type(ns=0/0,id=0/0),eth(src=0a:58:ac:01:00:0d,dst=0a:58:ac:01:00:0e),eth_type(0x0800),ipv4(src=172.1.0.8/255.255.2:0, bytes:0, used:2.890s, offloaded:yes, dp:tc, actions:89c4c6c7cdef365
ufid:674294e8-9b74-4ad8-8a60-9f82d78cdd94, skb_priority(0/0),skb_mark(0/0),ct_state(0x2a/0x3e),ct_zone(0/0),ct_mark(0/0x1),ct65),packet_type(ns=0/0,id=0/0),eth(src=00:00:00:00:00:00/00:00:00:00:00:00,dst=0a:58:ac:01:00:0d),eth_type(0x0800),ipv4(src=0 packets:0, bytes:0, used:3.830s, offloaded:yes, dp:tc, actions:ee8ec5e4f34ff11

there are  a few questions:
1）Each icmp packet is sent/delivered through vf rep, no flow hits hw offloaded flows, dump-flows pkt and bytes stat is zero
2)   I think these two pods are Layer 2 links, so the fast table should only care about dmac and ethtype
3）As shown in the dpctl/dump-flows, why does the matching keyword of offloaded flows have the ip address（src=172.1.0.8/255.255.2:0） of coredns, which is related to the design of ovn?

**Comment by DmytroLinkin** [comment]
@xfzhili Hi,
ICMP traffic is not offloaded by Connection Tracking. Please, use iperf or other TCP/UDP traffic generator.

**Comment by xfzhili** [comment]
> @xfzhili Hi, ICMP traffic is not offloaded by Connection Tracking. Please, use iperf or other TCP/UDP traffic generator.

@DmytroLinkin Hi， this message is important，thank you, 

 As shown in the figure below, when ping packets, the vf rep port will only capture the first icmp packet.Is this description correct?
![image](https://github.com/ovn-org/ovn-kubernetes/assets/51232972/c674b4b5-ee48-4dbc-9a2a-d2557a144379)

**Comment by xfzhili** [comment]
I use iperf to test and still find that no package can hit the offload flow table
