### ISSUE TITLE
hw offload works not right

### ISSUE THREAD

**Issue by xfzhili** [ovn-org/ovn-kubernetes#3861]
![image](https://github.com/ovn-org/ovn-kubernetes/assets/51232972/5a129b5b-f61e-42b1-b877-62efab64560a)
  
As I understand, L2 network connection does not require CT flow table，why flows has ct action？

In addition, the offloaded CT flow table only have the last level table. The hw nic can never match the CT state related fields, so it cannot hit the offload flow.

**Comment by xfzhili** [comment]
https://github.com/ovn-org/ovn-kubernetes/blob/master/docs/ovs_offload.md
ovs_offload.md shows that vf representor port can only catch the first icmp pkt。 This means that the packets all match the offload flow table
![image](https://github.com/ovn-org/ovn-kubernetes/assets/51232972/3bc6f4fa-04d6-4466-a234-b2a1ec100a14)

**Comment by moshe010** [comment]
@xfzhili we don't offload icmp when connection tracking is in used. You should check this with tcp traffic.

**Comment by xfzhili** [comment]
> @xfzhili we don't offload icmp when connection tracking is in used. You should check this with tcp traffic.
@moshe010  Is there any configuration for ovn-kubernetes to enable connection tracking?

I upgraded the kernel to 6.5.2, connection tracking works fine。Does this mean that connection tracking depends on the kernel version? Is it ovs or hw nic?

**Comment by MoonH2O** [comment]
hello,I encountered the problem of always restarting when deploying OVN. Do you have some wikis for deployment testing that I can refer to?
