### ISSUE TITLE
ovn-kubernetes installation works on Azure but not AWS

### ISSUE THREAD

**Issue by seastco** [ovn-org/ovn-kubernetes#3906]
I had to port my ovn-kubernetes installation over to AWS from Azure.

In AWS, when I apply the ovnkube-node daemonset, the networking of the nodes immediately deteriorates. By deteriorate I mean: node metrics immediately stop being sent to Datadog, a pod can't pull from Github or install packages. My session manager connection persists, but terminates after ~30 or so minutes. And then finally the nodes transition to NotReady state.

The nodes have 100GB+ of free memory, 99% CPU, 99% free disk space when this happens. When I describe the nodes, the cumulative used resources of the pods are no where close to hitting the nodes memory/CPU limits.

I did a side-by-side installation from scratch on both AWS/Azure and I see no differences in the logs being spit out by the ovn-kubernetes pods.

Some relevant context:
* I'm using Multus & using ovn-kubernetes CNI for the secondary interfaces of Kubevirt VMs. It's not being used as a primary CNI.
* Confirmed that per-cpu dispatch mode is being used in both AWS & Azure.
* OVS version: 2.17.5
* Azure VMs kernel version: 4.18.0-477.13.1.el8_8.x86_64
* EC2 instances kernel version: 5.15.128-81.144.amzn2.x86_64
* Not seeing anything strange in Kubelet logs or node events
* Primary CNI in Azure is [Calico](https://github.com/projectcalico/calico), primary CNI in AWS is [aws-cni](https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html).
* My Kubevirt VMs can still ping and SSH to each other using both their primary network interface IPs (aws primary network) and secondary network interface IPs (ovn network) until the node dies.

**Comment by seastco** [comment]
I'm using this image: https://github.com/ovn-org/ovn-kubernetes/pkgs/container/ovn-kubernetes%2Fovn-kube-f/95153159

Which profile do you want for pprof?

**Comment by martinkennelly** [comment]
`--metrics-enable-pprof` enable with this flag

Thich will be passed to func to start a metrics server:
```
// Start metric server for master and node. Expose the metrics HTTP endpoint if configured.
	// Non LE master instances also are required to expose the metrics server.
	if config.Metrics.BindAddress != "" {
		metrics.StartMetricsServer(config.Metrics.BindAddress, config.Metrics.EnablePprof,
			config.Metrics.NodeServerCert, config.Metrics.NodeServerPrivKey, ctx.Done(), ovnKubeStartWg)
	}
```

And `EnablePprof` is a bool for:

```
if enablePprof {
		mux.HandleFunc("/debug/pprof/", pprof.Index)
		mux.HandleFunc("/debug/pprof/cmdline", pprof.Cmdline)
		mux.HandleFunc("/debug/pprof/profile", pprof.Profile)
		mux.HandleFunc("/debug/pprof/symbol", pprof.Symbol)
		mux.HandleFunc("/debug/pprof/trace", pprof.Trace)

		// Allow changes to log level at runtime
		mux.HandleFunc("/debug/flags/v", stringFlagPutHandler(klogSetter))
	}
```
Then you can can get the pprof using this article:
https://jvns.ca/blog/2017/09/24/profiling-go-with-pprof/

Grab all the 'types'. Zip them and link them here.

**Comment by martinkennelly** [comment]
If you want to give back as well to this repo - we'd love a PR to add docs for this to the `./docs` dir

**Comment by seastco** [comment]
I'd be happy to! However for the life of me I cannot figure out how to pass in this flag. In my daemonset:
```
- command:
  - /root/ovnkube.sh
  - ovn-master
- args:
  - --metrics-enable-pprof=true
```
I've tried `-metrics-enable-pprof=true` and `metrics-enable-pprof=true` as well.

```
curl 10.48.3.18:9409/metrics/debug/pprof/profile
404 page not found
```

**Comment by seastco** [comment]
One thing I noticed when comparing Azure VMs & EC2 instances, the EC2 instances have MTU 9001 for all of the network interfaces. Azure VMs are using 1450 or 1500.

I see this in the EC2 instance dmesg  "breth0 dropped over-mtu packet: 1534 > 1500" about ten times as soon as I apply the ovnkube-node ds. This seems related?
