### ISSUE TITLE
flakey test: Load Balancer Service Tests with MetalLB Should ensure load balancer service works with 0 node ports when ETP=local 

### ISSUE THREAD

**Issue by jcaamano** [ovn-org/ovn-kubernetes#3948]
Observed:
https://github.com/ovn-org/ovn-kubernetes/actions/runs/6397392101/job/17366143195

**Comment by jcaamano** [comment]
@pperiyasamy is looking at this one

**Comment by numansiddique** [comment]
FYI - This same test failed here for me - https://github.com/ovn-org/ovn-kubernetes/actions/runs/7147352980/job/19467115609?pr=4044

**Comment by trozet** [comment]
@pperiyasamy this could be related to #4053 where the MTU was never being reset after a test case. Lets see how it goes after that is fixed. Additionally I have worked on some commits that will tcpdump, conntrack dump, datapath flow dump while the e2e test is running:

https://github.com/trozet/ovn-kubernetes/pull/8

You can leverage these to debug as well.

**Comment by tssurya** [comment]
are we still seeing this after https://github.com/ovn-org/ovn-kubernetes/pull/4053 has merged?

**Comment by tssurya** [comment]
I think this one is passing, seeing another failing : https://github.com/ovn-org/ovn-kubernetes/actions/runs/7672271207/job/20913218060?pr=4065 will open new issue
