### ISSUE TITLE
Launching a daemonset with hostNetwork:true and a hostport fails with network host not found

### ISSUE THREAD

**Issue by cn-mayank** [ovn-org/ovn-kubernetes#400]
I used the ansible playbook and have a cluster on aws running with kubernetes 1.10.
However when I try to create a daemonset with hostport to expose and setting hostNetwork:true in the spec, the pod gets stuck in ContainerCreating state with the error message as

`Warning   FailedCreatePodSandBox   kubelet, ec2amaz-734qnce   Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "rssdaemon-windows-p54hs": Error response from daemon: network host not found`

Is it supported and what can I do to resolve ? Appreciate your help.
Thanks!

**Comment by shettyg** [comment]
It is likely that we are missing something to support hostPort. We support hostNetwork though. I am not sure what is it that we are missing though. Ideally, hostPort should have worked transparently - it does need its own CNI plugin - but it likely does not.

**Comment by shettyg** [comment]
@dcbw Any ideas?

**Comment by cn-mayank** [comment]
Thanks @shettyg for your prompt reply. Do you mean that ovn-kubernetes does support it but the ansible-playbook in contrib could be modified to support hostPort ?

**Comment by shettyg** [comment]
I don't know whether ovn-kubernetes supports hostPort because I have never tried it. I know that hostPort has its own CNI plugin. But, I think it may need a chain in OVN CNI plugin. I guess, you can assume for now that ovn-kubernetes does not support hostPort.

**Comment by shettyg** [comment]
>It should be handled by the runtime (docker/crio/rkt), or by CNI plugin. Is this a complaint for the Windows node by any chance?

Rajat, have you tried hostPort for linux with ovn-kubernetes? Is hostPort set to true only when hostNetwork is also set to true?
