### ISSUE TITLE
Support multicast for secondary networks

### ISSUE THREAD

**Issue by seastco** [ovn-org/ovn-kubernetes#4101]
Multicast is disabled for secondary networks.

https://github.com/ovn-org/ovn-kubernetes/blob/665e3b05b9375564691fd0080d9c27c33d0a9e91/go-controller/pkg/ovn/secondary_layer2_network_controller.go#L70-L72 

Would love to have this. Could we consider adding this please?

**Comment by seastco** [comment]
It looks like this is not supported because it's not configurable per network. Where should this config live? The NAD?

**Comment by seastco** [comment]
Actually, does multicast work by default for layer2 secondary networks? Is the overlay network encapsulating the multicast traffic until it makes it to the layer2 switch?

Here I am testing multicast between two VMs on different nodes. Multicast is not enabled. `enp10s0` is a layer2 network.

![image](https://github.com/ovn-org/ovn-kubernetes/assets/91042401/02d066ca-d9ad-4455-b4d7-40cc1bb8c2f3)

**Comment by martinkennelly** [comment]
cc @maiqueb

**Comment by maiqueb** [comment]
IIUC - and from a simple glance of the code - we do have that flag.

... but I don't think we actually do anything with it. 

I do *not* know the multicast implementation in the default network, but seems [there is code](https://github.com/ovn-org/ovn-kubernetes/blob/7447607048cf6fca57b0a51dd3361e694fea851d/go-controller/pkg/ovn/master.go#L164) to drop multicast packets that is only provisioned if multi-cast is enabled. We're not doing it for the secondary network.

**Comment by seastco** [comment]
Could we re-open this?
