### ISSUE TITLE
ovnkube-node in DPU mode is not becoming ready due to missing cni config

### ISSUE THREAD

**Issue by tabuhariri** [ovn-org/ovn-kubernetes#4113]
I am testing on a Kubernetes cluster deployed with a node which has the control plane, and another node which also has a DPU.

The ovnkube-node on the DPU (in my particular case this is in DPU mode), is not comming up properly, because it is missing its readiness probe: [readiness-probe.go](https://github.com/ovn-org/ovn-kubernetes/blob/12681a716a4c98d8337c7815f15966cc5bba3502/go-controller/cmd/ovn-kube-util/app/readiness-probe.go#L162C1-L171C2),
due to the lack of the CNI configuration file on that particular host.

Looking at the codebase, I saw that the aforementioned CNI configuration is not being written on the DPU because of the following [logic](https://github.com/ovn-org/ovn-kubernetes/blob/12681a716a4c98d8337c7815f15966cc5bba3502/go-controller/pkg/node/default_node_network_controller.go#L1130C2-L1143C4)

I have tested with the following [PR](https://github.com/ovn-org/ovn-kubernetes/pull/4112) and it solves my issue, however I am unsure what are the implications of always writing the CNI configuration.

**Comment by jcaamano** [comment]
How are you deploying ovn-kubernetes on the DPU itself?

Not all of us have experience working with DPUs. @wizhaoredhat and @cathy-zhou should be able to help you out however.
