### ISSUE TITLE
flake: [FAIL] e2e egress IP validation [It] Should validate the egress IP SNAT functionality against host-networked pods

### ISSUE THREAD

**Issue by tssurya** [ovn-org/ovn-kubernetes#4127]
https://github.com/ovn-org/ovn-kubernetes/actions/runs/7755737906/job/21152530666?pr=4125

```
Summarizing 1 Failure:
  [FAIL] e2e egress IP validation [It] Should validate the egress IP SNAT functionality against host-networked pods
  /home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/egressip.go:757

Ran 86 of 246 Specs in 3179.378 seconds
FAIL! -- 85 Passed | 1 Failed | 0 Pending | 160 Skipped
--- FAIL: TestE2E (3179.39s)
FAIL
FAIL	github.com/ovn-org/ovn-kubernetes/test/e2e	3179.440s
FAIL
make: *** [Makefile:32: control-plane] Error 1
make: Leaving directory '/home/runner/work/ovn-kubernetes/ovn-kubernetes/test'
Error: Process completed with exit code 2.

```

This should not be failing, used to pass. This and https://github.com/ovn-org/ovn-kubernetes/issues/4115

**Comment by tssurya** [comment]
I think we have regressed or broken something recently.

**Comment by martinkennelly** [comment]
Couldnt find a reason why this flakes from the logs. Tried to reproduce locally looping through all the tests over night and didnt see it happen.
Waiting to see if others see it again before investing more time.
I see it occurred before my recent EIP multi nic changes so i dont think thats the PR that introduced it.

**Comment by trozet** [comment]
I see it here @martinkennelly 
https://github.com/ovn-org/ovn-kubernetes/pull/4124

Did you try examining the saved DBs from the test failure and simulate ovn-trace?

**Comment by qinqon** [comment]
Another one https://github.com/ovn-org/ovn-kubernetes/pull/4140

**Comment by martinkennelly** [comment]
> I see it here @martinkennelly #4124
> 
> Did you try examining the saved DBs from the test failure and simulate ovn-trace?

No.

I did a trace. I see the wrong mac address being assigned for the dst. I expected it to be the mac address of `ovn-worker2` but I see its the mac address of `ovn-control-plane` node:

OVN trace from pod on `ovn-worker` to secondary IP on `ovn-worker2`:
```
17. lr_in_arp_resolve (northd.c:13723): ip4, priority 1, uuid e0a83adf
    get_arp(outport, reg0);
    /* MAC binding to 02:42:ac:12:00:02. */
    next;
```

OVN control plane node:
```
    port rtoe-GR_ovn-control-plane
        mac: "02:42:ac:12:00:02"
```

Where as I expected the MAC to be `ovn-worker2`s:
```
    port rtoe-GR_ovn-worker2
        mac: "02:42:ac:12:00:03"

```

Listing node IPs for `ovn-worker2`:
```
ovn-nbctl list Chassis_Template_Var
_uuid               : 0f04a923-b62f-433b-b930-1f726cf36d8a
chassis             : "6ad2652d-16f8-47cb-bd61-258e4cafc76e"
external_ids        : {}
variables           : {NODEIP_IPv4_0="172.18.0.3", NODEIP_IPv4_1="172.18.1.1"}

```

Listing node IPs for `ovn-control-plane`:

```
ovn-nbctl list Chassis_Template_Var
_uuid               : fd79223e-6103-4fed-bd19-a8dd382d30ac
chassis             : "48f6eb55-09dc-444b-8eee-cfde3262aed5"
external_ids        : {}
variables           : {NODEIP_IPv4_0="172.18.0.2", NODEIP_IPv4_1="172.18.1.1"}

```

Within `ovn-control-plane`s ovnkube controller, I see `172.18.1.1` being added as a node IP before the test in this issue and then removed a bit later:
```
12:46:40.316143    1673 node_ip_handler_linux.go:89] Removing IP: {172.18.1.1 ffffffff}, from node IP manager   
```

I dont see the update to remove it from `Chassis_Template_Var` entry...

I can reproduce locally now.

**Comment by martinkennelly** [comment]
Cannot reproduce the timeout locally but its clear from the ovn trace that theres a stale mac for dst.

**Comment by martinkennelly** [comment]
I don't expect us to support migrating a node IP to another node. Need to confirm.
For now, Ill just change the IP within the test case so theres no conflict.
