### ISSUE TITLE
Support running Egress Services and IPV6

### ISSUE THREAD

**Issue by tssurya** [ovn-org/ovn-kubernetes#4132]
See https://github.com/ovn-org/ovn-kubernetes/pull/4106 and https://github.com/ovn-org/ovn-kubernetes/issues/4131
Egress services uses metalLB for the e2e's.

Goal: Troubleshoot with IPV6 KIND and fix it and re-enable the tests

**Comment by tssurya** [comment]
/assign @kyrtapz : Is this done?
Can you link PR and close this?

**Comment by kyrtapz** [comment]
This is fixed with https://github.com/ovn-org/ovn-kubernetes/pull/4200
Not sure if I have the permissions to close this issue ;]
/close
