### ISSUE TITLE
FLAKE: Kubevirt Virtual Machines when live migration [It] with pre-copy succeeds, should keep connectivity

### ISSUE THREAD

**Issue by tssurya** [ovn-org/ovn-kubernetes#4175]
Sample failure: https://github.com/ovn-org/ovn-kubernetes/actions/runs/7960589633/job/21730982594?pr=4159

**Comment by jcaamano** [comment]
Closing as dup of https://github.com/ovn-org/ovn-kubernetes/issues/3986

**Comment by tssurya** [comment]
AH woops haha, thanks Jaime, I didn't catch the other flake in 1st glance
