### ISSUE TITLE
Pod stuck in ContainerCreating after too many range is full errors

### ISSUE THREAD

**Issue by freedge** [ovn-org/ovn-kubernetes#4218]
if a pod fails multiple times to get an IP due to a "err: range is full" error, the pod will stay stuck in ContainerCreating forever

as implemented through
https://github.com/ovn-org/ovn-kubernetes/commit/906a598c971b06ff76f99d4294f7491b1af05499

the retry is done for around 15 minutes up until the final attempt, then the pod hangs there until ovnkube-controller is restarted or the pod deleted.
As the pod status says "Creating" I believe ovnk should keep trying.

**Comment by ricky-rav** [comment]
Even in level-driven controllers there's usually a cap on the number of retries (re-queues). We can revisit our max of 15 if there's a specific need, but I think it's a lot more complicated to handle if we /never/ give up an add/update/delete operation than if we give up after n failed attempts

**Comment by filanov** [comment]
I was searching for a bit and from a CNI point of view there is no way to mark a pod in error state, as you saw CNI plugin failure will result in `ContainerCreating` state
if there are issues with node condition or pod scheduling the pod may be in `NotReady` or `Pending` state but we don't really have control over it.

There is an option to add a custom condition on the pod but it's not always easy for such a basic resource.

Sending events can be a workaround but we will need to send the even periodically so the user will be able to see it. 

So CNI doesn't have a direct way to put a pod in a final state.

I consulted with more people to get more opinions around it, and the majority thinks that we should go with the k8s way and retry forever or until the user delete the pod. 

For this specific case the user have a way to fix, for example he can remove other pods and release some address or reconfigure the system and increase the range (not sure if it's really possible)

Anyway i suggest to remove the timeout and retry and increase the timeout between attempts
