### ISSUE TITLE
Improve handling of SKIPPED_TESTS in e2e-cp.sh

### ISSUE THREAD

**Issue by kyrtapz** [ovn-org/ovn-kubernetes#4229]
Improve how we handle skipped tests in e2e-cp.sh.
Currently the SKIPPED_TESTS is a variable that we add "|test" to, this is error prone and can cause us skipping tests unintentionally.
Example bug: https://github.com/ovn-org/ovn-kubernetes/pull/4227

**Comment by tssurya** [comment]
another example: https://github.com/ovn-org/ovn-kubernetes/pull/4253

**Comment by tssurya** [comment]
@jluhrsen : go wild and reinvent this :) I don't have any specific preference but can we see how K8s/K8s does these things just to get some motivation maybe?
