### ISSUE TITLE
When ACL is applied to a subnet, the action allow-related affects the other actions，such as drop

### ISSUE THREAD

**Issue by BigCousin-z** [ovn-org/ovn-kubernetes#4285]
configure as：
ovn-nbctl acl-list subnet
1：to-lport 2000 (ip4.src == 100.100.200.0/24) drop

The network from ping 100.100.100.2 to 100.100.200.2 is not work.
when I modify the configure ，as：
ovn-nbctl acl-list subnet
1：to-lport 2000 (ip4.src == 100.100.200.0/24) drop
2：to-lport 2000 (ip4.src == 1.2.3.4/24) allow-related

The network from ping 100.100.100.2 to 100.100.200.2 is connected.
Will allow related-affect the correctness of other rule actions?

ovn : 21.12.3
ovs : 2.17.5

The acl rule applies to the ls subnet。

**Comment by dceara** [comment]
Replied on the [ovn-org/ovn issue](https://github.com/ovn-org/ovn/issues/241#issuecomment-2063571311)
