### ISSUE TITLE
CI Flake: Dualstack jobs failing due to running out of disk space

### ISSUE THREAD

**Issue by tssurya** [ovn-org/ovn-kubernetes#4287]
See
https://github.com/ovn-org/ovn-kubernetes/actions/runs/8728901846/job/23968836196?pr=4245
https://github.com/ovn-org/ovn-kubernetes/actions/runs/8728901846/job/23968836684?pr=4245

```
~/work/ovn-kubernetes/ovn-kubernetes/test/e2e ~/work/ovn-kubernetes/ovn-kubernetes/test
+ go test -test.timeout 180m -v . -ginkgo.v -ginkgo.focus DualStack -ginkgo.timeout 3h -ginkgo.flake-attempts 2 '-ginkgo.skip=Should validate flow data of br-int is sent to an external gateway with sflow|ipv6 pod|Should validate connectivity before and after deleting all the db-pods at once in Non-HA mode|  e2e br-int NetFlow export validation|Should ensure load balancer service|LGW|disabling egress nodes impeding Legacy health check|Multi Homing|Node IP and MAC address migration|Multi node zones interconnect|External Gateway|Kubevirt Virtual Machines' -provider skeleton -kubeconfig /home/runner/ovn.conf --num-nodes=2 --report-dir=/home/runner/work/ovn-kubernetes/ovn-kubernetes/test/_artifacts --report-prefix=DualStack-conversion-shared-HA-interconnect-disabled_
# github.com/ovn-org/ovn-kubernetes/test/e2e.test
/opt/hostedtoolcache/go/1.21.9/x64/pkg/tool/linux_amd64/link: mapping output file failed: no space left on device
FAIL	github.com/ovn-org/ovn-kubernetes/test/e2e [build failed]
FAIL
make: *** [Makefile:32: control-plane] Error 1
make: Leaving directory '/home/runner/work/ovn-kubernetes/ovn-kubernetes/test'
Error: Process completed with exit code 2.
```

**Comment by jluhrsen** [comment]
@tssurya @trozet , I looked through all the CI runs in the [last 5 pages](https://github.com/ovn-org/ovn-kubernetes/actions) and did not find this happening. I assume it
must not be very frequent. [Here](https://github.com/ovn-org/ovn-kubernetes/pull/4305) is a PR that will add some output before and  after go test for those jobs you saw
this in. That will at least give us a little data to check out the next time this happens. I'll try to actively monitor CI to
find when it happens again.

**Comment by jluhrsen** [comment]
I've checked failed jobs on PRs periodically and was not seeing this specific issue any more. just recently checked the last 20 failed PRs and
it's not there. closing this now, but we can re-open if people run in to it again. We do have some extra storage related logging happening
so if it does show up we may get more clues.
