### ISSUE TITLE
EgressService Should validate egress service has higher priority than EgressIP when not assigned to the same node [It] ipv4 pods

### ISSUE THREAD

**Issue by tssurya** [ovn-org/ovn-kubernetes#4289]
This has failed two times so far:
See 
https://github.com/ovn-org/ovn/actions/runs/8737656006/job/23975653082#step:12:8883
and 
https://github.com/ovn-org/ovn-kubernetes/actions/runs/8728901846/job/23950504469?pr=4245

**Comment by flavio-fernandes** [comment]
Also seen here, in release-1.0 branch:  https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4761
