### ISSUE TITLE
Create HNS endpoint as part of hybrid-overlay-node on Windows

### ISSUE THREAD

**Issue by sebsoto** [ovn-org/ovn-kubernetes#4356]
### What would you like to be added?

hybrid-overlay-node should create an endpoint for the HNS network it maintains.

### Why is this needed?

In order to make use of the network a user has to create an endpoint for the HNS network which hybrid-overlay-node creates.

```
# Create HNS endpoint if it doesn't exist
$endpoint = Invoke-HNSRequest GET endpoints | where { $_.Name -eq 'VIPEndpoint'}
if( $endpoint -eq $null) {
    $endpoint = New-HnsEndpoint -NetworkId $hns_network.ID -Name "VIPEndpoint"
    Attach-HNSHostEndpoint -EndpointID $endpoint.ID -CompartmentID 1
}
```

By moving this functionality into hybrid-overlay-node this removes this step for the user.

**Comment by tssurya** [comment]
@JacobTanenbaum : can you help triage this please?
