### ISSUE TITLE
Cleanup Kubevirt Live Migration docs

### ISSUE THREAD

**Issue by tssurya** [ovn-org/ovn-kubernetes#4398]
### What would you like to see added/updated/deleted in our docs?

Please have 1 doc under features https://github.com/ovn-org/ovn-kubernetes/blob/master/docs/features/live-migration.md I don't understand why we have another one here: https://github.com/ovn-org/ovn-kubernetes/blob/master/docs/design/live-migration.md can we combine them?

Can you follow the templates for docs here: https://github.com/ovn-org/ovn-kubernetes/blob/master/docs/features/template.md

We are trying to cleanup and get our repo in shape for CNCF application, Please add diagrams to explain the migration

### Why is this needed?

See https://www.cncf.io/blog/2022/07/11/kubevirt-kube-ovn-networking-for-cloud-native-virtualization/  we'd like to do something similar but our docs are not pretty yet. We want to collaborate better with kubevirt community moving forward

Also for end users who are starting out we need to make https://ovn-kubernetes.io/features/live-migration/ look nicer

**Comment by qinqon** [comment]
We will take a look.
