### ISSUE TITLE
Flake: should work on secondary node interfaces for ETP=local and ETP=cluster when backend pods are also served by EgressIP 

### ISSUE THREAD

**Issue by tssurya** [ovn-org/ovn-kubernetes#4447]
### Which jobs are flaking?

control-plane

### Which tests are flaking?

  [FAIL] Services of type NodePort [It] should work on secondary node interfaces for ETP=local and ETP=cluster when backend pods are also served by EgressIP
  /home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/e2e.go:351

### Since when has it been flaking?

Last week saw this happening frequently since last week on many PRs

### Reason for failure (if possible)

have not done initial triage

### Anything else we need to know?

https://github.com/ovn-org/ovn-kubernetes/actions/runs/9546389361/job/26310246129?pr=4446

**Comment by tssurya** [comment]
https://github.com/ovn-org/ovn-kubernetes/actions/runs/9546389361/job/26310244533?pr=4446

**Comment by flavio-fernandes** [comment]
Also seen here, in the release-1.0 branch:
https://github.com/ovn-org/ovn-kubernetes/actions/runs/9686936475/job/26731359400?pr=4465
