### ISSUE TITLE
kind helm no longer works when deployed with NAD listener

### ISSUE THREAD

**Issue by flavio-fernandes** [ovn-org/ovn-kubernetes#4534]
### What happened?

With PR https://github.com/ovn-org/ovn-kubernetes/pull/4518 we introduced a regression on helm based deployments related to rbacs:

```
I0716 18:28:36.852466    1484 reflector.go:325] Listing and watching *v1.NetworkAttachmentDefinition from github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/client/informers/externalversions/factory.go:117
W0716 18:28:36.853209    1484 reflector.go:539] github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/client/informers/externalversions/factory.go:117: failed to list *v1.NetworkAttachmentDefinition: network-attachment-definitions.k8s.cni.cncf.io is forbidden: User "system:ovn-node:ovn-worker2" cannot list resource "network-attachment-definitions" in API group "k8s.cni.cncf.io" at the cluster scope
```

### What did you expect to happen?

This should work as it did before PR https://github.com/ovn-org/ovn-kubernetes/pull/4518 was merged.

### How can we reproduce it (as minimally and precisely as possible)?

`./kind-helm.sh -mne`

### Anything else we need to know?

The fix should be a small change to rbacs when deploying using helm.

### OVN-Kubernetes version

<details>

```console
$ ovnkube --version
[root@ovn-control-plane ~]# ovnkube --version
Version: 1.0.0
Git commit: 3275d9949490ba996f1ce60061bd91d5ca0dc934
Git branch: master
Go version: go1.22.2
Build date: 2024-07-16
OS/Arch: linux amd64
```

</details>

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### OVN version

<details>

```console
$ oc rsh -n ovn-kubernetes ovnkube-node-xxxxx (pick any ovnkube-node pod on your cluster)
$ rpm -q ovn
# paste output here
```

</details>

### OVS version

<details>

```console
$ oc rsh -n ovn-kubernetes ovs-node-xxxxx (pick any ovs pod on your cluster)
$ rpm -q openvswitch
# paste output here
```

</details>

### Platform

<details>

Is it baremetal? GCP? AWS? Azure?
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

**Comment by tssurya** [comment]
@flavio-fernandes how come helm lane was green though on therrgressed PR? I think we are missing test coverage ?

**Comment by flavio-fernandes** [comment]
> @flavio-fernandes how come helm lane was green though on therrgressed PR? I think we are missing test coverage ?

yeah. the existing helm lane was not using multi_network. Apologies for abusing the meaning of the word "regressed".
I'm adding a new lane to make sure this does gets covered going fwd.
