### ISSUE TITLE
DATA RACE during egress firewall unit tests with config.PrepareTestConfig()

### ISSUE THREAD

**Issue by trozet** [ovn-org/ovn-kubernetes#4592]
### Which jobs are flaking?

unit-tests

### Which tests are flaking?

configures egress firewall correctly with node selector, gateway mode: local, IP mode: IPv6

### Since when has it been flaking?

August 4th, 2024

### Reason for failure (if possible)

Data race seen during prepare test config in the unit tests:

https://github.com/ovn-org/ovn-kubernetes/pull/4583#issuecomment-2267883251

Also seen here:
https://github.com/ovn-org/ovn-kubernetes/pull/4548#discussion_r1705083378

**Comment by martinkennelly** [comment]
Seen again here https://github.com/ovn-org/ovn-kubernetes/pull/4580

**Comment by flavio-fernandes** [comment]
Seen again here https://github.com/ovn-org/ovn-kubernetes/pull/4544

https://productionresultssa10.blob.core.windows.net/actions-results/ba089aad-eecf-433c-8a16-d1cc30edcef0/workflow-job-run-2e838305-561b-5be5-e4e8-ae8cf3accd9c/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-08-14T11%3A41%3A41Z&sig=%2F0KnS02MBfca8eEv6H2djVT2gCZ2y2Ptg2Et0FG1suY%3D&ske=2024-08-14T19%3A35%3A10Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-08-14T07%3A35%3A10Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-05-04&sp=r&spr=https&sr=b&st=2024-08-14T11%3A31%3A36Z&sv=2024-05-04

**Comment by npinaeva** [comment]
I think it may be another flake, this issue is for UT failure, which I can't find in the linked PR.
I also I think I might have fixed it with https://github.com/ovn-org/ovn-kubernetes/pull/4611
