### ISSUE TITLE
[FAIL] Network Segmentation a user defined primary network created using NetworkAttachmentDefinitions is isolated from the default network [It] with L3 dualstack primary UDN

### ISSUE THREAD

**Issue by dceara** [ovn-org/ovn-kubernetes#4628]
### Which jobs are flaking?

network-segmentation

### Which tests are flaking?

[FAIL] Network Segmentation a user defined primary network created using NetworkAttachmentDefinitions is isolated from the default network [It] with L3 dualstack primary UDN
   /home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/network_segmentation.go:265

### Since when has it been flaking?

No real idea.. it was probably working when it was originally added.

### Anything else we need to know?

Link https://github.com/ovn-org/ovn-kubernetes/actions/runs/10402965859/job/28809303876

**Comment by flavio-fernandes** [comment]
also seen here: https://github.com/ovn-org/ovn-kubernetes/actions/runs/10429564860/job/28887403958?pr=4544

**Comment by tssurya** [comment]
also seen here: https://github.com/ovn-org/ovn-kubernetes/actions/runs/10415760296/job/28847461365?pr=4549
