### ISSUE TITLE
KubeVirt live migration lane is flaking

### ISSUE THREAD

**Issue by maiqueb** [ovn-org/ovn-kubernetes#4709]
### Which jobs are flaking?

KubeVirt live migration.

Parameters:
- noHA
- shared
- dualstack
- SnatGW
- 1br
- ic-single-node-zones, 3

### Which tests are flaking?

Kubevirt Virtual Machines with default pod network when live migration [It] with pre-copy succeeds, should keep connectivity

### Since when has it been flaking?

https://github.com/ovn-org/ovn-kubernetes/actions/runs/10777563371/job/29917387459?pr=4651

**Comment by oshoval** [comment]
https://github.com/ovn-org/ovn-kubernetes/actions/runs/10938484527/job/30367928920?pr=4708

**Comment by flavio-fernandes** [comment]
Also seen here: https://github.com/ovn-org/ovn-kubernetes/actions/runs/11131867792/job/30935680589?pr=4508
