### ISSUE TITLE
UT: UDN: Change the cluster-subnet versus node-subnet tests

### ISSUE THREAD

**Issue by tssurya** [ovn-org/ovn-kubernetes#4723]
### What would you like to see added/updated/deleted in our end-to-end tests?

https://github.com/ovn-org/ovn-kubernetes/pull/4718#issuecomment-2345663665

### Why is this needed?

0 coverage there even with unit tests dunno why.

**Comment by trozet** [comment]
Looks like at least for the route policy issue this is because in the unit test there is only 1 node, so it by chance gets the "right" management IP. For the static route there are only 2 static routes expected:

```
func expectedLayer3EgressEntities(netInfo util.NetInfo, gwConfig util.L3GatewayConfig) []libovsdbtest.TestData {
	const (
		routerPolicyUUID1 = "lrpol1-UUID"
		routerPolicyUUID2 = "lrpol2-UUID"
		staticRouteUUID1  = "sr1-UUID"
		staticRouteUUID2  = "sr2-UUID"
	)
	joinIPAddr := dummyJoinIP().IP.String()
	clusterRouterName := fmt.Sprintf("%s_ovn_cluster_router", netInfo.GetNetworkName())
	rtosLRPName := fmt.Sprintf("%s%s", ovntypes.RouterToSwitchPrefix, netInfo.GetNetworkScopedName(nodeName))
	rtosLRPUUID := rtosLRPName + "-UUID"
	nodeIP := gwConfig.IPAddresses[0].IP.String()
	networkIPv4Subnet := networkSubnet(netInfo)
	subnet := netInfo.Subnets()[0] // egress requires subnets. So far, these helpers do not work for dual-stack

	gatewayChassisUUID := fmt.Sprintf("%s-%s-UUID", rtosLRPName, gwConfig.ChassisID)
	expectedEntities := []libovsdbtest.TestData{
		&nbdb.LogicalRouter{
			Name:         clusterRouterName,
			UUID:         clusterRouterName + "-UUID",
			Ports:        []string{rtosLRPUUID},
			StaticRoutes: []string{staticRouteUUID1, staticRouteUUID2},
			Policies:     []string{routerPolicyUUID1, routerPolicyUUID2},
			ExternalIDs:  standardNonDefaultNetworkExtIDs(netInfo),
		},
		&nbdb.LogicalRouterPort{UUID: rtosLRPUUID, Name: rtosLRPName, Networks: []string{"192.168.0.1/16"}, MAC: "0a:58:c0:a8:00:01", GatewayChassis: []string{gatewayChassisUUID}},
		expectedGRStaticRoute(staticRouteUUID1, networkIPv4Subnet, gwRouterIPAddress().IP.String(), &nbdb.LogicalRouterStaticRoutePolicySrcIP, nil, netInfo),
		expectedGRStaticRoute(staticRouteUUID2, gwRouterIPAddress().IP.String(), gwRouterIPAddress().IP.String(), nil, nil, netInfo),
		expectedLogicalRouterPolicy(routerPolicyUUID1, netInfo, nodeName, nodeIP, managementPortIP(subnet.CIDR).String()),
		expectedLogicalRouterPolicy(routerPolicyUUID2, netInfo, nodeName, joinIPAddr, managementPortIP(subnet.CIDR).String()),
	}
```

The static route works because of this function:
```
func networkSubnet(netInfo util.NetInfo) string {
	return strings.TrimSuffix(subnetsAsString(netInfo.Subnets())[0], "/24")
}
```

which turns it from a /16 to a /24. So the question remains why isnt the test looking for the /16 route as well. I wonder if thats because the test is running as lgw mode and we dont create that route unless its shared gw mode.

**Comment by tssurya** [comment]
unfortunately none of tests have LGW mode coverage. I am adding LGW unit tests in one of the services UDN PRs below on the list. all of these are SGW.

**Comment by tssurya** [comment]
So my guess with regards to unit tests are correct: https://github.com/ovn-org/ovn-kubernetes/pull/4718#issuecomment-2345663665

the clustersubnet in the tests which is 192.168.0.0/16 is also what is being used as the nodesubnet 192.168.0.0/16 on the node's annotation, hence we don't catch differences...

**Comment by tssurya** [comment]
@trozet :

```
which turns it from a /16 to a /24. So the question remains why isnt the test looking for the /16 route as well. I wonder if thats because the test is running as lgw mode and we dont create that route unless its shared gw mode.
```
that is because gateway is not what creates the /16 :) its EgressIP...

**Comment by tssurya** [comment]
> 
> The static route works because of this function:
> 
> ```
> func networkSubnet(netInfo util.NetInfo) string {
> 	return strings.TrimSuffix(subnetsAsString(netInfo.Subnets())[0], "/24")
> }
> ```
> 

I am changing this logic to make the test more explicit
