### ISSUE TITLE
Fatal error: patch port <port name> ofport changed from 32 to 

### ISSUE THREAD

**Issue by npinaeva** [ovn-org/ovn-kubernetes#4783]
### Which jobs are flaking?

https://github.com/ovn-org/ovn-kubernetes/actions/runs/11384905304/job/31675052357?pr=4647

### Which tests are flaking?

any test may flake because of it

### Since when has it been flaking?

18 Oct 2024 first seen

### Reason for failure (if possible)

Fatal error: patch port patch-breth0_network.segmentation.4885.blue.blue_ovn-worker2-to-br-int ofport changed from 32 to

**Comment by tssurya** [comment]
maybe this is same as https://github.com/ovn-org/ovn-kubernetes/issues/4769 ? hard to tell but let's keep an eye out
