### ISSUE TITLE
Switch Docker Apt Repository to Support Ubuntu 18.04

### ISSUE THREAD

**Issue by lanoxx** [ovn-org/ovn-kubernetes#493]
The current Ansible playbook does not support Ubuntu 18.04. However, except for a few minor issues, executing the playbook on 18.04 works fine. The main issues I have encountered are related to the installation of the docker engine, since the apt repository location changed from `https://apt.dockerproject.org/repo` to `https://download.docker.com/linux/ubuntu`.

The following adjustments are required:

 1. Package name changed from: `docker-engine` to `docker-ce`.
 2. Repository key file changed from: `https://apt.dockerproject.org/gpg` to `https://download.docker.com/linux/ubuntu/gpg`.
 3. Key changed from `58118E89F3A912897C070ADBF76221572C52609D` to `9DC858229FC7DD38854AE2D88D81803C0EBFCD88`.
 4.  The repository coordinates changed as follows:

         -       deb https://apt.dockerproject.org/repo
         -       {{ ansible_distribution|lower }}-{{ ansible_distribution_release|lower }}
         -       main
         +       deb https://download.docker.com/linux/{{ ansible_distribution|lower }}
         +       {{ ansible_distribution_release|lower }}
         +       stable

5. Update the distribution check in `roles/linux/version_check/tasks/main.yml` to include 18.04.

**Comment by alinbalutoiu** [comment]
If you have time it would be great to submit a pull request for this since you already have the changes, also thanks for testing it out!

**Comment by lanoxx** [comment]
So far I have only verified that this change works on Ubuntu 18.04, it would be good to conduct a few more tests with 14.04 and 16.04 to see that this does not cause a regression, but I currently don't have time (and resources) for that.

**Comment by aserdean** [comment]
@lanoxx please feel free to send out a PR. I can test that for you on 14/16/18.

Thanks,
Alin.

**Comment by lanoxx** [comment]
As I recall this was fixed already.
