### ISSUE TITLE
rename ovn-node container to ovnkube-node

### ISSUE THREAD

**Issue by girishmg** [ovn-org/ovn-kubernetes#523]
The container for the ovnkube in master mode is called ovnkube-master, however the ovnkube in node mode is called ovn-node. I think it should be ovnkube-node. Using this name is not only consistent with how we name the master node but also clearly says that it is nothing to do with the OVN components from openvswitch.org (ovn-controller, ovn-northd, ovn-ctl and so on). It clearly indicates that it is OVN K8s CNI artifact.

**Comment by girishmg** [comment]
@pecameron @dcbw @rajatchopra any comments on this?

**Comment by pecameron** [comment]
@girishmg I picked the name somewhat randomly. ovnkube-node makes sense to me for reasons you articulate.

**Comment by pecameron** [comment]
Included among changes in PR 559
