### ISSUE TITLE
Question about HA

### ISSUE THREAD

**Issue by lihezhong93** [ovn-org/ovn-kubernetes#533]
According to https://github.com/openvswitch/ovn-kubernetes/blob/master/docs/ha.md, the OVN central database can be High-availability. The ovn-kube master should be a daemonset with replica count of 1. Can the master also be high-availability?

I try to set the ovn-kube master with replica cout of 2. There is some errors in container ovn-node. Is this because that the ovn-kube master could not be HA for now?

**Comment by dcbw** [comment]
ovnkube master itself is not currently HA-capable.

**Comment by tssurya** [comment]
This is already fixed, we can run ovnkube-master as 3 replicas.
