### ISSUE TITLE
Questing about central database HA

### ISSUE THREAD

**Issue by ylhyh** [ovn-org/ovn-kubernetes#626]
Can I deploy HA central database instances to other machines instead of Kubernetes Master Nodes?

**Comment by girishmg** [comment]
Not right now. However, I am going to submit a PR soon that will allow you to do what you are asking. See this document for more information:
https://docs.google.com/document/d/1khkgTNvjSEKgOSrzJOTtApL_mai-f3-pW1NHXOv5Dak/edit?usp=sharing

**Comment by ylhyh** [comment]
Thanks @girishmg , that would be great if it can be achived.
Actually I have tried to use external DB but meet errors: #625 . 
And it still get same error even I moved the central database to Kubernetes Master nodes .

**Comment by ylhyh** [comment]
@girishmg, one more question: What is the role of the "--ha" option of ovnkube?
`--ha                              HA option to reconstruct OVN database after failover`
It's required when connect to a HA central database?

**Comment by shettyg** [comment]
@ylhyh Ignore --ha option. It means something else.

**Comment by girishmg** [comment]
is fixed by commit 81a3bdf7566abe57df7, so closing
