### ISSUE TITLE
ovn-daemonset: Address assignment conflict between ovn-master and ovn-node

### ISSUE THREAD

**Issue by alijahnas** [ovn-org/ovn-kubernetes#698]
Let's take: net_cidr=10.128.0.0/16
When launching ovn-daemonset templates from ovn-kubernetes/dist/templates/
ovn-node component creates and assigns the address 10.128.0.2/24 to a local link named k8s-nodename.
But ovn-master also assigns addresses to pods and starts with 10.128.0.2

So you get both a local link and a pod who have the same address and it creates a conflict within the worker nodes.

Logs from ovn-master:
```
$ kubectl -n ovn-kubernetes logs ovnkube-master-58f44d76c4-j4jcs -c ovnkube-master
...
time="2019-05-10T15:40:03Z" level=info msg="Setting annotations ovn={\\\"ip_address\\\":\\\"10.128.1.2/24\\\", \\\"mac_address\\\ ":\\\"0a:00:00:00:00:01\\\", \\\"gateway_ip\\\": \\\"10.128.1.1\\\"} on pod npd-fc8zv"
...
```

Logs from ovn-node:
```
$ kubectl -n ovn-kubernetes logs ovnkube-node-p472v -c ovn-node
...
time="2019-05-10T15:47:00Z" level=debug msg="exec: /usr/sbin/ip addr add 10.128.1.2/24 dev k8s-k8s-cluster"
```

K8s version: v1.11.6
OVN daemonset tag: latest (https://hub.docker.com/r/ovnkube/ovn-daemonset)

**Comment by shettyg** [comment]
@girishmg You had faced something similar correct? And I thought, you had fixed it?

**Comment by alijahnas** [comment]
The thing is I am trying to get ovn-kubernetes as a network backend to OpenStack Magnum.
I tested and adapted it to minikube then a cluster with kubespray. But when I adapted ovn-k8s with a OpenStack Magnum k8s cluster, I had the above problem.

The code is ready to go upstream to Magnum, I just have to get beyond this issue that makes addresses overlap and connectivity between master and minion nodes crash. Thanks.

**Comment by alijahnas** [comment]
By deleting the pod with 10.128.0.2 address, everything comes together and works fine, but in order to get it to OpenStack Magnum, I think I need something that prevents from allocating the 10.128.0.2 address

**Comment by girishmg** [comment]
@shettyg I think there is still a race between the LogicalPort creation for the management port and the LogiicalPort creation for the first pod on that node. I have seen this before, but I kind of forgot about it.

I was thinking of fixing it this way. For every ovn-node's subnet we need to keep aside the 2nd address for the management port (that is set Logical_Switch's exclude_ips to the management port's IP). That way OVN will allocate the subsequent addresses dynamically for the PODs on that node.

Let me send a PR.

**Comment by dcbw** [comment]
@girishmg I'm working on moving management port creation into the master right now, which would fix this too.

**Comment by dcbw** [comment]
@girishmg also if we do the "dynamically allocate join switch ports" thing now that OVN 2.11 is out, that already adds some exclude_ips to the switch and we can just piggy-back on that.

**Comment by girishmg** [comment]
@dcbw seeing your comments now.

> @girishmg also if we do the "dynamically allocate join switch ports" thing now that OVN 2.11 is out, that already adds some exclude_ips to the switch and we can just piggy-back on that.

If I remember it correctly, that exclude_ips was for the Join switch, right? The fix we need is to use exclude_ip for each of the Logical Switch.

> @girishmg I'm working on moving management port creation into the master right now, which would fix this too.

It should fix it if you are creating the logical_switch and the logical_switch_port for the K8s management port in the same transaction, correct?

**Comment by alijahnas** [comment]
@dcbw @girishmg 
When this issue is fixed, is it possible to have updated ovn-daemonset containers so that the integration to OpenStack Magnum gets easier? Thanks!

**Comment by girishmg** [comment]
@alijahnas can you please try the master and let us know if it fixes the issue you are facing. Thanks.

**Comment by girishmg** [comment]
Following commit fixes the issue, so closing this issue.
----8<-----
commit 1e284aeb1d0af34d95bcf9f18f5b0dd7443bf316
Author: Girish Moodalbail <gmoodalbail@nvidia.com>
Date:   Mon May 13 13:06:05 2019 -0700

    race between LogicalPort creation of management port and first pod
----8<--------
