### ISSUE TITLE
Move the egress network policy rules to datapath’s ingress pipeline

### ISSUE THREAD

**Issue by girishmg** [ovn-org/ovn-kubernetes#715]
Today, all the network policy rules are converted to OVN ACL rules with direction set to ‘to-lport’. As a result, the ACL processing occurs on the egress pipeline for the datapath in the ls_out_acl table.  However, for the egress network policy rules we have an opportunity to apply them on the datapath’s ingress pipeline itself. This can be done by using the ‘from-lport’ direction for rules of that type.

Some of the advantages are:
-	You apply rules early in the ingress pipeline itself.
-	It is easier to read the logical flows in OVN SB DB for a given datapath. Right now, all the rules are crowded up there and lot of the rules have same priority: one set for ingress rules and other set for Egress rules.

**Comment by shettyg** [comment]
@girishmg Look at f47d7e0cfc0e41933b5b9b8b538de7eb131c873a on why we did it this way.

**Comment by girishmg** [comment]
@shettyg great. That makes sense, closing the issue.
