### ISSUE TITLE
Service IPs are not working

### ISSUE THREAD

**Issue by lanoxx** [ovn-org/ovn-kubernetes#722]
Since a few days I am experiencing the following error in my cluster. I can ping the overlay both of the management interface and also of my pods. This works from a node itself and also across nodes:

    ping 10.245.0.1 OK
    ping 10.245.0.2 OK
    ping 10.245.0.3 OK
    ping 10.245.1.1 OK
    ping 10.245.1.2 OK
    ping 10.245.1.3 OK

However, none of my service IPs are working. Not even the default kubernetes service on `10.96.0.1`. My CoreDNS pods are all logging the following errors:

    E0610 17:44:36.584904       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
    E0610 17:44:36.585857       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
    E0610 17:44:36.586874       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
    2019-06-10T17:44:43.841Z [INFO] plugin/ready: Still waiting on: "kubernetes"

I can start simple pods, but pods that somehow depend on a service IP such as my CoreDNS service fail:

    root@ip-172-35-44-135:/home/ubuntu# kubectl get pods --all-namespaces
    NAMESPACE     NAME                                READY   STATUS         RESTARTS   AGE
    default       nginx-deployment-7cbc4b6449-5jjg7   1/1     Running        0          6m13s
    kube-system   coredns-5b87c956f-5t2cq             0/1     Running        0          29m
    kube-system   coredns-5b87c956f-84mh4             0/1     Running        0          29m

I have setup, deleted (and setup again) my cluster several times today from scratch and I always end up with this issue. I even left out the windows machines and only tried with Linux nodes. I also tried with several different `ovn-kubernetes versions`, I even tried a built as far back as https://github.com/ovn-org/ovn-kubernetes/commit/37c850c56f11bcdda7c4106dbfa12d8cb0f5eb1f from 24. April.

All my nodes are running Ubuntu 16.04.6.

**Comment by shettyg** [comment]
What version of  running OVS? (`ovs-appctl version`). What is the kernel module version? `cat /sys/module/openvswitch/version`?

**Comment by lanoxx** [comment]
Hi @shettyg, thanks for the quick response. Here are details you requested:

    $ ovs-appctl version
    ovs-vswitchd (Open vSwitch) 2.9.2

There is no version file:

    $ cat /sys/module/openvswitch/version
    cat: /sys/module/openvswitch/version: No such file or directory

But instead a srcversion file:

    $ cat /sys/module/openvswitch/srcversion
    180E9D17CBC499DBBCDC66E

**Comment by shettyg** [comment]
It is likely that you are using a kernel module of openvswitch that does not support NAT (needed for service load-balancing)

**Comment by shettyg** [comment]
o/p of `modinfo openvswitch` ? And `lsmod  | grep openvswitch` ?

**Comment by lanoxx** [comment]
`modinfo openvswitch`:

    filename:       /lib/modules/4.4.0-1084-aws/kernel/net/openvswitch/openvswitch.ko
    license:        GPL
    description:    Open vSwitch switching datapath
    srcversion:     180E9D17CBC499DBBCDC66E
    depends:        nf_conntrack,libcrc32c,nf_defrag_ipv6
    retpoline:      Y
    intree:         Y
    vermagic:       4.4.0-1084-aws SMP mod_unload modversions

`lsmod | grep openvswitch`:

    openvswitch            98304  10 vport_geneve
    nf_defrag_ipv6         20480  1 openvswitch
    nf_conntrack          106496  7 openvswitch,nf_nat,nf_nat_ipv4,xt_conntrack,nf_nat_masquerade_ipv4,nf_conntrack_netlink,nf_conntrack_ipv4
    libcrc32c              16384  2 raid456,openvswitch

**Comment by lanoxx** [comment]
I find it hard to understand why this is suddenly failing. My cluster has been working mostly fine for the last half year with basically the same setup. I am installing the cluster into a set of vanilla Ubuntu 16.04 instances on AWS using the same Ansible scripts that have worked fine just a few weeks ago.

Are you aware of any Ubuntu 16.04.x security patches that might have caused this?

**Comment by shettyg** [comment]
`dmesg | grep -i "open vswitch" `?

Also look at /var/log/openvswitch/ovs-vswitchd.log to see any errors around NAT.

**Comment by shettyg** [comment]
Were you installing openvswitch dkms kernel module package before? Or was it always upstream openvswitch kernel module?

**Comment by lanoxx** [comment]
I have always used the upstream module which gets automatically installed by the ovn-kubernetes provided ansible scripts.

`dmesg | grep -i "open vswitch"` gives an empty result.

Here are the last couple of lines from the ovs-vswitchd.log: https://gist.github.com/lanoxx/c91a8600ca87347f5e939d062b650a8b

**Comment by lanoxx** [comment]
I am seeing a lot of these in the journal:

    Jun 10 20:15:40 ip-172-35-37-249 kernel: netlink: Unknown conntrack attr (type=6, max=5)
    Jun 10 20:15:40 ip-172-35-37-249 kernel: netlink: Unknown conntrack attr (type=6, max=5)
    Jun 10 20:15:40 ip-172-35-37-249 kernel: openvswitch: netlink: Flow actions may not be safe on all matching packets.
    Jun 10 20:15:40 ip-172-35-37-249 kernel: netlink: Unknown conntrack attr (type=6, max=5)
    Jun 10 20:15:40 ip-172-35-37-249 kernel: netlink: Unknown conntrack attr (type=6, max=5)
    Jun 10 20:15:40 ip-172-35-37-249 kernel: openvswitch: netlink: Flow actions may not be safe on all matching packets.
    Jun 10 20:15:40 ip-172-35-37-249 kernel: netlink: Unknown conntrack attr (type=6, max=5)

**Comment by shettyg** [comment]
>Here are the last couple of lines from the ovs-vswitchd.log: >https://gist.github.com/lanoxx/c91a8600ca87347f5e939d062b650a8b

>2019-06-10T17:00:24.213Z|00033|ofproto_dpif|WARN|Rejecting ct action because datapath does not support nat (your kernel module may be out of date)

From the above, it is clear that the kernel module does not support NAT.

**Comment by lanoxx** [comment]
Thanks for spotting that.

As I understand it the Ansible scripts download openvswitch version 2.9.x from the web, then build Debian packages from that and then install those Debian packages. How could they suddenly not support NAT?

**Comment by shettyg** [comment]
Does ansible script try to install dkms package for openvswitch? If so, it is possible that it tried to install it, but it failed to compile for the latest kernel that Ubuntu is providing. 

If that is the case, you should try the tip of openvswitch's branch-2.9. If that still fails, you should move to tip of 2.10 or tip of 2.11.

**Comment by lanoxx** [comment]
Are you talking about [the openvswitch-datapath-dkms package](https://github.com/ovn-org/ovn-kubernetes/blob/master/contrib/roles/linux/openvswitch/tasks/build_install_release_ovs.yml#L45)?

I don't see any compile errors during the execution of Ansible, its possible that there is an error but its silently ignored and I never see it.

This morning I tried to setup a new cluster which uses OVS 2.10.2 but that gave me lots of MTU errors and the overlay network was not even starting, so I abandoned the cluster again. Currently I am trying with OVS 2.9.2 again, but using Ubuntu 16.04 instances with  a patch level from around March. It seems the NAT errors are now gone. In `/var/log/openvswitch/ovs-vswitchd.log` I only see one ocurense of `nat` which is in the following line:

    2019-06-11T08:51:54.017Z|00021|ofproto_dpif|INFO|system@ovs-system: Datapath supports ct_state_nat

Nevertheless, my CoreDNS pods are still not starting. The errors I see in the CoreDNS log are now slightly different. I did not see the `read upd` timeout before.

    2019-06-11T09:17:45.788Z [ERROR] plugin/errors: 2 1666176440527830169.6100255984154774042. HINFO: read udp 10.245.0.2:46171->172.35.0.2:53: i/o timeout
    E0611 09:17:47.785223       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
    E0611 09:17:47.785963       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
    E0611 09:17:47.786107       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
    2019-06-11T09:17:48.788Z [ERROR] plugin/errors: 2 1666176440527830169.6100255984154774042. HINFO: read udp 10.245.0.2:48627->172.35.0.2:53: i/o timeout

**Comment by lanoxx** [comment]
I have reverted to Ubuntu 16.04 with patch level from 20190320 and I also reverted to the following ovn commit: 378afe237ff8e9877714ee664cee2fdcb5bbfc58 and now my CoreDNS pods are running again, in the morning I was trying with commit: 37c850c56f11bcdda7c4106dbfa12d8cb0f5eb1f which was still giving me errors (see previous comment).

**Comment by lanoxx** [comment]
I managed to setup a new cluster today using the latest version of ovn-kubernetes and I am not longer seeing this issue. I would like to point out though, that upgrading the ovs version from 2.9 to 2.10 fails with the ansible scripts because the kernel modules cannot be unloaded. I had to reset the Linux nodes and start with new nodes to get a working installation.
