### ISSUE TITLE
race condition in pkg/cluster/node_test.go

### ISSUE THREAD

**Issue by danwinship** [ovn-org/ovn-kubernetes#743]
There is a race condition in pkg/cluster/node_test.go that sometimes causes the `It("test watchConfigEndpoints single IP"` test to fail because the `watchConfigEndpoints` add handler gets run twice, and so makes an extra set of calls to `ovs-vsctl` that the `FakeExec` was not expecting.

This happens because `WatchFactory.addHandler` assumes that it needs to:

	// Send existing items to the handler's add function; informers usually
	// do this but since we share informers, it's long-since happened so
	// we must emulate that here
	for _, obj := range existingItems {
		inf.handlers[handlerID].OnAdd(obj)
	}

but the logic is wrong: in some cases, both this code (first) and the informer's own code (second) will get run for the same object.

**Comment by dcbw** [comment]
@danwinship would it work to figure out if this is the first handler being attached, and then suppress this behavior, but only for the first one?

**Comment by dcbw** [comment]
For the record, here's what the SharedInformer does:

```
func (s *sharedIndexInformer) AddEventHandlerWithResyncPeriod(handler ResourceEventHandler, resyncPeriod time.Duration) {
        <snip>

	listener := newProcessListener(handler, resyncPeriod, determineResyncPeriod(resyncPeriod, s.resyncCheckPeriod), s.clock.Now(), initialBufferSize)

	if !s.started {
		s.processor.addListener(listener)
		return
	}

	// in order to safely join, we have to
	// 1. stop sending add/update/delete notifications
	// 2. do a list against the store
	// 3. send synthetic "Add" events to the new handler
	// 4. unblock
	s.blockDeltas.Lock()
	defer s.blockDeltas.Unlock()

	s.processor.addListener(listener)
	for _, item := range s.indexer.List() {
		listener.add(addNotification{newObj: item})
	}
}
```

So there's the possibility of a race if a handler gets attached to the Factory too quickly after the factory object is created, where it might catch some/all of the synthetic adds depending on when the SharedInformer's internal listener actually starts (which is dependent on goroutines).
