### ISSUE TITLE
need help for node to svc clusterIP and external IP

### ISSUE THREAD

**Issue by jasonqiann** [ovn-org/ovn-kubernetes#770]
Hi, 
i modify the logical net framework as the pod and node are in one underlay network.
node's addresses and pod's addresses are in 10.250.0.0/21.

all pod are in one logical switch(k8s), and i create two load balancers(TCP&UDP), then i added the two load balancers on logical switch k8s.

i added rules like: svcIPs:svcPort=pod1'sIP:port,pod2'sIP:port，so i can visit svcIP:svcPort normally from pod. but it not work when i visit svcIP:svcPort from the k8s node.

how to config to achieve my goal which can visit svcIP:svcPort from node.

thanks.

**Comment by jasonqiann** [comment]
i create one lsp for every node, like below:
`# ovn-nbctl show
switch 4dc736b4-9d53-442f-b2d7-7bf40477c26d (k8s)
    port node-kubemaster01
        addresses: ["dynamic"]
    port default_test-app-7675d84794-d6kh5
        addresses: ["dynamic"]
    port default_tomcat-7bf9c54fd7-d7h9t
        addresses: ["dynamic"]
    port public
        type: localnet
        addresses: ["unknown"]
    port node-kubemaster02
        addresses: ["dynamic"]
    port node-kubemaster03
        addresses: ["dynamic"]
    port node-kubeworker01
        addresses: ["dynamic"]`

for each node, i create ovs port on br-int:
`# ovs-vsctl list interface ovn0
_uuid               : b2ec4a22-fdcf-42af-b535-3c67ee2cb2ad
admin_state         : up
bfd                 : {}
bfd_status          : {}
cfm_fault           : []
cfm_fault_status    : []
cfm_flap_count      : []
cfm_health          : []
cfm_mpid            : []
cfm_remote_mpids    : []
cfm_remote_opstate  : []
duplex              : []
error               : []
external_ids        : {iface-id="node-kubemaster02"}
ifindex             : 35
ingress_policing_burst: 0
ingress_policing_rate: 0
lacp_current        : []
link_resets         : 3
link_speed          : []
link_state          : up
lldp                : {}
mac                 : []
mac_in_use          : "7e:33:bc:fa:00:04"
mtu                 : 1500
mtu_request         : []
name                : "ovn0"
ofport              : 22
ofport_request      : []
options             : {}
other_config        : {}
statistics          : {collisions=0, rx_bytes=2022, rx_crc_err=0, rx_dropped=0, rx_errors=0, rx_frame_err=0, rx_over_err=0, rx_packets=36, tx_bytes=7056, tx_dropped=0, tx_errors=0, tx_packets=168}
status              : {driver_name=openvswitch}
type                : internal`

and added route to svc from ovn0's ip:
"# route 
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         10.250.7.254    0.0.0.0         UG    0      0        0 br0
10.250.0.0      0.0.0.0         255.255.248.0   U     0      0        0 br0
10.250.0.0      0.0.0.0         255.255.248.0   U     0      0        0 ovn0
link-local      0.0.0.0         255.255.0.0     U     1009   0        0 em4
link-local      0.0.0.0         255.255.0.0     U     1025   0        0 br0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
**192.156.0.0     10.250.0.3      255.255.0.0     UG    0      0        0 ovn0**
192.168.122.0   0.0.0.0         255.255.255.0   U     0      0        0 virbr0"

above 10.250.0.3 is ovn0's ip.

my load balancer is :
`# ovn-nbctl list load
_uuid               : e6a26429-988c-4395-b947-e121c530aa30
external_ids        : {}
name                : cluster-tcp-loadbalancer
protocol            : tcp
vips                : {"192.156.0.1:443"="10.250.7.11:6443,10.250.7.12:6443,10.250.7.13:6443", "192.156.15.231:80"="10.250.0.8:8080"}`

when i visit 192.156.15.231:80, i get no route to host or connection timeout.

any one can tell me how to config it?

**Comment by tssurya** [comment]
> odify the logical net framework as the pod and node are in one underlay network.
> node's addresses and pod's addresses are in 10.250.0.0/21.

I don't think its supported in k8s to have nodeCIDR and podCIDR as part of the same range?
Closing this issue as its too old and if you are running into this issue still please feel free to reopen.
