### ISSUE TITLE
NodePort routing broken

### ISSUE THREAD

**Issue by lanoxx** [ovn-org/ovn-kubernetes#781]
I have setup a new cluster this week and I had problems with NodePorts again. I have seen this problem multiple times already and so far I have not found a deterministic pattern on when or why it occurs. It affects both Linux and Windows nodes. My new cluster currently consists of five nodes: 1 master (which is also a minion), 2 Linux worker nodes and 2 windows worker nodes. Currently the node port problem occurs on two of the Linux nodes. On another cluster that I have setup before, on 4 out of 5 nodes the NodePorts were broken. I tried to remove a broken node from the cluster and replace it by a new node, but then the new node also has problems with the NodePorts.

Here is an example. I have deployed a simple nginx pod into the cluster and exported port `80` of the pod as a service of type `NodePort`. Here is the output of `kubectl get svc -o wide`:

    nginx           NodePort    10.96.0.185   <none>        80:30993/TCP   9s     app=nginx

Lets check on which node the nginx pod runs:

    nginx-deployment-695599979b-q5kvn   1/1     Running   0          40m   10.245.5.3   ip-172-35-61-250.eu-central-1.compute.internal   <none>
    nginx-deployment-695599979b-xz7nw   1/1     Running   0          40m   10.245.5.6   ip-172-35-61-250.eu-central-1.compute.internal   <none>

I use the following script to connect to the node port of each node:

    for ip in 172.35.32.224 172.35.44.145 172.35.57.20 172.35.60.189 172.35.61.250; do echo -n "$ip: "; NO_PROXY=$ip curl -s --connect-timeout 10 --max-time 10 http://$ip:30993 | head -n 4 | tail -n 1; done;
    172.35.32.224: <title>Welcome to nginx!</title>
    172.35.44.145: <title>Welcome to nginx!</title>
    172.35.57.20: <title>Welcome to nginx!</title>
    172.35.60.189:
    172.35.61.250:

For the last two nodes in the list the request just times out. When I connect to one of the nodes (say 172.35.60.189) and try to access the service via its service IP, then the connection works:

    root@ip-172-35-60-189:/home/ubuntu# curl -s 10.96.0.185:80 | head -n 4 | tail -n 1
    <title>Welcome to nginx!</title>

Ok, now I tried to check with various ovn/ovs tools that I know of:

    ovn-nbctl lb-list (on the master):

    UUID                                    LB                  PROTO      VIP                    IPs
    b28395a7-bb42-4245-b80d-99222643e729                        tcp        172.35.60.189:30677    10.245.2.7:9000
                                                                tcp        172.35.60.189:30993    10.245.5.3:80,10.245.5.6:80
                                                                tcp        172.35.60.189:31330    10.245.2.5:443
                                                                tcp        172.35.60.189:32275    10.245.2.5:80
                                                                tcp        172.35.60.189:32565    10.245.3.3:80,10.245.3.4:80
    f0c0072e-41f6-4f9d-8e56-7f25891416a1                        tcp        10.96.0.100:443        10.245.2.7:9000
                                                                tcp        10.96.0.10:53          10.245.0.3:53,10.245.0.4:53
                                                                tcp        10.96.0.10:9153        10.245.0.3:9153,10.245.0.4:9153
                                                                tcp        10.96.0.151:443        10.245.2.3:6443
                                                                tcp        10.96.0.152:80         10.245.3.3:80,10.245.3.4:80
                                                                tcp        10.96.0.180:44134      10.245.0.6:44134
                                                                tcp        10.96.0.182:443        10.245.2.5:443
                                                                tcp        10.96.0.182:80         10.245.2.5:80
                                                                tcp        10.96.0.185:80         10.245.5.3:80,10.245.5.6:80
                                                                tcp        10.96.0.1:443          172.35.60.189:443
                                                                tcp        10.96.0.23:80          10.245.0.5:8080
                                                                tcp        10.96.0.8:443          10.245.2.6:8443
    8210d1ad-a84e-4fd7-aadc-7cff01b99b05                        tcp        172.35.44.145:30677    10.245.2.7:9000
                                                                tcp        172.35.44.145:30993    10.245.5.3:80,10.245.5.6:80
                                                                tcp        172.35.44.145:31330    10.245.2.5:443
                                                                tcp        172.35.44.145:32275    10.245.2.5:80
                                                                tcp        172.35.44.145:32565    10.245.3.3:80,10.245.3.4:80
    7be6cb14-15c9-417d-97ff-0cf967d143fd                        tcp        172.35.57.20:30677     10.245.2.7:9000
                                                                tcp        172.35.57.20:30993     10.245.5.3:80,10.245.5.6:80
                                                                tcp        172.35.57.20:31330     10.245.2.5:443
                                                                tcp        172.35.57.20:32275     10.245.2.5:80
                                                                tcp        172.35.57.20:32565     10.245.3.3:80,10.245.3.4:80
    c4d89494-b206-4c65-b561-0c2f7aaf8ea4                        udp        10.96.0.10:53          10.245.0.3:53,10.245.0.4:53
    4aef1fd1-053f-416b-92b0-a3f4837dec12                        tcp        172.35.61.250:30677    10.245.2.7:9000
                                                                tcp        172.35.61.250:30993    10.245.5.3:80,10.245.5.6:80
                                                                tcp        172.35.61.250:31330    10.245.2.5:443
                                                                tcp        172.35.61.250:32275    10.245.2.5:80
                                                                tcp        172.35.61.250:32565    10.245.3.3:80,10.245.3.4:80
    f19e4cd2-4ca6-4175-a898-a88c5b748a0c                        tcp        172.35.32.224:30677    10.245.2.7:9000
                                                                tcp        172.35.32.224:30993    10.245.5.3:80,10.245.5.6:80
                                                                tcp        172.35.32.224:31330    10.245.2.5:443
                                                                tcp        172.35.32.224:32275    10.245.2.5:80
                                                                tcp        172.35.32.224:32565    10.245.3.3:80,10.245.3.4:80

As far as I can tell, the nodeports are properly showing up there.

When I look at the nginx logs I see the incoming HTTP request, but the response never reaches my curl process. It seems the traffic is then just lost somewhere in the overlay network. Here is an example from the nginx log:

    100.64.0.5 - - [30/Jul/2019:15:56:34 +0000] "GET / HTTP/1.1" 200 612 "-" "curl/7.64.0" "-"
    100.64.0.4 - - [30/Jul/2019:15:57:55 +0000] "GET / HTTP/1.1" 200 612 "-" "curl/7.64.0" "-"

The log entry originating from 100.64.0.5 corresponds to an HTTP request that I have sent to 172.35.61.250:30993.

The log entry originating from 100.64.0.4 corresponds to an HTTP request that I have sent to 172.35.32.224:30993.

I am not sure what else I can check to debug this. Is there a way that I can resolve this manually using the ovn/ovs tools?

P.S: Related issues might be #636 #611

**Comment by lanoxx** [comment]
@girishmg Do you have any idea how to debug this?

**Comment by tssurya** [comment]
This is definitely fixed currently in the recent branch, please retry and reopen if the issue persists on the latest version, closing this issue as its too stale.
