### ISSUE TITLE
ovn-kubernetes doesn't implement service SessionAffinity

### ISSUE THREAD

**Issue by danwinship** [ovn-org/ovn-kubernetes#819]
From https://kubernetes.io/docs/concepts/services-networking/service/:

> If you want to make sure that connections from a particular client are passed to the same Pod each time, you can select the session affinity based the on client’s IP addresses by setting `service.spec.sessionAffinity` to “ClientIP” (the default is “None”). You can also set the maximum session sticky time by setting `service.spec.sessionAffinityConfig.clientIP.timeoutSeconds` appropriately. (the default value is 10800, which works out to be 3 hours).

ovn-kubernetes does not implement this, causing a handful of k8s e2e tests to fail.

**Comment by danwinship** [comment]
(I will probably look at implementing this soon)

**Comment by danwinship** [comment]
We've determined that this requires some work in OVN... looking into it

**Comment by ivan1221** [comment]
I'm interested in this feature, are you working on it?

**Comment by aojea** [comment]
No, I'm not, feel free to try

**Comment by tssurya** [comment]
closing this issue as this is fixed.
