### ISSUE TITLE
Need additional service/loadbalancer rules for some clouds

### ISSUE THREAD

**Issue by danwinship** [ovn-org/ovn-kubernetes#831]
Certain CloudProviders assume that they can redirect loadbalancer traffic directly to a node with no rewriting, and the node will accept the packets.

That is, if you have a LoadBalancer service with an ingress IP of 1.2.3.4 and a service port of 443 and a NodePort of 31000, and it's available on a node with node IP 5.6.7.8, then:

- on AWS, the user will connect to to the cloud load balancer at `1.2.3.4:443`, and the load balancer will NAT the connection, and the node will receive a connection at `5.6.7.8:31000`, which ovn-kubernetes will have set up an OVN loadbalancer for.
- on Azure, the user will connect to to the cloud load balancer at `1.2.3.4:443`, and the load balancer will simply forward the packets directly to the node, which will receive a connection for `1.2.3.4:443`. [kube-proxy copes with this](https://github.com/kubernetes/kubernetes/blob/v1.16.0-rc.1/pkg/proxy/iptables/proxier.go#L991), but ovn-kubernetes doesn't currently.

For local gateway mode, it's easy enough to make this work by adding iptables rules pointing from the `ingress-ip:service-port` combo to the OVN load balancer. Is that also the right fix for other modes? Or would we need to create additional load balancers for the new IP/port?

**Comment by girishmg** [comment]
>     * on Azure, the user will connect to to the cloud load balancer at `1.2.3.4:443`, and the load balancer will simply forward the packets directly to the node, which will receive a connection for `1.2.3.4:443`. [kube-proxy copes with this](https://github.com/kubernetes/kubernetes/blob/v1.16.0-rc.1/pkg/proxy/iptables/proxier.go#L991), but ovn-kubernetes doesn't currently.

Even if we did that the response packets will take a different path out, and I don't know if that will work. (In the response packets, the source IP will be that of the internet gateway IP (SNAT'ed) and will not be the LB IP, so not sure how the clients will work). Is this the case of stateless LB? Curious to know the use case here?

**Comment by danwinship** [comment]
> Even if we did that the response packets will take a different path out, and I don't know if that will work

OK, so maybe instead of just DNATting the packets (which is what I did for local gateway mode), we need the node iptables rules to fully masquerade them. Then the response from the ovn load balancer will come back to the node, which can unmasquerade it and return it to the cloud load balancer.

> Is this the case of stateless LB? Curious to know the use case here?

I guess given a network plugin and proxy where the traffic paths work right, this would let the destination pod see the origin client source IP? The node would get a `client-ip:source-port → ingress-ip:service-port` connection, which it would DNAT to `client-ip:source-port → pod-ip:pod-port`, the pod would process that and send a response `pod-ip:pod-port → client-ip:source-port` but the network plugin's routing setup would ensure that that packet passed through the node again, which would then be able to un-DNAT it back to `ingress-ip:service-port → client-ip:source-port` and then send it directly back to the original client directly without passing through the load balancer again.

I don't know if there are any other reasons; AFAICT this isn't a behavior we configured, it's just how the kubernetes CloudProvider for Azure works by default.

**Comment by girishmg** [comment]
> I guess given a network plugin and proxy where the traffic paths work right, this would let the destination pod see the origin client source IP? The node would get a `client-ip:source-port → ingress-ip:service-port` connection, which it would DNAT to `client-ip:source-port → pod-ip:pod-port`, the pod would process that and send a response `pod-ip:pod-port → client-ip:source-port` but the network plugin's routing setup would ensure that that packet passed through the node again, which would then be able to un-DNAT it back to `ingress-ip:service-port → client-ip:source-port` and then send it directly back to the original client directly without passing through the load balancer again.

Thanks.

**Comment by girishmg** [comment]
> > Even if we did that the response packets will take a different path out, and I don't know if that will work
> 
> OK, so maybe instead of just DNATting the packets (which is what I did for local gateway mode), we need the node iptables rules to fully masquerade them. Then the response from the ovn load balancer will come back to the node, which can unmasquerade it and return it to the cloud load balancer.
> 
> > Is this the case of stateless LB? Curious to know the use case here?
> 
> I guess given a network plugin and proxy where the traffic paths work right, this would let the destination pod see the origin client source IP? The node would get a `client-ip:source-port → ingress-ip:service-port` connection, which it would DNAT to `client-ip:source-port → pod-ip:pod-port`, the pod would process that and send a response `pod-ip:pod-port → client-ip:source-port` but the network plugin's routing setup would ensure that that packet passed through the node again, which would then be able to un-DNAT it back to `ingress-ip:service-port → client-ip:source-port` and then send it directly back to the original client directly without passing through the load balancer again.
> 
> I don't know if there are any other reasons; AFAICT this isn't a behavior we configured, it's just how the kubernetes CloudProvider for Azure works by default.

if you masquerade, then the application running in the POD wouldn't know the original Client IP from where the packets originated.

**Comment by danwinship** [comment]
Right, but that's not guaranteed to work anyway. (It doesn't work with AWS, etc.)
