### ISSUE TITLE
move all OVN K8s related node/pod annotations under k8s.ovn.org namespace

### ISSUE THREAD

**Issue by girishmg** [ovn-org/ovn-kubernetes#849]
Currently, we annotate nodes and pods without any namespace. To keep it clean and consistent with various K8s components, move all the OVN K8s annotations under k8s.v1.ovn.org.

For example:
node's annotations of ovn_host_subnet -> k8s.v1.ovn.org/host-subnet
pod's annotation of ovn -> k8s.v1.ovn.org/pod-network(?)

**Comment by danwinship** [comment]
The "v1" seems contrary to upstream style; kubernetes tends to label "alpha" and "beta" annotations as such, but stable annotations don't have any version indication.

And the "k8s" part seems unnecessary too. (What would be the difference between "ovn.org/host-subnet" and "k8s.ovn.org/host-subnet"? Nothing else at ovn.org is likely to be apply annotations to kubernetes objects...)

But definitely +1 to "ovn.org/" at least

**Comment by girishmg** [comment]
@danwinship I agree with the version part, we can drop it.

W.r.t to "k8s" part the initial thinking was to capture the project under which "ovn" is being used since "ovn.org" seemed to be very broad. How about cni.ovn.org?

**Comment by danwinship** [comment]
If you want to indicate sub-project, I like "k8s" better than "cni".

Although we could also just go with "ovn-kubernetes". It's not like people will have to type the whole thing over and over anyway; we'll define `const HostSubnetAnnotation = "ovn-kubernetes.ovn.org/host-subnet"` and then people will just use the constant.

**Comment by girishmg** [comment]
Well `ovn` in `ovn-kubernetes` is already implied by `ovn.org`. So, can we settle down for either `kubernetes.ovn.org` or `k8s.ovn.org`.

@dcbw any thoughs?

**Comment by girishmg** [comment]
FWIW, Calico uses `cni.projectcalico.org`: https://docs.projectcalico.org/v3.7/reference/cni-plugin/configuration

**Comment by dcbw** [comment]
@girishmg @danwinship `k8s.ovn.org` is good with me

**Comment by girishmg** [comment]
this is fixed through c5d605df07e5851d7abef4362d486a1262e071c1
