### ISSUE TITLE
remove support for spare interface gateway mode

### ISSUE THREAD

**Issue by girishmg** [ovn-org/ovn-kubernetes#850]
The spare interface gateway mode allows one to take a spare interface on the node and attach the interface directly to `br-int`. When you do that, all the North-South traffic from the Pod will exit out through the spare interface.

However, the issue with this mode is that the NodePort services aren't supported (and therefore LoadBalancer type services). The following diagram captures the issue well.

```
 +-----------------------------+
 |                             |
 |                             |
 |	      +-------------+  |
 |  +-------+ |  br-int     |  |
 |  |K8s    | +-----+-------+  |
 |  |NodeIP |    (NodeIP2)     |
 |  +---+---+       |          |
 |      |           |          |
 |  +---+---+   +---+----+     |
 +--+ eth0  +---+  eth1  +-----+
    +-------+   +---+----+
```

As you can see, the packets for NodePort services arrive on eth0. However, there is no path for them to enter the OVN pipeline. You can't use IPtable rules on the node to forward those packets through the management port since they should be entering OVN pipeline from L3 gateway.

This is a severe drawback with this mode, and we know that no one in the community is using this mode. So, we should just remove this mode to facilitate some of the upcoming PRs (annotate node with L3 gateway information and move gateway creations to master node). 

@dcbw @shettyg @danwinship Any comments?

**Comment by danwinship** [comment]
> Any comments?

"Yay!"

**Comment by girishmg** [comment]
Fixed by https://github.com/ovn-org/ovn-kubernetes/pull/852
