### ISSUE TITLE
Ovn-controller can't start on the k8s minion(node)

### ISSUE THREAD

**Issue by TrevorTaoARM** [ovn-org/ovn-kubernetes#858]
Did anybody met the case that ovn-controller can't start well on the k8s minion node which stops at the "wait_for_event process_ready" , the output of the ovn-controller container of the pod ovnkube-node shows the following logs:

`linux@nfv-demo01:~$ docker logs af94fbed45c3
================== ovnkube.sh --- version: 3 ================
 ==================== command: ovn-node
 =================== hostname: nfv-demo01
 =================== daemonset version 3
 =================== Image built from ovn-kubernetes ref: refs/heads/master  commit: 7a5263b9dc78974e520f5685b05b6712dfb753bf
=============== ovn-node - (wait for ovs)
=============== ovn-node - (wait for ready_to_start_node)
ovn_nbdb tcp://10.169.41.173:6641   ovn_sbdb tcp://10.169.41.173:6642  ovn_nbdb_test tcp:10.169.41.173:6641
=============== ovn-node - (ovn-node  wait for ovn-controller.pid)
info: Waiting for process_ready ovn-controller to come up, waiting 1s ...
linux@nfv-demo01:~$ docker logs 4ecf525a0e73
================== ovnkube.sh --- version: 3 ================
 ==================== command: ovn-controller
 =================== hostname: nfv-demo01
 =================== daemonset version 3
 =================== Image built from ovn-kubernetes ref: refs/heads/master  commit: 7a5263b9dc78974e520f5685b05b6712dfb753bf
=============== ovn-controller - (wait for ovs)
info: Waiting for ovs_ready  to come up, waiting 1s ...
ovs_ready  came up in 1 5 sec tries
=============== ovn-controller - (wait for ready_to_start_node)
ovn_nbdb tcp://10.169.41.173:6641   ovn_sbdb tcp://10.169.41.173:6642
ovn_nbdb_test tcp:10.169.41.173:6641
=============== ovn-controller  start_controller
2019-10-11T10:38:35Z|00001|vlog|INFO|opened log file /var/log/openvswitch/ovn-controller.log
Starting ovn-controller.
run as: /usr/share/openvswitch/scripts/ovn-ctl --no-monitor start_controller --ovn-controller-log=-vconsole:info
`
But the ovn-controller works well on the k8s master node.

**Comment by girishmg** [comment]
@TrevorTaoARM this could be related to this issue https://github.com/ovn-org/ovn-kubernetes/issues/855

**Comment by TrevorTaoARM** [comment]
It's ok now. Close it. Thanks.
