### ISSUE TITLE
Localnet gateway br-nexthop needs to be resynced on node reboot

### ISSUE THREAD

**Issue by dcbw** [ovn-org/ovn-kubernetes#946]
The MAC address of br-nexthop always changed after node reboot. However, when pod try to communicate with the node IP, the GR router of OVN keeps using the old MAC address of br-nexthop as the dst_mac. And it doesn’t work.  The only way I can make it work is to ping 169.254.33.2 on the node.  I guess it updates the ARP table of GR router.

**Comment by girishmg** [comment]
@dcbw the OVN SB DB has MAC_binding table that captures all the MAC addresses learnt. Looks like it had the old binding entry and that was used as destination MAC.

I am not sure why node reboot is causing the br-nexthop's MAC address to change. That shouldn't happen since that OVS port is persisted and upon reboot it should get back its persisted value.

**Comment by pliurh** [comment]
Actually, this issue happened in my environment.

@girishmg You're right. The sbdb MAC_binding table is not up-to-date. The new mac of br-nexthop is `d2:d6:a8:b2:31:f6`.

```
_uuid               : 44af303d-07f3-4529-b163-bc36b0621dfc
datapath            : bc74e40d-8b8d-4f0c-a253-fbf8d7ee4d2d
ip                  : "169.254.33.1"
logical_port        : "rtoe-GR_worker-0"
mac                 : "c2:a7:b9:0d:30:35"
```

In the `ovs-vswitchd.log` I can see the br-nexthop was recreated after reboot.
https://pastebin.com/vik7ycRy
And here is the `ovsdb-server.log`
https://pastebin.com/L7tvreaL

**Comment by girishmg** [comment]
Ok the internal ports are getting re-created on reboot and therefore the MAC address changes.

BTW, the node management port also has the same issue, however we annotate the node with the new MAC address and it gets picked up by the master and the corresponding logical switch port gets updated with the new MAC.

For the br-nexthop case, perhaps we should just delete the corresponding MAC binding from the OVN SB DB? This is easy to do. However, we would like for the deletion to occur on the master and not on the node.

**Comment by shettyg** [comment]
When we create the br-nexthop, we can take the created mac and then set it as static in OVSDB. That will make sure that it will remain the same across reboots (unless we are deleting it or the OVS database is destroyed when container runnign OVS is destroyed).

**Comment by girishmg** [comment]
@shettyg by saving the `mac` address in the interface's record works. I am going to submit a PR for this. If the container running OVS is destroyed, the database still exists on the host, so we are good there.

**Comment by dcbw** [comment]
@girishmg the issue is that after node reboot, we'll create a completely new br-nexthop and br-local and they'll have different MACs. But the node *should* post the new MACs to the annotations, and that *should* be picked up by the master and stuffed into the NBDB, and then northd will sync to the SBDB, and so on. Right?

**Comment by girishmg** [comment]
@dcbw `br-nexhop` is not part of the OVN logical topology. It is an interface on the host. You can think of it as a physical interface. This interface is added back upon rebooted. Since the `mac` information was not persisted when it was created we will get random MAC address on reboot.

PR #949 fixes this issue.

**Comment by girishmg** [comment]
@dcbw for `br-local` we have already taken care of persisting the MAC by setting `other_config:hwaddr` in the bridge table
