### ISSUE TITLE
OVN Kubernetes logical topology doesn't scale with larger number of k8s nodes

### ISSUE THREAD

**Issue by girishmg** [ovn-org/ovn-kubernetes#990]
In the logical topology we have, the `join` logical switch connects all the L3 gateways together on a single L2 broadcast domain. So, with 622 k8s nodes the join logical switch connects 622 L3 gateways and 1 distributed gateway router  (ovn_cluster_router). This ends up in creation of hundreds of thousands of logical flow entries in OVN SB’s lr_in_arp_resolve table across all of the 623 gateway routers. 

```
 +-------------------+   +-------------------+  +-------------------+
 |Node1              |   |Node2              |  |Node3              |
 | .---.             |   | .---.             |  | .---.             |
 |(l3GW )            |   |(l3GW )            |  |(l3GW )            |
 | `-+-'             |   | `-+-'             |  | `-+-'             |
 +---+---------------+   +---+---------------+  +---+---------------+
     |                       |                      |                
     |                       |                      |                
+----+-----------------------+----------------------+--------------+ 
|                       Join (100.64.0.0/16)                       | 
+----------------------------+-------------------------------------+ 
                             |                                       
  .--------------------------+------------------------------------.  
 (                       ovn_cluster_router                        ) 
  `--------+------------------+---------------------------+-------'  
           |                  |                           |          
           |                  |                           |          
         +-+-+              +-+-+                       +-+-+        
         |LS1|              |LS2|                       |LS3|        
         +---+              +---+                       +---+         
```

Every L3 gateway router has ARP resolve entries in lr_in_arp_resolve table for 622 other router’s IP address. So, this results in 622 * 622 entries. Which is 386K entries. Add in IPv6 entries, then it will be 772K entries. 

If you now consider the shared gateway mode, then we have two L3 gateways per node and therefore the ports on the `join` logical switch doubles. So, we will have 622 * 2 + 1 (1245) ports on the logical switch. The number of flows in this case will be: 1,550,025 (1.5M+) flows. If we add
IPv6, then it is close to 3M+ flows.
```
$ grep -c 'lr_in_arp_resolve.*rtoj-GR_nd-sjc3' lf.list 
1541322
$ grep -c 'lr_in_arp_resolve.*rtoj-GR_local' lf.list 
1538840
```

Both ovn-northd and ovsdb-server NB daemon is super busy processing these flow entries (cursory ltrace says it’s all in string operations) . The cpu and memory print of these daemons are extremely high. All the client (ovn-{nb|sb}ctl) operations to these daemons are timing out.

**Solution**

The solution is to remove the single join logical switch and instead, introduce a join logical switch per-node.
NOTE:   we cannot directly peer each L3 gateway router to the ovn_cluster_router as it is not allowed. From, ovn-nb(5) manpage, we have:

              The Gateway router can only be connected to a distributed router
              via a switch if SNAT and DNAT are to be configured in the  Gate‐
              way router.

The following diagram depicts such a topology.

```
+-------------------+   +-------------------+  +-------------------+
|Node1              |   |Node2              |  |NodeN              |
| .---.             |   | .---.             |  | .---.             |
|(l3GW )            |   |(l3GW )            |  |(l3GW )            |
| `-+-'             |   | `-+-'             |  | `-+-'             |
+---+---------------+   +---+---------------+  +---+---------------+
    |                       |                      |                
    |                       |                      |                
 +--+-------------+     +---+------------+      +--+--------------+ 
 | join-node1 .   |     | join-node2 .   |      |  join-node3 .   | 
 | 100.64.0.0/30  |     | 100.64.0.4/30  |      |  100.64.0.8/30  | 
 +--+-------------+     +---+------------+      +--+--------------+ 
    |                       |                      |                
 .--+-----------------------+----------------------+-------------.  
(                       ovn_cluster_router                        ) 
 `--------+------------------+---------------------------+-------'  
          |                  |                           |          
          |                  |                           |          
        +-+-+              +-+-+                       +-+-+        
        |LS1|              |LS2|                       |LS3|        
        +---+              +---+                       +---+               
```
There is no more large L2 broadcast domain. Each L3 Gateway router connects with ovn_cluster_router with a two-port switch and requires just a /30 subnet.

@dcbw @shettyg Any comments?

**Comment by dcbw** [comment]
@girishmg if I understand the issue correctly, this makes sense to me.

**Comment by shettyg** [comment]
I am not sure whether adding 600 additional logical switches to your setup instead of 1 will lead other bottlenecks. So you will have to do a rigorous performance analysis.

**Comment by shettyg** [comment]
>This ends up in creation of hundreds of thousands of logical flow entries in OVN SB’s lr_in_arp_resolve table across all of the 623 gateway routers.

Not clear to me why though. What IP addresses?

**Comment by girishmg** [comment]
> > This ends up in creation of hundreds of thousands of logical flow entries in OVN SB’s lr_in_arp_resolve table across all of the 623 gateway routers.
> 
> Not clear to me why though. What IP addresses?

@shettyg see the partial output from the 600+ node cluster

```
  table=9 (lr_in_arp_resolve  ), priority=100  , match=(outport == "rtoj-GR_node1" && reg0 == 100.64.0.154), action=(eth.dst = ee:c0:88:40:00:9b; next;)
  table=9 (lr_in_arp_resolve  ), priority=100  , match=(outport == "rtoj-GR_node1" && reg0 == 100.64.0.155), action=(eth.dst = ee:c0:88:40:00:9c; next;)
  table=9 (lr_in_arp_resolve  ), priority=100  , match=(outport == "rtoj-GR_node1" && reg0 == 100.64.0.156), action=(eth.dst = ee:c0:88:40:00:9d; next;)
  table=9 (lr_in_arp_resolve  ), priority=100  , match=(outport == "rtoj-GR_node1" && reg0 == 100.64.0.157), action=(eth.dst = ee:c0:88:40:00:9e; next;)
  table=9 (lr_in_arp_resolve  ), priority=100  , match=(outport == "rtoj-GR_node1" && reg0 == 100.64.0.158), action=(eth.dst = ee:c0:88:40:00:9f; next;)
```
per ovn-northd manpage 

```
     Ingress Table 8: ARP/ND Resolution

       Any packet that reaches this table is an IP packet whose next-hop  IPv4
       address  is  in  reg0 or IPv6 address is in xxreg0. (ip4.dst or ip6.dst
       contains the final destination.) This table resolves the IP address  in
       reg0 (or xxreg0) into an output port in outport and an Ethernet address
       in eth.dst,
```
Per the paragraph above, every L3 gateway router will have 621 such entries since each of the other 621 gateways can be IPv4 destination from the L3 gateway router as they are on the same broadcast domain.

**Comment by girishmg** [comment]
@dcbw @shettyg  I have a working prototype that we are testing internally and it is looking great. The number of flows are now in 5K range (from 3M). The CPU and memory utilization are normal.
